### ISSUE TITLE
Walker 2008 sex method

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#102]
There is no space to input a score for the Walker 2008 sex method.  Clicking the "Actions" button does nothing.

![image](https://user-images.githubusercontent.com/21186879/38500746-ed8eabdc-3bd0-11e8-9d4f-ccc8cf822a36.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1, @clegarde and @fedamann This is also a data issue, we do not have any method features defined for Walker 2008. DPAA anthropologist need to provide this method feature data

**Comment by SachinPawaskarUNO** [comment]
In the future CoRA will display the message below instead of the above message, if base data for method features has not been setup for a method.

![image](https://user-images.githubusercontent.com/19599773/38513056-ada9e26c-3bf2-11e8-9127-4008678edd6c.png)

**Comment by clegarde** [comment]
This method was in the original data, as well as the data I formatted for you in December @SachinPawaskarUNO, so we'll double-check through to make sure there aren't any others that went missing. Then we'll send one document to you with the data for only methods currently missing in CoRA.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, The method is there, but no method features. 
I like the idea of creating only a delta of what's missing in CoRA. I would recommend that you use CoRA UI to verify the current methods and method features in the system.

**Comment by skindsc1** [comment]
@SachinPawaskarUNO, This is one of those methods where a calculation needs to happen based on a feature.  Is it going to be possible to make the calculations happen if we give you that data (i.e., the equations to be used) along with the features needed?  @clegarde @fedamann

**Comment by clegarde** [comment]
Here is the data for the Walker 2008 method. 
[Walker 2008.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1924981/Walker.2008.xlsx)

**Comment by clegarde** [comment]
GTG
