### ISSUE TITLE
Function of the "All" action?

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#103]
What is the function of the "All" action?

![image](https://user-images.githubusercontent.com/21186879/38557596-270e5354-3c93-11e8-917d-de709431b87d.png)

It leads to an error:

![image](https://user-images.githubusercontent.com/21186879/38557662-4ec08fe8-3c93-11e8-9b7e-4a78c001f0e2.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue has been addressed with a new release. Please verify and close issue if verified.
