### ISSUE TITLE
Able to add a Pair Match without editing element

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#106]
When viewing an element I was able to add a pair match without first choosing to edit the element.

**Comment by skindsc1** [comment]
After playing with the site I can now see that all the other "Details" functions can be added without choosing to edit the element.  Should those also be locked down when not in the "Edit" mode?  Otherwise why lock down anything else?

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue has been addressed with a new release. Please verify and close issue if verified.
