### ISSUE TITLE
DNA > Additional tests > dropdown menu should be alphabetical

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#108]
![alphabetize additional tests](https://user-images.githubusercontent.com/34662044/38568595-8ed3c600-3cd8-11e8-8699-3d6087619e3c.jpg)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by emilystreetman** [comment]
Verified as fixed - closing ticket.
