### ISSUE TITLE
Combine submethods for Nawrocki 1998 (Cranium > Age)

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#111]
The Nawrocki 1998 data entry page should be a single page with 27 data entry points on it.  The current distinction of endocranial and ectocranial is problematic for data analysis, because composite scores use data from both "submethods".

![nawrocki submethods](https://user-images.githubusercontent.com/34662044/38641960-13ee68aa-3dc8-11e8-97d7-f0b349d75c9a.jpg)

Combining these submethods will avoid several points of data duplication and eliminate possibilities for transcription error, and simplify calculation of the two composite scores (SUMCAL and SUMALL) requested by @cbrown311 in tickets #72 and #73

This ticket is related to "composite" parent ticket #67. Following discussion with @clegarde @skindsc1 and @SachinPawaskarUNO in CoRA meeting 11Apr18. @SachinPawaskarUNO, please also see forthcoming email with details on how to calculate each composite score.

**Comment by clegarde** [comment]
This should also include the Nawrocki 1998 palatine features. All three of these are combined to generate ONE composite score (SUMALL) on the cranium. This method includes the three "submethods" (Ectocranial sutures, endocranial sutures, and palatine) with composite scores on the spreadsheet provided to you via email 11 April 2018. None of these could be applied to only one skeletal element, so the cranium would be the only skeletal element that would use any of these submethods.
In preparing this, I have noticed that the "Nawrocki 1998 Palatine" method actually contains ALL the features for all three of these submethods. Therefore, "Nawrocki 1998 ectocranial sutures" and "Nawrocki 1998 endocranial sutures" can be removed altogether, and the name of "Nawrocki 1998 Palatine" can be changed to just "Nawrocki 1998". @emilystreetman @SachinPawaskarUNO @fedamann 

![nawrocki 1998](https://user-images.githubusercontent.com/7350474/38680546-3696fe1c-3e2c-11e8-8e43-af526051fbfc.PNG)

**Comment by emilystreetman** [comment]
Verified as fixed - closing ticket.
