### ISSUE TITLE
Data entry options for Cranium > Ancestry > Hefner and Ousley 2014 should be 0 and 1 only

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#114]
To be discussed further with @clegarde and @fedamann : 

The current data entry options for Hefner and Ousley 2014 are derived from the scoring method detailed in Hefner 2009. To facilitate the calculation of the SUMMED OSSA (composite) score required for Hefner and Ousley 2014, I suggest the data entry follow the OSSA score for each trait, allowing only 0s and 1s for each data point. If this is adopted, I would also change the trait names to clarify that the range is OSSA's 0-1 and not Hefner 2009's 1-3, 0-4, or 0-1. (E.g., from "anterior nasal spine" to "Anterior nasal spine (ANS) OSSA Score").

Changing this approach would reduce error by eliminating 6 points of redundant data entry by users, and be more precise, since the current data points and scores are not actually described in Hefner and Ousley 2014.

Future automation optimization idea discussed by @clegarde and me: entries saved to Hefner 2009 as 0-4 would be automatically assessed as being above or below the OSSA threshold (Hefner and Ousley 2014) and would be automatically populated into the Hefner and Ousley 2014 page as 0s or 1s, reducing human error in translating between the two methods, and allowing for autocalculation of the summed ossa score by CoRA.

This ticket is related to "composite" parent ticket #67

**Comment by emilystreetman** [comment]
Update: all data entry options retain Hefner 09 values, and composite score calculates with a possible range of 4-19.  However, composite score search option is limited to range 0-6.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by emilystreetman** [comment]
Verified as addressed. Closing ticket.
