### ISSUE TITLE
Cannot delete a Trauma or Pathology

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#115]
Under skeletal element, Pathology, a trauma or pathology cannot be deleted. The icon for deleting a trauma and pathology is there, and it pops up with the "are you sure you want to delete?", but then an error message pops up. You can delete an anomaly.
![deleting trauma](https://user-images.githubusercontent.com/7350474/38681503-75a6b05a-3e2e-11e8-9f90-b474d7a07777.PNG)

**Comment by nmcelroy** [comment]
@clegarde Hi, I tried to replicate this issue and the delete is working for me on traumas/pathologies. When I put in the multi zone selection option for these two I thought I fixed the delete as well. Could you give any additional information/screenshots that might help me recreate the issue? Thanks!

**Comment by clegarde** [comment]
I added traumas under the following cranium: CIL 2003-116-G-01-X-232C-101. I click delete.
![trauma_1](https://user-images.githubusercontent.com/7350474/38690094-e1c3f78e-3e42-11e8-87e8-b294f9361cd3.PNG)
Then I get the following message, I click "ok."
![trauma_2](https://user-images.githubusercontent.com/7350474/38690140-fb816cba-3e42-11e8-9523-72e1cb4d2e51.PNG)
Then I get the error.
![trauma_3](https://user-images.githubusercontent.com/7350474/38690151-017da91c-3e43-11e8-9c68-508b0e8efb47.PNG)

**Comment by clegarde** [comment]
This was something we had addressed earlier this winter, when the delete option was added. There were permission issues, so I don't know if that's playing a role here.  But I am deleting something I added, so I should be able to delete it. I could see it giving me a "permissions" error if it was me trying to delete someone else's.

**Comment by nmcelroy** [comment]
Ok, thank you! It was a permission issue.

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
