### ISSUE TITLE
Can't open a skeletal element

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#117]
I can't open a skeletal element. Clicking "Search" or "new" results in the "Whoops something went wrong" screen. You can do the search under "DNA", but when clicking on a skeletal element, it goes to the "Whoops something went wrong" screen again.
![screen shot 2018-04-15 at 8 39 22 am](https://user-images.githubusercontent.com/7350474/38779068-e6a1d184-4088-11e8-8a89-2fea7dcb5737.png)
![screen shot 2018-04-15 at 8 41 56 am](https://user-images.githubusercontent.com/7350474/38779071-ecf12224-4088-11e8-966c-1278b82476a6.png)

**Comment by SachinPawaskarUNO** [comment]
Carrie,
I think you got that error, because I was doing a quick tweak on cora-cat.
Can you please try again and let me know?

Respectfully,
Sachin Pawaskar, Ph.D, MBA, MS
College of Information Science and Technology
University of Nebraska at Omaha
Office: PKI 277-C
Tel: (402) 554-4904

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
Yep, GTG.
