### ISSUE TITLE
Unable to delete pathology or trauma 

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#121]
After adding pathology or trauma I have not been able to delete them (by clicking on the red trash can).

![image](https://user-images.githubusercontent.com/21186879/38811446-1e8bd51a-414f-11e8-80df-821cd8c8efda.png)

**Comment by clegarde** [comment]
@SachinPawaskarUNO @skindsc1 , I can add and delete (I tried again since I closed my ticket yesterday to make sure with your update last night it still worked), so maybe this is still a permissions issue?

**Comment by nmcelroy** [comment]
@skindsc1 I looked into this and tried to recreate the issue by logging into an anthropologist account and switching projects. I had no problems when doing this, so I was wondering if this problem is happening to any other anthropologists as well or if it's only on your account?

**Comment by skindsc1** [comment]
@nmcelroy @SachinPawaskarUNO  I just logged in and was able to delete pathology/trauma.  Not sure what was going on yesterday but I will close this ticket now.  I have not heard of anyone else having this problem.
