### ISSUE TITLE
Add a "Search" button to search function

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#122]
When searching for an element (by bone, designator, etc.) could we update the search function to add a "Search" button that must be pushed in order to initiate the search?  Right now it will search when the drop down is activated but if you access the drop down before updating the search bar you will get the message that elements cannot be found.  Adding a button that must be pushed in order to search would make the search function more intuitive.

@emilystreetman

**Comment by emilystreetman** [comment]
I also think that it is unintuitive that typing "cranium" and hitting Enter finds no results.

Instead, I suggest that the current search function would be more intuitive if it were represented by a typing bar, a required dropdown, and a search button that worked with hitting Enter. This would also allow a user to select the search method before typing into the box.

**Comment by emilystreetman** [comment]
I think it's worth looking at this ticket again to see if the v1.0.0 release captures the desired search function. @skindsc1 @clegarde

**Comment by skindsc1** [comment]
I'm satisfied with the current search function in v1.0.0
