### ISSUE TITLE
Add headers/label to separate features (endo vs ecto) for Nawrocki 1998 (cranium, age)

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#124]
Because features have the same name (different abbreviations) for endo- and ectocranial features, it would help ensure the data isn't entered in the wrong spot if Ectocranial, Endocranial, and Palatine were added to separate the sections.
![nawrocki 1998_headers](https://user-images.githubusercontent.com/7350474/38823038-e9eeee48-416a-11e8-8386-bc9fb70a4f95.PNG)
![nawrocki 1998_headers2](https://user-images.githubusercontent.com/7350474/38823043-ec07279a-416a-11e8-9bf1-997690223298.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde I have added a method feature group filtering capability, this will allow you to see which features are related to which groups (e.g Cranium - Age - Nowrocki 1998, has feature groups Ectocranial, Endocranial, and Palatine). Please note we can also add this capability to other methods that have feature groups.
This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
