### ISSUE TITLE
Add new description for McKern & Stewart (1957) - pubic symphysis

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#126]
Since we separated this submethod, it pulled the original description. 
![mckern and stewart_pubicsymph description](https://user-images.githubusercontent.com/7350474/38825683-21336f16-4173-11e8-8350-f30df0414be5.PNG)

Should be "Age estimation by scoring morphological features of the pubic symphysis."

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
“on various skeletal elements” needs to be deleted because it is only on the os coxa. It could say “on the os coxa” but I don’t think that’s necessary.

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
