### ISSUE TITLE
Add "Possible" to Trauma types 

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#127]
@clegarde @fedamann 
Suggest adding the following types of Trauma to the drop-down menu, recording observations that cannot be definitively assessed as trauma can still be useful in large and commingled assemblages: 
Possible antemortem
Possible antemortem - blunt force 
Possible antemortem - sharp force
Possible antemortem - projectile
Possible antemortem - treatment
Possible perimortem 
Possible perimortem - blunt force
Possible perimortem - sharp force
Possible perimortem - projectile

![cora trauma](https://user-images.githubusercontent.com/35308331/38881118-f1bcda3c-422c-11e8-93c7-5b6a74517b63.JPG)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by tlvandeest** [comment]
@SachinPawaskarUNO All suggested additional labels have been added.
