### ISSUE TITLE
Capability to sort/search for elements by age

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#13]
For example, if I have a left clavicle that has been given a McKern and Stewart stage of 0, I want to find all right clavicles that have also been given a stage of 0.  Currently I can find all the right clavicles but there is no indication of whether an age has been provided and I cannot open a specific bone from the list of results.

**Comment by skindsc1** [comment]
Just had a very productive discussion with @SachinPawaskarUNO and he showed me how to step by step recreate the issue
![image](https://user-images.githubusercontent.com/21186879/34626833-dfd26a3e-f223-11e7-8133-b85fe8fbbaeb.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 Please verify

**Comment by skindsc1** [comment]
Verified and closed.
