### ISSUE TITLE
Change features scores for Mann et al 1991 > Cranium > Age

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#132]
Change feature scores from 0 and 1 to "open", "partial obliteration", "complete obliteration" for all four features (incisive, posterior median palatine, transverse palatine, anterior median palatine).

![mann et al 1991_feature scores](https://user-images.githubusercontent.com/7350474/38947006-c9d96146-4300-11e8-949b-3fa0fe657195.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
