### ISSUE TITLE
Change default search response message

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#133]
When searching, if ENTER is used following entry of the search term the following response is received. 
![cora search method](https://user-images.githubusercontent.com/35308331/38947245-9e2be0ea-4301-11e8-8992-b65ac594284c.JPG)
 The search response should read something like: "No skeletal element records found. Ensure you have used the drop down menu to select the type of search intended. The default search is for accession number."  
@SachinPawaskarUNO @fedamann #122

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by tlvandeest** [comment]
Message change verified. The following typos were noted:  
1. Add period after "...by Bone"
2. "s" should be removed from "Skeletal Elements records" so it read "Skeletal Element records" @SachinPawaskarUNO @clegarde

**Comment by tlvandeest** [comment]
Corrections verified.
