### ISSUE TITLE
Update feature score for Osteophyte Formation > Falys and Prangle 2015 (clavicle, age)

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#134]
Feature score should only be 1 to 4 for the osteophyte formation feature. So the composite score range is 3 to 16. Sorry we missed this when we compiled the composite score data.
![falys and prangle 2015_osteophyte score](https://user-images.githubusercontent.com/7350474/38953915-ceba32f2-4315-11e8-9d61-c9e33453bd37.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
