### ISSUE TITLE
Skeletal Element Page layout in Safari

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#137]
When I add a new skeletal element, the view skeletal element page has an odd layout: 
![new skeletal element](https://user-images.githubusercontent.com/7350474/39097595-0882adc8-4624-11e8-9ef4-505ef1b562ad.png)

I closed out and went back in to see if it would change back to the normal, but it does not. This is what other skeletal element pages look like (ones that I have not added):
![view skeletal element](https://user-images.githubusercontent.com/7350474/39097607-20acca1e-4624-11e8-83dc-d164e7376737.png)

Just wanted to make you aware of how it is showing up in Safari.

**Comment by clegarde** [comment]
I'm using Safari 11.1, OS X. But it's only doing this on the elements that I have added, so I'm not sure what that's all about. Maybe it's just something with my computer.

**Comment by SachinPawaskarUNO** [comment]
What is the Mac OS, is it High Sierra version 10.13.4?

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

I think I have a fix for this, it is an issue with how some browser engines are more strict than others.

**Comment by clegarde** [comment]
Looks good now!
