### ISSUE TITLE
CoRA shouldn't allow the same "composite key" to be entered twice

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#138]
@fedamann @skindsc1 @cbrown311 @mei215, would there be a time that we'd ever be entering the same "composite key" twice? If possible, I think CoRA should provide an error message if you try to enter a "composite key" that has been used before. I can't think of a scenario where you'd want to enter the same accession, provenience 1 and 2, and designator. At least one of these fields should be different. This could help with data entry error if CoRA doesn't let you. If that's possible, @SachinPawaskarUNO?
![composite key](https://user-images.githubusercontent.com/7350474/39097687-4122a68c-4625-11e8-80e3-24ea5f21f009.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
