### ISSUE TITLE
Rollover measurement descriptions not displaying

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#139]
When on the measurement page and hovering on the "?" icon for a measurement description, the description is not popping up - the cursor changes from the arrow to the "I" shape.  This happens in both Edge and IE and occurs regardless of whether the element is locked down or editing is enabled.

**Comment by SachinPawaskarUNO** [comment]
@spawaskar-cora/cora-administrators to look at this one someone's machine at DPAA lab

**Comment by skindsc1** [comment]
Just checked this on my computer and it is displaying now (in Edge).  Closing.
