### ISSUE TITLE
Create a report for Pathology and Trauma

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#140]
There is currently no way to search for elements that have pathology or trauma listed.  This may be helpful if looking for a pathology that is systemic or bilateral within the assemblage, or for trauma that may have affected multiple elements (for example, a tibia-fibula combination).

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 Please verify

**Comment by skindsc1** [comment]
The report looks good for now so I will close the ticket.  We may want to add some results to the report such as DNA sample number, I-#, and sequence # but that can be a separate ticket.
