### ISSUE TITLE
Correction to Samworth and Gowland (Os coxa - Age)

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#141]
A correction is needed for the Samworth and Gowland (2007) method for age using the os coxa.
The pubic symphysis drop-down should be 1 through 6, currently it is 1 through 3.  
@clegarde @SachinPawaskarUNO 
![cora samworth and gowland](https://user-images.githubusercontent.com/35308331/39209850-a0077710-47cc-11e8-8e95-187555c25ec3.JPG)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by tlvandeest** [comment]
Correction verified
