### ISSUE TITLE
Correction to Phenice (Os coxa - Sex)

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#142]
A correction is needed to the Phenice (1969) method for sex using the os coxa.  One trait is absent entirely. 
A line for scoring the  "Ventral Arc" should be added.  Scoring for the drop down menu is 1 through 3 (same as other two traits in method). 
@clegarde @SachinPawaskarUNO 
![cora phenice](https://user-images.githubusercontent.com/35308331/39210113-5f1c2416-47cd-11e8-98c7-1e9d59c09a59.JPG)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by tlvandeest** [comment]
Correction verified.
