### ISSUE TITLE
Delete McKern and Stewart for Cranium only (Age)

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#143]
McKern and Stewart (1957) only uses cranial sutures for the cranium, which the authors state are unreliable for age estimation based on their sample and should not be used. It is currently not a defined, useable method in CoRA and suggest it be removed from the drop down menu for the cranium. Discussed with C. LeGarde.  @clegarde @fedamann @SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by tlvandeest** [comment]
McKern and Stewart 1957 is still in the drop down menu for the age methods in the cranium. @SachinPawaskarUNO @clegarde

**Comment by tlvandeest** [comment]
Deletion verified.
