### ISSUE TITLE
Add Search ability to find bones with Trauma, Anomaly, or Pathology

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#144]
Suggest adding the ability to search for elements that have Trauma, Anomaly, or Pathology recorded.  This can be used for cases in which trauma is present and fragments may potentially be associated based on shared trauma within or between elements.  Same is true for anomalies and pathologies that can affect adjacent elements or is generally bilateral in occurrence. In trauma/pathology instances, it is common that metrics cannot be used or taken for sorting and associations. @fedamann @SachinPawaskarUNO

**Comment by emilystreetman** [comment]
Duplicate to ticket #140

**Comment by tlvandeest** [comment]
Verified as covered by implementation of Trauma, Pathological Condition, and Anomaly Report.
