### ISSUE TITLE
Add Mincer et al 1993 data > cranium > age

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#145]
When adding this method for age of the cranium, the following error pops up:
![mincer et al_1993](https://user-images.githubusercontent.com/7350474/39212903-b2a98e4a-47d5-11e8-93f4-3ef7192bb7de.PNG)

I believe this means there is no data. The data for features and scoring is attached.
[Mincer.et.al_1993_Features-Scores.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1944812/Mincer.et.al_1993_Features-Scores.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This was a slightly different issue, it was bad data provided by anthros. I have fixed the bad data. Most of these bones using this method currently have only one feature name **Third molar apical root development**, I'm Ok with changing this and add Tooth 1 and Tooth 16, etc. Just want to make sure that I clarify this and give the other anthros a change to discuss before we proceed. Lets talk about this in tomorrows SCRUM.
@fedamann, We need to discuss this and other Tooth related changes/features/module

**Comment by emilystreetman** [comment]
@clegarde Please check in on Blankenship and Kasper methods

**Comment by clegarde** [comment]
Updated formatting [ to { and added Blankenship and Kasper to the spreadsheet. These should all have the tooth listed as a feature. Blankenship and Mincer have the same scores (D-H), but Kasper had a couple extra (B-H). @SachinPawaskarUNO 

[Third molar aging.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1947935/Third.molar.aging.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
