### ISSUE TITLE
Buikstra and Ubelaker 1994 < Cranium and Os coxa < Sex

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#147]
The features/scores are missing from CoRA for Buikstra and Ubelaker 1994 for the cranium, mandible and os coxa for sex. The data is attached.
[Buikstra and Ubelaker 1994_Feature-scores.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1945039/Buikstra.and.Ubelaker.1994_Feature-scores.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
