### ISSUE TITLE
Hierarchical groups for inventory

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#157]
per discussion with @fedamann, here is a list for hierarchical groupings for inventory. This is NOT the same as the groupings for the articulation report groups (#116) although they are similar. This list has them separated out a bit further (could be thought of as subgroupings from the other list). 
[CoRA_Hierarchical inventory groupings.xlsx](https://github.com/spawaskar-cora/cora-docs/files/2023045/CoRA_Hierarchical.inventory.groupings.xlsx)

**Comment by emilystreetman** [comment]
Ticket #254 (re-verifying these groups) is closed. @clegarde could we verify and close this one since the original request is active in CAT?

**Comment by SachinPawaskarUNO** [comment]
@clegarde Can we please verify this issue? 
I'm hoping we have addressed most of what was originally discussed, I'm just not sure.

**Comment by clegarde** [comment]
GTG
