### ISSUE TITLE
Skeletal Elements > Mito Sequence Number Search Issue

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#158]
When I tried to search by mito sequence number under Skeletal Elements, I get an error message. See below for screenshots.
![cora_searchissue](https://user-images.githubusercontent.com/34749060/40372204-da01412e-5da9-11e8-93bb-1af6e8afc721.png)
![cora_searchissue2](https://user-images.githubusercontent.com/34749060/40372236-e08dcb7a-5da9-11e8-9fa3-1046566255bc.png)

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Please verify this is CAT and close out issue if verified.

**Comment by nyukyi** [comment]
@SachinPawaskarUNO Verified & closing this issue now.
