### ISSUE TITLE
Autoopen in new window when clicking Combination Key from the Search Results

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#159]
To preserve search results, the link to each element should auto-open in a new window based on the group discussion on 22 May 18.  @clegarde @fedamann @SachinPawaskarUNO @emilystreetman

**Comment by emilystreetman** [comment]
I believe this suggestion is integrated into the V1.0.0 - @tlvandeest please verify?

**Comment by tlvandeest** [comment]
This does happen now in V 1.0.0.  Confirmed and closed.
