### ISSUE TITLE
Zones guide with descriptions

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#16]
@emilystreetman markdown descriptions for Zone method of skeletal inventory by element.

**Comment by emilystreetman** [comment]
This item is complete pending getting additional skull images from the artist - for current guide, please see  cora-docs/docs/forensics-anthro-guide/zones.md

**Comment by emilystreetman** [comment]
Images and guide have been updated. Pull request will be created when measurements sections has also been updated.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman will create a pull request by 05/31/2018

**Comment by emilystreetman** [comment]
I believe the zones guide is complete. Perhaps this ticket can be closed and new tickets raised regarding dental inventory? Currently, teeth are not included in the zonation method for the skull. @fedamann

**Comment by fedamann** [comment]
Verified and closed.
