### ISSUE TITLE
Inventory and Zones should be linked for entering New Skeletal Element

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#160]
For ease of entry and reducing time for each element, initial entry of a skeletal element including the zones page or easily transitioned to the zones page would greatly improve the process. @clegarde @fedamann @SachinPawaskarUNO

**Comment by fedamann** [comment]
@tlvandeest verify the update pls

**Comment by tlvandeest** [comment]
Verfied this issue taken care of in v1.0.0 with selection of automatic next page when creating new element.
