### ISSUE TITLE
Articulations for hierarchical groups

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#162]
@SachinPawaskarUNO @clegarde  Is it possible to automatically generate the articulations for hierarchical groups categories when they're selected so that this information does not have to be manually entered?

Linking to issue #157 : Hierarchical groups for inventory

**Comment by emilystreetman** [comment]
@CTegtmeyer We haven't talked about this one in scrum for a while. Do you think it's ready to close since the original issue is now addressed in CAT? (New issues with teeth aside.)

**Comment by CTegtmeyer** [comment]
@emilystreetman Yes, I think this issue has been sufficiently addressed. I will close this issue.
