### ISSUE TITLE
Make "Mito Sequence Subgroup" alphaneumeric

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#164]
The "Mito Sequence Subgroup" box should allow letters and numbers.

![image](https://user-images.githubusercontent.com/21186879/40660540-e9084e20-6316-11e8-8a3b-8a93ab43c16c.png)

**Comment by skindsc1** [comment]
@nmcelroy It should also allow hyphens.  For example, we should be able to enter "A-1" in the subgroup box.

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#134

**Comment by SachinPawaskarUNO** [comment]
@skindsc1, Can you please verify this issue?

**Comment by skindsc1** [comment]
@SachinPawaskarUNO @nmcelroy Yes, I can confirm this works.  Just FYI, it took me several tries before it successfully saved the subsequence and in at least one case I did not get the green bar message at the top that said my changes were made successfully.
