### ISSUE TITLE
Updates to the "Test Type" drop down list in additional DNA testing

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#165]
In the "Test Type" dropdown for additional DNA tests, the "tr" in YStr and AStr should be capitalized.  These are abbreviations and should follow the same capitalization rule as all the others in the list (for example,, Next Generation Sequencing = NGS)

Additionally, AStr should be updated to AuSTR.  AuSTR is the abbreviation we use in reports when discussing autosomal testing.  To many anthropologists ASTR will indicate Ancient DNA.

![image](https://user-images.githubusercontent.com/21186879/40663834-322e72de-631f-11e8-97fb-ce564e1fd761.png)

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#126

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 Please verify

**Comment by emilystreetman** [comment]
attempted to visit DNA page after saving "DNA sampled" for right fibula CIL 2018-351-X-5405--408, and received this error:
![image](https://user-images.githubusercontent.com/34662044/49388720-35313e80-f6ea-11e8-8860-a1fd3640ab03.png)

**Comment by rpernst** [comment]
the error was fixed with pull request sachinpawaskaruno/cora2#584

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 @emilystreetman Please verify

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman With the new design changes there will be no new screen for Additional DNA testing. The data fields for additional testing will now be under the DNA sample. The reason for this is that if additional tests are are done from the same sample then they will be fields for that DNA sample number that can be filled out (such as loci for ..., etc). If additional testing is being done with a new sample, then a new DNA sample record must be created and the appropriate data fields can be filled out.
Maybe what you can do is check if necessary fields are available on the DNA record for different types of tests.

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy will explain how to create a new DNA sample. within the same element.

@emilystreetman Please note that the DNA module is going to change further in the upcoming releases after v1.0.0 is deployed based upon conversation with AFDIL. We will be having additional discussions on this topic at a later date. For now I'm going to remove the v1.0.0 tag from this issue and we will handle this separately in the future.

**Comment by SachinPawaskarUNO** [comment]
This has been addressed with the v1.1.1 release
