### ISSUE TITLE
Check of Min and Max limits for measurements needed

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#167]
Biologically impossible numbers were listed as the minimum and maximum thresholds for the ulna were discovered during data entry.  Suggest that the spreadsheet for the soft and hard thresholds be checked. See attached image. @clegarde @fedamann @SachinPawaskarUNO 
![cora measurement thresholds](https://user-images.githubusercontent.com/35308331/40747306-7be0976e-6422-11e8-8c19-f29da59b9c6e.JPG)

**Comment by sfuehr** [comment]
The same problem @tlvandeest mentions for the ulna occurs with the foreman magnum length and breadth measurements for the cranium. The minimum and maximum thresholds are too large for these two measurements. @SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
@fedamann, can we please assign an anthropologist to go over the spreadsheet provided to verify the measurement threshold values and if necessary fix any issues such as those mentioned in this ticket and attach an updated spreadsheet to this ticket. @clegarde, it would be a good idea to attach the latest spreadsheet to this ticket for others such as @tlvandeest, @sfuehr to take a look at and potentially suggest/propose changes

**Comment by fedamann** [comment]
@sachin yes; we'll get it sorted.

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#482

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest and @fedamann, Can we please verify this issue?

**Comment by emilystreetman** [comment]
@skindsc1 has offered to verify #239, which is a similar measurement threshold issue and also the root ticket #60 - you guys may want to communicate to avoid duplicating efforts. unique issue in this ticket may be the error message for elements with no thresholds noted by @tlvandeest on may 30

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest Please verify

**Comment by tlvandeest** [comment]
Verified min and max thresholds and measurement entry can be done for calcaneus and talus.  Other element min and max values covered in #249 so closing this ticket.
