### ISSUE TITLE
on articulation screen, order bones by most recent created timestamp

### ISSUE THREAD

**Issue by veronicak7** [spawaskar-cora/cora-docs#172]
on articulation screen, order bones by most recent created timestamp.

![capture](https://user-images.githubusercontent.com/39967521/40999196-b10e6368-68f9-11e8-9e93-3c664231f8b2.PNG)

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#244

**Comment by SachinPawaskarUNO** [comment]
@veronicak7 and @fedamann Can you please verify this issue?

**Comment by SachinPawaskarUNO** [comment]
@veronicak7 and @fedamann Can you please verify this issue?

**Comment by emilystreetman** [comment]
Verified, closing. I created designators 345, 346, and 347. When I clicked the dropdown menu for 346, the other two were the first and second selections:
![image](https://user-images.githubusercontent.com/34662044/49392763-05d3ff00-f6f5-11e8-9767-2780e889c5df.png)
