### ISSUE TITLE
Ability to indicate isotope sampling

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#173]
Ability to indicate isotope sampling, see image below

<img width="484" alt="isotope image" src="https://user-images.githubusercontent.com/33848426/41118713-7c07b546-6a2c-11e8-973c-7a99bcbdc5b0.PNG">

**Comment by SachinPawaskarUNO** [comment]
@TarawaProject This has been implemented, Please verify

**Comment by CTegtmeyer** [comment]
Verified
