### ISSUE TITLE
Ability to add trauma information by bone group

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#176]
Ability to add trauma information by bone group. Example: blunt force trauma to shoulder

**Comment by rpernst** [comment]
This feature was added with this change SachingPawaskarUNO/cora2#235

**Comment by emilystreetman** [comment]
This looks like it is active in cat.coracore.org - @TarawaProject if you agree, will you please close the ticket?
![image](https://user-images.githubusercontent.com/34662044/47872735-5c3fdc00-dddd-11e8-966e-6695e6631844.png)

**Comment by CTegtmeyer** [comment]
This has been verified
