### ISSUE TITLE
Add type of mito testing to DNA module

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#177]
Add type of mito testing to DNA module. see image below

![image](https://user-images.githubusercontent.com/33848426/41119453-85b65aaa-6a2e-11e8-8feb-5bd8ddcf2169.png)

**Comment by nmcelroy** [comment]
Addressed this in SachinPawaskarUNO/cora2#250

**Comment by TarawaProject** [comment]
verified
