### ISSUE TITLE
Ability to add # of loci to additional testing

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#178]
Ability to add # of loci to additional testing. See below.
<img width="476" alt="dna loci" src="https://user-images.githubusercontent.com/33848426/41119836-95300b56-6a2f-11e8-9b2a-1b37f5c9496a.PNG">

**Comment by nmcelroy** [comment]
Addressed this in SachinPawaskarUNO/cora2#250

**Comment by TarawaProject** [comment]
verified that this was added
