### ISSUE TITLE
Link measurement standards table to CoRA Docs

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#18]
@SachinPawaskarUNO @clegarde @jjlynch2  Link Jeff's measurement standards table (https://osteocoder.com/projects/measurement-standards/) to CoRA Docs measurement documentation.

**Comment by SachinPawaskarUNO** [comment]
This issue has been fixed by @clegarde and Sachin with commit [6d3999c](https://github.com/spawaskar-cora/cora-docs/commit/6d3999ced2f4e2f9a74b3b93d9de5600b7810cea)
