### ISSUE TITLE
Create search capabilities by accession, provenance 1, provenance 2 for reports

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#180]
Create search capabilities by accession, provenance 1, provenance 2 for the following reports: mtDNA, methods, articulation, measurements, zones

**Comment by SachinPawaskarUNO** [comment]
@TarawaProject and @fedamann Can you please verify this issue?

**Comment by CTegtmeyer** [comment]
This issue has been verified
