### ISSUE TITLE
Add skeletal bone named "unidentified rib fragments"

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#181]
Add skeletal bone named "unidentified rib fragments"

**Comment by emilystreetman** [comment]
@SachinPawaskarUNO, you mentioned phalanges in the meeting today. 

I am commenting here to note that there are several possible phalanges entries that would benefit from this same "count" option. They include phalanges that begin with "unidentified" and "unseriated", totaling 7 different skeletal element names. (unidentified phalanx; unseriated proximal manual phalanx; unseriate proximal pedal phalanx; unseriated intermediate manual phalanx; etc)

I'm not sure whether John's comment about recording mass was intended to replace count, but count would be quite useful for phalanges.

**Comment by SachinPawaskarUNO** [comment]
@TarawaProject, Please verify that a new skeletal bone named "unidentified rib fragments" is now available for inventory in CoRA.

**Comment by CTegtmeyer** [comment]
this issue is verified
