### ISSUE TITLE
Add new field for skeletal element named consolidated AN

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#183]
Add new field for skeletal element named consolidated AN
add ability to report by consolidated AN

**Comment by clegarde** [comment]
Based on conversations with project leads (@TarawaProject ) and Sachin, this ability already exists. This is the "Individual Number" field. This can be reported and searched. 
Previous consolidation is not accounted for in CoRA, so #199 was added to fit that need.

**Comment by emilystreetman** [comment]
@TarawaProject If this is ok, will you please close the ticket? Please see also the 24Aug18 comment by Franklin on #199, which explains why the existing fields can capture the desired info.
