### ISSUE TITLE
On hover of over column headers show display name for measurement reports

### ISSUE THREAD

**Issue by TarawaProject** [spawaskar-cora/cora-docs#185]
On hover of over column headers show display name for measurement reports. See image below.
<img width="709" alt="measurement info" src="https://user-images.githubusercontent.com/33848426/41124590-29ee7206-6a3e-11e8-86b9-6657add96b57.PNG">

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#245

**Comment by SachinPawaskarUNO** [comment]
@fedamann and @TarawaProject This issue has now been addressed by showing the appropriate bone cora-docs measurements in the right hand side slideout panel.
@TarawaProject Can you please verify this issue?

**Comment by CTegtmeyer** [comment]
This issue has been verified. Cora-docs is in the right had side of the screen on the measurement search page.
