### ISSUE TITLE
Cervical Vertebrae measurements not present for entry

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#189]
Measurements are not present for Cervical Vertebra 1 and Cervical Vertebra 2 for entry under these elements. Measurement definitions provided in the CoRAdoc for Cer_1, Cer_2, and Cer_3.  @clegarde @SachinPawaskarUNO

**Comment by clegarde** [comment]
@SachinPawaskarUNO Find the measurements with their description and threshold values attached. There are actually 6 measurements for the two bones.
[Vertebrae measurements.xlsx](https://github.com/spawaskar-cora/cora-docs/files/2090843/Vertebrae.measurements.xlsx)

**Comment by nmcelroy** [comment]
Related to #191 
Addressed in fix.

**Comment by tlvandeest** [comment]
Confirmed in v 1.0.0 and closed.
