### ISSUE TITLE
Cannot enter measurements for Talus and Calcaneus

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#191]
When entering the TAL_03, CAL_03, and CAL-04, the following error is received: 
![calcaneal measurement error](https://user-images.githubusercontent.com/35308331/41243819-dcbe2796-6d68-11e8-90a1-8f1b955d705a.JPG)

For these three measurements only, a second error of "You must enter a valid value" appears on the actual measurement entry page: 

![cora valid measurement error](https://user-images.githubusercontent.com/35308331/41244148-ccebcd0e-6d69-11e8-84c0-0cf29d691454.jpg)

Unless, these measurements are blank, any other measurements entered cannot be saved. 
@clegarde @SachinPawaskarUNO

**Comment by nmcelroy** [comment]
Related to #189 
Addressed in fix.

**Comment by tlvandeest** [comment]
Confirmed in v 1.0.0 and closed.
