### ISSUE TITLE
Add articulation of Metatarsal 1 to Proximal pedal phalanx 1

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#192]
Under Articulations, a Metatarsal 1 cannot be articulated to a Proximal pedal phalanx 1, but the articulation can be listed the other way around (Proximal pedal phalanx 1 to Metatarsal 1).  
This articulation will then only appear under Proximal pedal phalanx 1 and NOT under Metatarsal 1. 
![cora mt1 to ppp1](https://user-images.githubusercontent.com/35308331/41244470-bd42fd4a-6d6a-11e8-8ad9-5367d0e938a4.JPG)
![cora ppp1 to mt1](https://user-images.githubusercontent.com/35308331/41244472-be729b12-6d6a-11e8-98e0-0df084edc235.JPG)
@clegarde @SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest, I think this should be a simple fix, The original articulation seed data provided by the anthropologists is missing that articulation record. @SachinPawaskarUNO will add this seed data articulation record.

**Comment by tlvandeest** [comment]
Confirmed as present in v 1.0.0 and closed.
