### ISSUE TITLE
New Users and assignment to Ploesti project

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#197]
Sachin, 
Please add the following interns to the Ploesti Project in CoRA so they can
assist. I have discussed this with Dr. Ingvoldstad also. They are already
listed for the USS Oklahoma, but let me know if you need their email
addresses.  Dr. Damann is out of the office currently, so he is not
available to add them at this time.    
Megan McCollum
Abigail Kindler
Sihley Pawaskar
Lindsay Gilliland

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest and @mei215, Currently we already have accounts for Megan and Abby in CoRA. So I have added them to the Ploesti project. You need to provide additional information for Sihley and Lindsay, namely their email addresses which is a required field for login into CoRA.
Please verify with Megan and Abby that they now access to the Ploesti project and let me know.

Also going forward please send such requests by creating an issue on CoRA docs.

@fedamann FYI, Doing this as you are on vacation.

**Comment by tlvandeest** [comment]
@sachin I request that when an email is sent to you directly with contact information you not put that into a GitHub ticket without my knowledge.  These tickets can be found and viewed online without being logged into Github and so my contact information was removed from the comment above.

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest I agree with you, that was an inadvertent copy paste error, my apologies.
