### ISSUE TITLE
Clavicle triage - only show for clavicles?

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#198]
Can the "clavicle triage" checkbox only show up for clavicles? Since it only applies to that skeletal element, can it not show up for other skeletal elements? It will never be checked for any other skeletal element (like the one shown here) so if we're looking at the number of that have been triaged vs not (thinking about dashboard @SachinPawaskarUNO ), it will be inflated because it will be showing for all skeletal elements, right? 
![clavicle triage](https://user-images.githubusercontent.com/7350474/41810214-6b2e8542-76c0-11e8-9427-0b82381a1b75.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde, I agree, that is a good idea. We will have to change the dashboard accordingly, because it currently shows percentage for all SEs, this should be percentage of Clavicle (SEs) only.

**Comment by emilystreetman** [comment]
This looks good to me in cat (but I don't have admin dashboard access to verify there) - @clegarde will you please close if you agree?
![noclavicletriage1](https://user-images.githubusercontent.com/34662044/47869848-fac83f00-ddd5-11e8-9e38-e10f8a0520ae.JPG)
![noclavicletriage2](https://user-images.githubusercontent.com/34662044/47869854-fdc32f80-ddd5-11e8-94e5-55e00c9ef46a.JPG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Can you please verify this?

**Comment by clegarde** [comment]
GTG
