### ISSUE TITLE
Add "Original Accession" field to skeletal element

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#199]
Stemming from conversations with @TarawaProject and other projects. If it could appear on the view skeletal element.
![view skeletal element](https://user-images.githubusercontent.com/7350474/41810234-ecf30d00-76c0-11e8-9af5-9d0227917382.png)

**Comment by fedamann** [comment]
Per conversation this week among projects teams at Offutt and Hawaii we will use current flexibility of Accession, Provenance1, Provenance2, and Individual Number to deal with the issues around maintaining legacy accession numbers.  The business rule for this is project specific (i.e., Project Lead decision) and must be applied consistently by all project team members.  @clegarde @TarawaProject @Megyesimm @akoehl @SachinPawaskarUNO

**Comment by emilystreetman** [comment]
Hi @clegarde following Franklin's above comment, if it's ok to close this ticket, will you please do so? Thank you!
