### ISSUE TITLE
Link to associated element in Articulations/Pair Match/Refit Details page

### ISSUE THREAD

**Issue by lfkennedy** [spawaskar-cora/cora-docs#200]
It would be convenient to be able to navigate directly to associated elements, particularly as these do not often/always share sequence data or provenience.  The picture below shows the "Articulations" page as an example, where the associated element is circled.  

Could the circled text be made into a link to this element's page?  At the very least, could this string of text be reformatted so that it can be highlighted for copy/paste functionality into the search bar?

![slide2](https://user-images.githubusercontent.com/35273714/41912457-7496f50e-7915-11e8-84f2-57c79c60c999.JPG)

**Comment by rpernst** [comment]
A datatable was added to the association pages with links so that an associated element can be quickly viewed. This was changed in this pull request SachinPawaskarUNO/cora2#384

**Comment by lfkennedy** [comment]
verified in cat.coracore.org
