### ISSUE TITLE
Provenance 2: Should be able to be left blank

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#21]
Unlike the Oklahoma project that has additional "Group" information, the Ploesti (Tidal Wave) project--and possibly other disinterment projects--have only an accession number (e.g., CIL 2017-310), Provenance One (e.g., X-8170) and a Designator (e.g., 601). I have nothing to add to Provenance Two. However, without the Provenance Two field completed, CoRA will not allow me to save. 
![image](https://user-images.githubusercontent.com/33871387/34630594-600dd63a-f232-11e7-8edc-81dd2370738f.png)

**Comment by mei215** [comment]
Following discussion with @SachinPawaskarUNO, we decided both Provenance sections should be able to be left blank.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#300
