### ISSUE TITLE
Removal of "N/A" as a siding option

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#22]
Following discussion with @SachinPawaskarUNO and @fedamann, "N/A" should be removed as an option for siding an element as "unsided" is already an option. 

![image](https://user-images.githubusercontent.com/33871387/34631382-b46dad60-f235-11e7-8788-060b28b0e651.png)

**Comment by SachinPawaskarUNO** [comment]
As per @fedamann N/A are for non diagnostic fragments associated with an accession as opposed to a paired element that is unsided. This will be documented appropriately by @clegarde when she creates the fields and allowable values glossary. 
We are not removing N/A.

**Comment by SachinPawaskarUNO** [comment]
This issue has now been addressed via SachinPawaskarUNO/cora#417
@clegarde can you please verify this one.

**Comment by clegarde** [comment]
@SachinPawaskarUNO , Done, GTG.
