### ISSUE TITLE
Measurement changes not saving in Review tab

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#233]
Changes to measurements are not saving or transferring to Measurement page under details menu for the element.  On review tab, also CoRA is not marking that the change has been saved, reviewed, and accepted.  @SachinPawaskarUNO @clegarde 
![cora review issue 1](https://user-images.githubusercontent.com/35308331/42514940-2da66556-8420-11e8-8ab0-55339b2c7c00.JPG)
 
![cora review issue 2](https://user-images.githubusercontent.com/35308331/42514961-36065c4c-8420-11e8-8510-5e6a4ac22951.JPG)
![cora review issue 3](https://user-images.githubusercontent.com/35308331/42514996-4c390848-8420-11e8-94d3-c7b938b485fe.JPG)

**Comment by rpernst** [comment]
This was not a bug but how the feature was working, an element needs to be reviewed and then the person who inventoried the item must accept the review for the change to happen to the element. This accept button was added with this pull request SachingPawaskarUNO/cora2#431

**Comment by tlvandeest** [comment]
Suggest we have a discussion/walkthrough of the review process in CoRA.  From what I can see in CoRA-CAT there is still not an accept button on the review page for the analyst to accept and apply the changes (if I am understanding Ryan's note above).  @SachinPawaskarUNO @rpernst

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest, This should now be in CAT. Please verify.

**Comment by tlvandeest** [comment]
Unable to verify at this time due to Application Error when searching for elements in CoRA CAT @SachinPawaskarUNO @fedamann

**Comment by SachinPawaskarUNO** [comment]
During the SCRUM today, I have discussed with @tlvandeest a way to get past the search error and search an element using a composite key and from there go to the Review Screen for that element. Hopefully we should be able to make progress on this issue.

**Comment by tlvandeest** [comment]
Tested Review funciton on a femur and both Save for Reviewer and Accept for Analyst reviewer, respectively.  When changes suggested by the Reveiwer were accepted, the values corrected within the element measurement record also.  @emilystreetman @SachinPawaskarUNO
