### ISSUE TITLE
Add Refits and Pair Match to review page

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#235]
Currently, Refits and Pair Matches are not present and cannot be reviewed under the Review page. I suggest they be added as they are an important part of the review. @SachinPawaskarUNO @clegarde 
![cora review add refits and pm](https://user-images.githubusercontent.com/35308331/42515598-c6186590-8421-11e8-90e0-2d57cdc887a9.JPG)

**Comment by rpernst** [comment]
Worked on by pull request SachinPawaskarUNO/cora2#431

**Comment by tlvandeest** [comment]
Confirmed as present in v. 1.0.0 and issued closed
