### ISSUE TITLE
Measurements out of order in Review page

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#236]
The list of measurements are out of order on the Review page for the cranium, humerus, femur, tibia, calcaneus, clavicle, scapula, os coxa, and sacrum. See image below for example. @SachinPawaskarUNO @clegarde 
![cora measurement review numbers](https://user-images.githubusercontent.com/35308331/42516241-38ea86ec-8423-11e8-8bbb-f2de4380c9bb.JPG)

**Comment by emilystreetman** [comment]
This looks OK to me now for all elements listed in the original ticket - @tlvandeest as ticket-writer, please close if this is OK for you, too?

![measurements_hum](https://user-images.githubusercontent.com/34662044/46029381-e4cdad00-c0b8-11e8-9609-b086d34ffa4a.jpg)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest Please verify

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest. Please verify.

**Comment by tlvandeest** [comment]
Verified in CoRA CAT and closed.
