### ISSUE TITLE
Display DNA sample number (with link) rather than "Yes"?

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#237]
@SachinPawaskarUNO, when we get the results of a skeletal element search, can the sample number (if there is one) be displayed in the "DNA Sampled" column, rather than just "Yes"? And could that be a clickable link to the DNA Profile page for that skeletal element? If it hasn't been sampled, it could still say "No" or whatever seems appropriate.  
![screen shot 2018-07-11 at 2 19 28 pm](https://user-images.githubusercontent.com/7350474/42594799-ecef7ee8-8515-11e8-8d29-b91352984b4f.png)

**Comment by nmcelroy** [comment]
This has been addressed in SachinPawaskarUNO/cora2#429

**Comment by fedamann** [comment]
Finished
