### ISSUE TITLE
Incorrect measurement thresholds

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#239]
When entering cranial measurements I received the following error for 2 measurements:

![image](https://user-images.githubusercontent.com/21186879/42775657-8756591a-88fa-11e8-989c-7a54bf96edaf.png)

The min and max thresholds are both very large for these 2 measurements.

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#482

**Comment by emilystreetman** [comment]
Linked to ticket #249 Min and Max values and thresholds

**Comment by skindsc1** [comment]
Verified that these specific measurement thresholds are correct.
