### ISSUE TITLE
Add "Mito Seq #" to results from "DNA sample number" search

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#240]
It would be nice to have "mito sequence number" show (if there is one) in an additional column when searching a DNA sample number. I'm adding mtDNA data and I don't know if it's already in there until I go in to each one. It would save time when doing general data entry to see that in the results when you search, so you'd know if it already has mito sequence info. That would often be the data you're looking for when searching by DNA sample number anyway.
![screen shot 2018-07-28 at 1 53 23 pm](https://user-images.githubusercontent.com/7350474/43359765-08e595c8-926e-11e8-9b07-ace7170aab87.png)

**Comment by nmcelroy** [comment]
This is addressed in v1.0.0

**Comment by clegarde** [comment]
GTG. I did get the following error when clicking on the sample number (2388A). Using Safari.
![screen shot 2018-10-17 at 9 47 16 am](https://user-images.githubusercontent.com/7350474/47094893-b6dc1400-d1f1-11e8-8289-8821c71d9f36.png)

**Comment by nmcelroy** [comment]
@clegarde was this error only when clicking on specifically 2388A or did it happen multiple times on different DNA sample numbers as well?

**Comment by nmcelroy** [comment]
Fixed issue in SachinPawaskarUNO/cora2#528

**Comment by clegarde** [comment]
GTG
I'm very happy you can click the mito sequence number from this search and get the list of elements in the mito sequence, too! Awesome!
