### ISSUE TITLE
Capturing tooth number

### ISSUE THREAD

**Issue by veronicak7** [spawaskar-cora/cora-docs#246]
When entering a skeletal element, there is no way to capture the number of the tooth that was sampled for DNA. Often the sampled tooth would be associated with a skeletal element (i.e. mandible, maxilla, or cranium), but could also be a non-articulated tooth. The odontologists specify the tooth number when sampling and we don't want to lose that information when entering into CoRA.

**Comment by fedamann** [comment]
@veronicak7 @SachinPawaskarUNO add 32 new skeletal specimens to bone type list that covers the permanent teeth 1 through 32 (e.g., tooth #1, tooth #2, etc).  These should be associated to two new bone groups: Maxillary teeth for 1-16 and Mandibular teeth 17-32.  This should suffice for a mvp for dental, and the build out the dental module can be moved to the backlog.

**Comment by fedamann** [comment]
@SachinPawaskarUNO @rpernst  
1. Create new skeletal elements for Tooth #1 through Tooth #32 as 32 unique records
2. In the SKULL group, delete "Tooth" and include all newly created numbered teeth 
3. Add new group: "Maxillae" and include Tooth #1 through Tooth #16
4. Add new group: "Mandible" and include Tooth #17 through Tooth #32

**Comment by clegarde** [comment]
There should also be an "Unidentified tooth" or something similar for those that we cannot assign a number to. Not sure if you'd want additional ones or not (ex: Unidentified molar, Unidentified incisor, Unidentified maxillary molar, etc.). @fedamann @SachinPawaskarUNO

**Comment by fedamann** [comment]
@clegarde Correct. and why we decided to leave "Tooth" as a skeletal element record for the most basic and general description of an unidentified tooth (we are only removing "Tooth" from the group inventory option, not the complete list of skeletal elements)  The more complete data capture will come later when we build out the dental module.

**Comment by emilystreetman** [comment]
@veronicak7 Hi Veronica - Hawaii CHR folks may have already found you to let you know about this, but in the 9OCT18 scrum, it was requested that you please verify and close this ticket. Thank you!

**Comment by veronicak7** [comment]
Hi Emily,

I did receive that information from Caryn. Thanks.

Best,
Veronica

Veronica A. Keyes, PhD, RPA
DPAA Laboratory
veronica.a.keyes2.civ@mail.mil
(808) 448-4500 ext. 3769

-----Original Message-----

**Comment by emilystreetman** [comment]
Verified - closing ticket.
