### ISSUE TITLE
Tooth record associations

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#247]
@SachinPawaskarUNO @rpernst 
1. Associate maxillary teeth (1-16) to the "Maxillae" skeletal element
2. Associate mandibular teeth (17-32) to the "Mandible" skeletal element

**Comment by emilystreetman** [comment]
Being addressed in #254 Bone groupings - verification
Siding issues occur with this association design where mandible is a middle element, maxillae may be either left or right, and teeth are only one of left or right.

**Comment by emilystreetman** [comment]
I believe this is now an issue to double check whether articulation is possible between:

- cranium and tooth 1 - tooth 16
- maxilla and tooth 1 - tooth 16
- mandible and tooth 17 - tooth 32

Currently: From Tooth 30, I can choose any cranium or mandible to articulate to. This should only be mandibles. From Mandible, I cannot choose any teeth to articulate to. Teeth 17-32 should appear.

If someone (@SachinPawaskarUNO or @rpernst) will post the articulations xlsx to this ticket in the dev team's preferred format, I will correct these elements.

**Comment by emilystreetman** [comment]
I have made a new ticket #269 for the current issue with tooth articulations. Closing this one since the original request is verified as active in CAT.
