### ISSUE TITLE
DNA Module: redesign parent-child relationship

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#251]
Redesign the parent child relationship among mitochondrial results and additional testing options, so every test performed is a child of the specimen, not the mito sequence result.  in other words, flatten the relationship to one parent (specimen) and multiple children (tests performed and associated results). @SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy This is related to the conversation we had last Thursday

**Comment by SachinPawaskarUNO** [comment]
This has been addressed with the v1.1.1 release
