### ISSUE TITLE
Entering Accession and Provenance in CoRA-cat

### ISSUE THREAD

**Issue by ragreid** [spawaskar-cora/cora-docs#256]
As of 2pm HST, cannot enter accession and provenance when entering a new skeletal element or bone group when testing the new environment in CoRA-cat. The auto-population option is also not working for entering accession or provenance.

**Comment by SachinPawaskarUNO** [comment]
@ragreid Can you tell me which project in Cora-cat you were using when you had this issue? Can you also please add a screenshot to this issue?

**Comment by ragreid** [comment]
It was the demo I was testing

![image](https://user-images.githubusercontent.com/39973898/45969030-41a06900-bfce-11e8-808f-c0619b9bdf74.png)

**Comment by fedamann** [comment]
Check with Rebecca. I believe we fixed this in the manager's meeting. It
has to do with Project Lead's decision for control of data entry.  If the
PL wants users to add in new info, without pulling from a drop down list
then we need to enable this function.

**Comment by ragreid** [comment]
Tested and verified
