### ISSUE TITLE
Inventory - Elements List not alphabetized

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#261]
The dropdown for element selection on a single-bone entry page is not in alphabetical order.

![elements_list](https://user-images.githubusercontent.com/34662044/46096855-e0bb9100-c185-11e8-88b8-f5dffc6f9619.jpg)

**Comment by emilystreetman** [comment]
The update currently shows the list reverse-alphabetized with zygomatic first. Please adjust to A-to-Z instead of Z-to-A

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#498

**Comment by emilystreetman** [comment]
Verified as fixed - closing ticket.
