### ISSUE TITLE
New Bone Group: Accession Does Not Autofill

### ISSUE THREAD

**Issue by btrnew** [spawaskar-cora/cora-docs#262]
Hi :) 

I went into my project settings and had CoRA autofill an accession number for me. When inputting a single skeletal element the autofill function works perfectly. However, the feature does not autofill an accession number when inputting skeletal elements as a bone group. While the Bone Group section is under construction this might be a good thing to consider tweaking. 

Thank you! Have a good day!

**Comment by emilystreetman** [comment]
Will you please share a screenshot or two documenting this problem?

**Comment by btrnew** [comment]
Hi! Follow up to this ticket now that Bone Group is ready to be tested.

The screenshot below indicates that I have my settings set to autofill an accession number. 
![saved accession number](https://user-images.githubusercontent.com/43450732/46378655-0dfdb880-c638-11e8-980f-f9d28e0e3f7d.jpg)

The photo below shows that this function works for entering a single skeletal element
<img width="960" alt="skeletal element autofill" src="https://user-images.githubusercontent.com/43450732/46378733-4bfadc80-c638-11e8-94ab-eaf2cf90f272.png">

However, here you can see that when on the add Bone Group page the accession number does not autofill. 
<img width="960" alt="bone group no autofill" src="https://user-images.githubusercontent.com/43450732/46378797-7a78b780-c638-11e8-8dd0-2b559a7f71be.png">

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#504

**Comment by SachinPawaskarUNO** [comment]
@btrnew, Can you please take a look at this and close if verified as fixed

**Comment by btrnew** [comment]
Issue is fixed. Thank you!
