### ISSUE TITLE
Hover function over menu

### ISSUE THREAD

**Issue by JKJuarez** [spawaskar-cora/cora-docs#263]
Would it be possible to include a hover function over menu items?  I know we talked about the design being set up to save space but it might be helpful to have a quick reference by hovering over the icons.

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#500

**Comment by JKJuarez** [comment]
Was asked during last CoRA scrum to give a couple of weeks before closing this. Closing now.
