### ISSUE TITLE
Bio-material option

### ISSUE THREAD

**Issue by JKJuarez** [spawaskar-cora/cora-docs#264]
Would it be possible to add into the "bone" option something like "mummified bio-material"?  Cabanatuan has a mummified brain and I imagine other projects have come across other (at least partially) mummified biomaterial.  Without a place to write-in the specific item, a general term might be beneficial.

Thank you,
JKJ

**Comment by SachinPawaskarUNO** [comment]
Based on SCRUM discussion today, it has been decided to add a new SE called "Tissue".

**Comment by JKJuarez** [comment]
Decision to close out ticket following implementation and discussion at CoRA scrum on 9 Oct 18
