### ISSUE TITLE
References Section in CoRA Docs

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#265]
It would be nice to have a list of reference (citations) in the CoRA Docs area. When the measurements page says "Buikstra and Ubelaker 1994" or "Langley et al 2015" a full citation would be helpful to users.

For example:

Buikstra, J. E. and D. H. Ubelaker (editors)
	1994		Standards for Data Collection from Human Skeletal Remains.  Arkansas Archeological Survey Research Series No. 44, Fayetteville, AR.

Byrd, J. E. and B. J. Adams
	2003		Osteometric sorting of commingled human remains.  Journal of Forensic Sciences 48:717–724.

**Comment by SachinPawaskarUNO** [comment]
@fedamann and @emilystreetman I have added a reference page under the about menu. Please encourage DPAA Anthropologists to add appropriate references used within this page for CoRA.

@emilystreetman Please verify and close out this ticket.

**Comment by clegarde** [comment]
These should just be under the methods page. Buikstra and Ubelaker are under there, and I thought the measurements references were also, so this might be an oversight on my part since we had a discussion on how to properly reference Byrd and Adams. These could either go under the "Other" section or an additional one could be added labeled "Measurements" but I think all of our references should be listed on that one page rather than scattered in multiple places.

**Comment by emilystreetman** [comment]
Wow yes, thanks @clegarde - I totally forgot that existed. I made a branch called 'add-references' and tacked the additional references from the measurements page to the methods.md - but not the full citations, because I don't know all of them. 

I think we should change the intro paragraph of measurements.md to include a link to that section of methods.md . Currently, that intro paragraph over-simplifies what is really on that page.

@SachinPawaskarUNO - I was wrong about where this info needed to go, will you please delete the "References" page since it already exists elsewhere.

**Comment by emilystreetman** [comment]
In scrum 9OCT18, @fedamann recommended having references only in one place, the Methods section of the help guide, which already exists. @SachinPawaskarUNO leaving ticket open for now.

**Comment by clegarde** [comment]
I added some info, including adding Byrd and Adams 2015 for additional measurements not in the earlier articles (and these reference B&A 2015 in the measurement guide), and gave these a once over. Created a pull request @SachinPawaskarUNO

**Comment by emilystreetman** [comment]
Thank you to @clegarde for making a pull request on this. Verified as updated.
