### ISSUE TITLE
"Refit" Should be Added as an Associations Option

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#27]
In addition to the "Pair match" and "Articulation" options provided for Associations, "Refit" should be added as a third option to associate portions of fragmented elements scattered throughout multiple accessions that can be reconstructed. @SachinPawaskarUNO  @fedamann 

![image](https://user-images.githubusercontent.com/33871387/34788695-0171116e-f601-11e7-894a-db1dd9349610.png)

**Comment by SachinPawaskarUNO** [comment]
Need to discuss with @mei215 and @fedamann about how to narrow down the search space for refit selection without having to pull/query all skeletal elements in the project.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#378 and SachinPawaskarUNO/cora#379
