### ISSUE TITLE
More info or link with notifications

### ISSUE THREAD

**Issue by lfkennedy** [spawaskar-cora/cora-docs#272]
After creating a bone group, the notification could be more specific - could it include the accession # at least?

![image](https://user-images.githubusercontent.com/35273714/46768960-c1595380-ccaf-11e8-9c5f-1ceb9bc118e0.png)

After creating multiple bone groups, having the accession number written out or a link would enhance our ability to quickly access those specimen logs in order to edit them and add data.

When the "view" button is clicked, user is navigated to the same page.

possibly similar to #267 ?

**Comment by rpernst** [comment]
Yes, the notification was fixed with this sachinpawaskaruno/cora2#511.
The view link will now send you to a more detailed view of the notification including how long ago it was created, the accession number, provenance1, provenance2, and starting designator number.

**Comment by lfkennedy** [comment]
OK!
