### ISSUE TITLE
Remove Manual and Pedal Digit 1 Intermediate Phalanges

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#274]
@SachinPawaskarUNO, "intermediate manual phalanx 1" and "intermediate pedal phalanx 1" should be deleted as element options because they do not exist in the skeleton

 ![capture](https://user-images.githubusercontent.com/33871387/47307104-cbeee380-d5f3-11e8-9efa-5c345cd8c4e3.JPG)

**Comment by mei215** [comment]
Checked this closed ticket and it looks like these two elements (intermediate pedal phalanx 1 and intermediate manual phalanx 1) are still present.

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy, Please take a look, these are still showing up in CAT.

**Comment by SachinPawaskarUNO** [comment]
@fedamann, @nmcelroy @rpernst I have addressed this issue. This issue has to do with original skeletal_bones dataset. I have now addressed this issue in both CAT and current PROD.
@mei215, Please verify this issue.

**Comment by mei215** [comment]
This issue has been fixed.
