### ISSUE TITLE
Some measurements not represented in help images

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#281]
Following discussion on the thread of ticket #259, the following measurements are not currently represented in the help images. Emily and Nandar are working on creating images where needed, and labeling existing images where possible to add these measurements to the help guide.

Cla_04 | Sagittal (Anterior-Posterior)   Diameter at Midshaft
Cla_05 | Vertical (Superior-Inferior) Diameter at Midshaft
Cla_06 | Maximum Width at the Distal End
Cla_07 | Breadth at the Inflexion Point at the Distal End
Cla_08 | Maximum Thickness at the Inflexion Point at the Distal End
Cla_09 | Maximum Anterior-Posterior Width at the Proximal End
Cra_11 | Nasion-Prosthion Height (n-pr)
Fem_06 | Medial-Lateral (Sagittal) Subtrochanteric Diameter
Fem_07 | Anterior-Posterior (Sagittal) Midshaft Diameter
Fem_08 | Medial-Lateral (Transverse) Midshaft Diameter
Fem_18 | Upper Breadth of Femur
Fem_19 | Lateral Condyle Height
Hum_06 | Total Breadth of the Capitulum-Trochlea
Hum_07 | Anterior-Posterior Breadth of the Head
Man_07 | Maximum Ramus Breadth
OsC_03 | Pubis Length
OsC_04 | Ischium Length
OsC_14 | Thickness of the Ilium at the Sciatic Notch
OsC_15 | Maximum Breadth of the Ischium
OsC_16 | Minimum Breadth of the Pubis
Rad_05 | Anterior-Posterior (Sagittal) Diameter at Midshaft
Rad_06 | Medial-Lateral (Transverse) Diameter at Midshaft
Rad_10 | Breadth of the Distal Epiphysis
Tib_06 | Circumference at the Nutrient Foramen
Tib_12 | Maximum Anterior-Posterior Distance of the Distal Articular   Surface
Tib_13 | Biarticular Breadth
Tib_14 | Medial Condyle Articular Width
Tib_15 | Medial Condyle Articular Length
Tib_16 | Lateral Condyle Articular Length
Uln_04 | Anterior-Posterior (Dorso-Volar) Diameter
Uln_05 | Medial-Lateral (Transverse) Diameter
Uln_11 | Breadth of the Semilunar Notch

**Comment by emilystreetman** [comment]
The following elements/measurements still require drawings and/or digital updates:
- Cervical vertebrae 1 and 2
- Hands
- Feet
- Patella
- Cra_11 | Nasion-Prosthion Height (n-pr)
- Hum_06 | Total Breadth of the Capitulum-Trochlea
- Hum_07 | Anterior-Posterior Breadth of the Head
- Tib_12 | Maximum Anterior-Posterior Distance of the Distal Articular Surface
- Tib_13 | Biarticular Breadth
- Tib_14 | Medial Condyle Articular Width
- Tib_15 | Medial Condyle Articular Length
- Tib_16 | Lateral Condyle Articular Length
- Uln_11 | Breadth of the Semilunar Notch

Pull request created for updated images showing:
- Cla_04 | Sagittal (Anterior-Posterior) Diameter at Midshaft
- Cla_05 | Vertical (Superior-Inferior) Diameter at Midshaft
- Cla_06 | Maximum Width at the Distal End
- Cla_07 | Breadth at the Inflexion Point at the Distal End
- Cla_08 | Maximum Thickness at the Inflexion Point at the Distal End
- Cla_09 | Maximum Anterior-Posterior Width at the Proximal End
- Fem_06 | Medial-Lateral (Sagittal) Subtrochanteric Diameter
- Fem_07 | Anterior-Posterior (Sagittal) Midshaft Diameter
- Fem_08 | Medial-Lateral (Transverse) Midshaft Diameter
- Fem_18 | Upper Breadth of Femur
- Fem_19 | Lateral Condyle Height
- Man_07 | Maximum Ramus Breadth
- OsC_03 | Pubis Length
- OsC_04 | Ischium Length
- OsC_14 | Thickness of the Ilium at the Sciatic Notch
- OsC_15 | Maximum Breadth of the Ischium
- Rad_05 | Anterior-Posterior (Sagittal) Diameter at Midshaft
- Rad_06 | Medial-Lateral (Transverse) Diameter at Midshaft
- Rad_10 | Breadth of the Distal Epiphysis
- Tib_06 | Circumference at the Nutrient Foramen
- Uln_04 | Anterior-Posterior (Dorso-Volar) Diameter
- Uln_05 | Medial-Lateral (Transverse) Diameter

**Comment by emilystreetman** [comment]
All measurements images updated and pull request created. waiting to verify in Help documentation and on measurements pages in CoRA

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman @nyukyi Please verify

**Comment by emilystreetman** [comment]
Looks good!
