### ISSUE TITLE
Remove age methods

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#284]
Following work on McKern and Stewart age methods for ticket #250.

Please remove these McKern and Stewart age methods from the manubrium and the xiphoid, respectively:
id | method_id | feature | display_name | element_name | display_values
118 | 74 | Manubriosternal Joint | Manubriosternal Joint | Manubrium | {"Unfused":"Unfused",   "Fused":"Fused"}
156 | 126 | Xiphoid-sternal fusion | Xiphoid-sternal fusion | Xiphoid process | {"Unfused":"Unfused",   "Fused":"Fused"}

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed, Please verify.

**Comment by emilystreetman** [comment]
Looks good!
