### ISSUE TITLE
CoRA measurement images not using most up-to-date images in GitHub

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#285]
Related to ticket #279 Broken links to Help Guide and #281 Some measurements not represented in Help Guide

Links on the right side help guide now link to correct measurements section, but while the images presented in the Help Guide are the most up-to-date files, the measurements page in CoRA is not similarly updated.

Example snip here where main page image is not updated. This issue is present on at least ulna, radius, femur, and os coxa measurement pages.

![image](https://user-images.githubusercontent.com/34662044/48568758-ab9a0800-e8c5-11e8-8e69-26722624f786.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue have been fixed. Please verify.
@emilystreetman and @fedamann Are there any more issues that still need to be updated?

**Comment by emilystreetman** [comment]
@SachinPawaskarUNO - this ticket is verified. We will need to go through the same steps when @nyukyi and I finish ticket #281 because that will be the second (final) batch of updated measurements images.
