### ISSUE TITLE
Ability to create a list of elements that have any Individual Number

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#286]
I cannot call up a list of elements that are associated with an Individual Number.  For example, if I want to get a list of left femora that have an I-# associated with them.

**Comment by SachinPawaskarUNO** [comment]
@skindsc1, Please verify.

**Comment by skindsc1** [comment]
Verified and closed

**Comment by emilystreetman** [comment]
Can someone please show me how to do this? I see the column in advanced search results, but can't sort or export by I-# presence?

**Comment by skindsc1** [comment]
I talked with Emily and we are in agreement that this ticket has been addressed.
