### ISSUE TITLE
Zone Report Bug

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#290]
There is a bug when selecting zones.  This is an example of what I encountered:  I looked up zones for the sacrum, and then selected tibia right after that.  When I clicked on "zones" after selecting tibia, the zones for the sacrum (or other previously selected element) showed up. 
![cora_zones_bug](https://user-images.githubusercontent.com/34749060/48721838-4bb6a080-ebe8-11e8-9551-2555e47ae7fe.PNG)

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Here is what I'm seeing in CAT (see screenshot below). Are you going to the right environment. Can you please reverify.

![image](https://user-images.githubusercontent.com/19599773/48730598-86c4ce00-ec00-11e8-823b-6a31e4c6469e.png)

**Comment by nyukyi** [comment]
@SachinPawaskarUNO I was/am in CAT! I just checked it again, and it's working now... Did you secretly fix it??
