### ISSUE TITLE
Sacrum zone report - zone list out of order

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#294]
Under the zone list for the sacrum in the zones report section, the list is out of order

![cora_sacrum_zone](https://user-images.githubusercontent.com/34749060/48869099-93345c80-eda1-11e8-9fcb-2847eca8fbca.PNG)

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Please verify

**Comment by nyukyi** [comment]
Looks good, thank you!
