### ISSUE TITLE
Tying images with appropriate elements:  hands, feet, and vertebrae

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#295]
![hand_500](https://user-images.githubusercontent.com/34749060/48869710-cbd53580-eda3-11e8-9f86-e3a638c46846.png)

Hand elements to be tied with this above image:
- Metacarpal 1
- Metacarpal 2
- Metacarpal 3
- Metacarpal 4
- Metacarpal 5
- Hamate
- Capitate
- Trapezoid
- Trapezium
- Pisiform
- Triquetral
- Lunate
- Scaphoid

---

![foot_500](https://user-images.githubusercontent.com/34749060/48869890-6897d300-eda4-11e8-8fef-765797c96a81.png)

Foot elements to be tied with this above image:
- Metatarsal 1
- Metatarsal 2
- Metatarsal 3
- Metatarsal 4
- Metatarsal 5
- Cuboid
- Navicular
- First (Medial) cuneiform
- Second (Intermediate) cuneiform
- Third (Lateral) cuneiform

---

![vertebrae_200](https://user-images.githubusercontent.com/34749060/48870146-4783b200-eda5-11e8-968e-1b7ab026adcf.png)

Vertebrae to be tied with this above image:
- Cervical vertebra 1
- Cervical vertebra 2

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Please verify

**Comment by nyukyi** [comment]
@SachinPawaskarUNO Verified, good to go!
