### ISSUE TITLE
Phalanx Count Function

### ISSUE THREAD

**Issue by btrnew** [spawaskar-cora/cora-docs#296]
I thought I recalled someone mentioning that there would be a count function that would allow you to add X amount of unseriated phalanges, but there doesn't appear to be a count option or phalanges skeletal group option. I don't see a ticket for this, so I thought I would make the suggestion. 

An example of the necessity of this feature:
I have an accession with over 100 unseriated proximal phalanges that are currently not associated with any other skeletal elements or individuals. Not having to input each of those phalanges individually would be an immense time saver and reduce user error (misnumbering, skipping a number, duplicating, etc.)

<img width="861" alt="phalanx count" src="https://user-images.githubusercontent.com/43450732/48873502-485f1880-ed92-11e8-9782-022bc97b4300.PNG">

**Comment by SachinPawaskarUNO** [comment]
@btrnew, @fedamann, Currently only the list of Skeletal_Bones (SB) flagged as countable will have count and mass fields available for inventorying purposes. We currently have **Unidentified phalanx** that could be use for this purpose. I would like the groups in Hawaii & Omaha to work together on coming up with a list of such bones, if what we have currently is not sufficient. We currently have the following bones that have these capabilities

1. Unidentified cranium
2. Unidentified fragments
3. Unidentified rib fragments
4. Unidentified long bone
5. Unidentified metacarpal/tarsal
6. Unidentified phalanx
7. Unidentified vertebra

@btrnew Please note that the count and mass fields become available only after you Save/Create the record.

**Comment by SachinPawaskarUNO** [comment]
@btrnew Please verify

**Comment by emilystreetman** [comment]
I am verifying that the elements listed by @SachinPawaskarUNO on 22NOV18 have count function enabled.

Related unseriated phalanges counts were fixed in ticket #182
