### ISSUE TITLE
Drop-down of element designators should show side and element

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#299]
In a comment for ticket #151 , @clegarde made a comment that I think should be its own idea. It would be easier to choose articulating elements (or other associations) if the side and bone were shown in the drop-down selection list in a similar way to how it's shown in this screencap:

![image](https://user-images.githubusercontent.com/34662044/49030525-2b995b00-f16d-11e8-85d3-fbf1e23504db.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde @emilystreetman, Please verify.

**Comment by clegarde** [comment]
This is great! GTG
