### ISSUE TITLE
Error when trying to update DNA sample

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#302]
When attempting to update/edit DNA, I'm getting the following error:
![screen shot 2018-12-05 at 9 26 22 pm](https://user-images.githubusercontent.com/7350474/49557215-ee536c80-f8d4-11e8-83d9-f5058d230196.png)

I got this after adding a new sample, then choosing "Edit" to add other data (date, results, mito seq number, etc.).

**Comment by clegarde** [comment]
Sorry @SachinPawaskarUNO , I should have stated, this is happening for multiple skeletal elements, not just 1994B. I tested a handful of different samples/skeletal elements.

**Comment by clegarde** [comment]
This isn’t because I’m trying to add a duplicate sample number. I’m trying to edit a sample that already exists in CoRA and then I get this message. As of now, it’s not letting me edit any DNA samples already in CoRA, so I can’t add mito results to an existing sample.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, Ohh, Let me restate for our understanding, you are editing an existing DNA record and when saving you are getting that error. If that is the case, then it is a bug. It should only do what I stated above when creating a new DNA record.
@nmcelroy Please address this issue. I'm guessing that you have added this check to both store and update methods. This should only be in store when you are creating a new DNA record.

**Comment by clegarde** [comment]
Correct. Error received when editing existing record.

**Comment by SachinPawaskarUNO** [comment]
@clegarde I have uploaded a fix for this. Can you please verify?

**Comment by clegarde** [comment]
GTG
