### ISSUE TITLE
Error when attempting to switch projects

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#303]
Got the following error when switching in cat.coracore.org from Demo project to USS OK project. When I clicked Back on my browser, it had successfully switched projects, despite this error appearing.

![image](https://user-images.githubusercontent.com/34662044/49598445-470e1e00-f944-11e8-96e9-c7db191c0fb3.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please verify

**Comment by emilystreetman** [comment]
This worked today. Closing.
