### ISSUE TITLE
Link to Individual Number Report does return results

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#305]
After searching by skeletal element (Ex: humerus), if you click on the Individual Number link:
![a1 humerus search](https://user-images.githubusercontent.com/7350474/49767802-9a170680-fc9f-11e8-99ff-2c32e8ec9e21.png)
You don't return results, just directed to the Individual Report page with no results:
![a2 individual number report page](https://user-images.githubusercontent.com/7350474/49767815-adc26d00-fc9f-11e8-90eb-68ea77124b8b.png)
This is in contrast to clicking on the sequence number where you're directed to the mtDNA advanced report with results:
![a3 mito sequence report](https://user-images.githubusercontent.com/7350474/49767862-d3e80d00-fc9f-11e8-8033-6e501f8514d0.png)

**Comment by nmcelroy** [comment]
Addressed in SachinPawaskarUNO/cora2#600
