### ISSUE TITLE
Accession search does not return results

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#306]
Skeletal elements > Accession > UNO-2016-212 (I tested in CoRA Demo since I thought USS Oklahoma was too large to try):
![b1 se search_accession search](https://user-images.githubusercontent.com/7350474/49768073-9e8fef00-fca0-11e8-8570-4d60002c3765.png)
Returned the following:
![b2 se search_accession search_results](https://user-images.githubusercontent.com/7350474/49768095-b9626380-fca0-11e8-8de7-6e048a7daefd.png)
DNA > Accession > UNO-2016-212 returned the following:
![b3 dna search_accession_results](https://user-images.githubusercontent.com/7350474/49768112-ca12d980-fca0-11e8-9724-405a49f3e244.png)

If this is an issue with the results being too large, could there be a different message?

**Comment by SachinPawaskarUNO** [comment]
@clegarde Do you have access to any other DPAA projects other than the USS Oklahoma? If you do, please check this out, if not can you please ask someone on the DPAA team such as Tarawa or Ploesti to verify this issue.

**Comment by clegarde** [comment]
I only have USS Oklahoma. Can @CTegtmeyer or @mei215 check this, please?

**Comment by mei215** [comment]
I ran both searches with the Ploesti data in Production and did not have the same problem. Skeletal elements and/or DNA results were produced.

**Comment by CTegtmeyer** [comment]
I also ran searches with the Tarawa data in Production and did not have the same problem. Results were returned when accession or DNA was searched.

**Comment by clegarde** [comment]
@SachinPawaskarUNO, I just tried this again and it worked for me too. I tried in USS Oklahoma as well, and it worked too. Giving me the first 500 results (as it indicates). I'm not sure if something changed with other updates or not, but this appears to be GTG.
