### ISSUE TITLE
Skeletal Elements > External ID search not returning results

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#307]
Skeletal Elements > External ID > 2015H0996 entered as follows:
![se search_external id](https://user-images.githubusercontent.com/7350474/49768227-4b6a6c00-fca1-11e8-8cde-7144ca87b867.png)

Returns the following:
![se search_external id_results](https://user-images.githubusercontent.com/7350474/49768238-51f8e380-fca1-11e8-90e9-8e75a3a1149c.png)

***This does work under DNA > External ID, so maybe we should just remove it from the list of search by options under Skeletal Elements?

**Comment by SachinPawaskarUNO** [comment]
@clegarde I agree with you we should just remove it from the list of search by options under Skeletal Elements as it is rightly under DNA. This is probably a fallout of the old search in CoRA v0.7.0. I have made this change. Please verify.

**Comment by clegarde** [comment]
GTG
