### ISSUE TITLE
Measurements Report Export has too much data in Column A

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#308]
The exports for a measurement report returns the entire help text for the measurement in Column A, rather than just the measurement name (ex: Cra_01). See attached.
[CoRA Measurement Report_CIL2003-116-I-136.pdf](https://github.com/spawaskar-cora/cora-docs/files/2665357/CoRA.Measurement.Report_CIL2003-116-I-136.pdf)
[CoRA Measurement Report_CIL2003-116-I-136.xlsx](https://github.com/spawaskar-cora/cora-docs/files/2665358/CoRA.Measurement.Report_CIL2003-116-I-136.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
