### ISSUE TITLE
No export option for Measurement Report by Bone

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#309]
When generating a Measurement Report by Individual Number (Ex: CIL 2003-116-I-136) there is the option to export:
![c2 measurement report by individual_export option available](https://user-images.githubusercontent.com/7350474/49768678-bb2d2680-fca2-11e8-983b-51cba1821a6d.png)

When generating a Measurement Report by Bone (Ex: Sacrum) there is not an option to export and the full list is shown, rather than only 25 rows:
![c1 measurement report by bone_no export option](https://user-images.githubusercontent.com/7350474/49768714-e44db700-fca2-11e8-808a-06572a12d6ab.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
