### ISSUE TITLE
Zones out of order in drop downs for Trauma and Pathology Reports

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#311]
Zones out of order in drop downs for Trauma and Pathology Advanced Reports: 
![add trauma_zones out of order_mandible](https://user-images.githubusercontent.com/7350474/49769540-33491b80-fca6-11e8-84e2-c9b157b51cf0.png)

Only something to address if we want everything to be in numerical or alphabetical order.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
