### ISSUE TITLE
Provenance 1 and 2 out of order in drop downs for all Advanced Reports

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#312]
Only something to address if we want everything to be in numerical or alphabetical order.

![mtdna advanced report_provenance 1 out of order](https://user-images.githubusercontent.com/7350474/49769632-88852d00-fca6-11e8-9385-1106f44dc64a.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
