### ISSUE TITLE
Skeletal Element - return to "edit" vs "view" page from Methods

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#313]
When adding/editing methods, if you click on return to SE page icon on the "methods" bar:
![methods_se home](https://user-images.githubusercontent.com/7350474/49819167-50c7c500-fd3a-11e8-9786-359d51a37aef.png)

You return in EDIT mode:
![screen shot 2018-12-11 at 11 41 06 am](https://user-images.githubusercontent.com/7350474/49819190-64732b80-fd3a-11e8-9c46-56c0629b465e.png)

If you choose the icon on the "element highlights" bar:
![screen shot 2018-12-11 at 11 40 39 am](https://user-images.githubusercontent.com/7350474/49819186-5d4c1d80-fd3a-11e8-8ce9-3a66465df826.png)

You return in VIEW mode:
![screen shot 2018-12-11 at 11 41 33 am](https://user-images.githubusercontent.com/7350474/49819203-6b01a300-fd3a-11e8-829f-36cdafdd9188.png)

***Should these both be returning in VIEW mode? This example was a humerus for age, but I tested this for all bio profile methods and multiple skeletal elements and they all operated as noted above.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
