### ISSUE TITLE
"No skeletal articulations available for this bone" banner despite articulations selected

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#314]
Articulations shows “No articulations have been associated with this skeletal element” notification, despite there being a skeletal element associated with the element.

![capture](https://user-images.githubusercontent.com/36896992/49822995-b8721600-fd22-11e8-95a9-8d7089e0d922.JPG)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, Please verify

**Comment by CTegtmeyer** [comment]
verified. issue has been resolved
