### ISSUE TITLE
Narrow mito sequence in search based on accession and provenance

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#315]
On the Advance DNA report function, when it asks you to choose a mito sequence, mito sequences aren’t narrowed by accession or provenance 1 and/or 2, but all possible mito sequences are listed (310?). Would it be possible to have this be limited to what mito sequences are available per accession and the very least, and provenance at the very most?

**Comment by clegarde** [comment]
I was wondering if we could search just by provenance (1 or 2) under the mtDNA advanced report, and not have to choose a mito sequence? This would then generate all mito sequences for a particular provenance 1 or provenance 2. I think this would be a useful feature. Somewhat relates to @CTegtmeyer issue here. A different approach to getting the same type of data?

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @CTegtmeyer please verify. We have implemented what @clegarde suggested above, as it seems to give the anthropologists the most flexibility.

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO @clegarde Verified. Looks good. I agree, this gives much more flexibility and it helps the search for mito sequences.
