### ISSUE TITLE
Narrow down provenance 1 and 2 baased on accession choice

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#316]
Search functions: choosing an accession doesn’t limit your choices of provenances 1 or 2. Would it be possible to narrow down the choices of provenances based on accession? (It is hard to remember what provenance goes with what accession especially when you have a lot of both).

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, Please verify

**Comment by CTegtmeyer** [comment]
verified! Awesome!
