### ISSUE TITLE
Zone for lunate opens at upper limb

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#319]
When clicking on the zone for lunate, it opens the CoRA doc sidebar for upper limb instead of hands and feet. Should open the sidebar at: https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#hands-and-feet instead.

**Comment by clegarde** [comment]
I was just noting this in another issue. It looks like the help for zones is linking to the regional header ("Thorax and Shoulder" for the clavicle), rather than the element ("Clavicle"), for all skeletal elements.

**Comment by clegarde** [comment]
@SachinPawaskarUNO @fedamann If a discussion led to the decision to link to regional headers, that seems just fine. I just wasn't sure, since the measurement help linked right to the element. Either way seems reasonable!

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @fedamann, I think if we have the URL anchors in the cora-docs, then let's use it. Since we have the control we might as well make it easier for the Anthropologist by taking them to the exact bone. I would prefer the users not have to scroll to find the bone they are working with. Thoughts???

**Comment by clegarde** [comment]
Agreed. I can work on this if @fedamann agrees.

**Comment by CTegtmeyer** [comment]
verified. I will leave this thread open for now, given the current conversation

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @fedamann, Can you two please connect and see if we can have work done on this? We are talking about first creating anchors in cora-docs to specific elements ("Clavicle")instead of regional header ("Thorax and Shoulder" for the clavicle). Then provide these new anchor URL links to me along with the bone they map to.

**Comment by clegarde** [comment]
Sent doc to @SachinPawaskarUNO. 

We are missing the following in the help docs (so no image in CoRA, but the zones are listed):
-Malleus
-Stapes
-Incus
-Hyoid

@emilystreetman, can you work on this? I just sent you an email directly, so we can confer there as necessary.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
I checked through every bone with zones TRUE. The following do not have the correct link yet:
-Clavicle -> https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#clavicle 
-Lumbar vertebra 1/2 -> https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#thoracic-and-lumbar-vertebrae
-Lumbar vertebra 2/3 -> https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#thoracic-and-lumbar-vertebrae
-Lumbar vertebra 3/4 -> https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#thoracic-and-lumbar-vertebrae
-Lumbar vertebra 4/5 -> https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#thoracic-and-lumbar-vertebrae

I'm attaching the spreadsheet I previously sent to @SachinPawaskarUNO with a sheet to show the following: verified, cannot verify (that bone is not in the USS Oklahoma project), not linking properly (listed above), and bones that are linking but do not have an image in CoRA. I will open a separate ticket for the last issue.
[Zone Links.xlsx](https://github.com/spawaskar-cora/cora-docs/files/2700055/Zone.Links.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify. The Clavicle, Lumbar vertebra 1/2, 2/3, 3/4, 4/5 zone help_url have been updated.

**Comment by clegarde** [comment]
GTG. Closing ticket because new issues were opened for other items mentioned - for easier visibility and tracking.
