### ISSUE TITLE
Several SE Zone pages only have a "placeholder" rather than image

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#320]
Several skeletal elements have a placeholder rather than an image for the zone page:
Accessory rib
Calcaneus
Clavicle
Coccyx
Distal pedal phalanx 1
Hamate
Humerus
Lumbar vertebra 1/2
Lumbar vertebra 5
Metacarpal 2
Metacarpal 3
Metacarpal 5
Metatarsal 3
Metatarsal 4
Os coxa
Proximal manual phalanx 1
Radius
Scapula
Thoracic vertebra 10/11
Thoracic vertebra 12
Tibia
Trapezoid
Triquetral
Ulna
Unseriated intermediate manual phalanx
Unseriated proximal manual phalanx
Unseriated proximal pedal phalanx
Unseriated rib
Unseriated thoracic vertebra
First (Medial) cuneiform

*I haven't checked through everything. See attached list for what I've checked so far.
[SE Zone images.xlsx](https://github.com/spawaskar-cora/cora-docs/files/2669026/SE.Zone.images.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify.
I have tried to get as many as I could, if I'm missing some, please let me know. 
This was because the new images had different file names

**Comment by clegarde** [comment]
I just looked through a bunch. Most important one I see that is missing:
Os coxa

Others:
Accessory rib (Image: Ribs 2-12)
Unseriated thoracic vertebra (Image: Thoracic and lumbar vertebrae)

**Comment by clegarde** [comment]
Verified!

Sacrum image for the coccyx and coccygeal vertebrae.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Added the zone images for Coccyx and Coccygeal vertebrae. Please verify.
Also while doing the above I found Sacral vertebrae 1 - 5 did not have zone images, so took my best judgement and used the Sacrum image for these also. Please Verify these also and/or let me know if I should be using some other image.

**Comment by clegarde** [comment]
Verified! And yes, sacral vertebra should have sacrum image. Verified (we only have one sacral vertebra 1 in USS Oklahoma project, so I did not verify the other 4 sacral vertebrae).

It looks like we did not provide zones for the sacral vertebrae. @fedamann these should be the same as the zones for the sacrum as a whole, correct? Zones 1-4. The zone page is also not linking to the zone help:
![screen shot 2018-12-15 at 9 22 39 am](https://user-images.githubusercontent.com/7350474/50044607-b0301880-004b-11e9-80d0-5b132cc54343.png)

Here is the sacrum:
![screen shot 2018-12-15 at 9 29 28 am](https://user-images.githubusercontent.com/7350474/50044638-1452dc80-004c-11e9-8c93-b0a8968c441a.png)

@SachinPawaskarUNO This led me to discovering a discrepancy between the zone descriptions in CoRA and those in the help for the sacrum (sorry I did not notice this earlier!). I verified, and the help is correct, so the zones in CoRA should match the help for the sacrum. If we're doing a shortened description, I should think the following would be acceptable. @fedamann can verify if necessary:
1 - Body
2 - Right ala
3 - Left ala
4 - Spinous process

**Comment by fedamann** [comment]
Help guide is correct, app page wrong.  Concur w/ @celarde for short handle fix of sacrum in ui

**Comment by clegarde** [comment]
@SachinPawaskarUNO Sacral vertebrae 1 - 5 can be the same zones as sacrum.

**Comment by clegarde** [comment]
GTG
