### ISSUE TITLE
Add "Results Confidence" to mtDNA Advanced Report and/or Dashboard DNA Sampled details

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#322]
Would be nice to have "Results Confidence" as a way to generate a report in mtDNA Advanced reporting.
![mtdna advanced report](https://user-images.githubusercontent.com/7350474/49889768-f72dcc00-fe07-11e8-870a-2df1a3bf3a73.png)
Also would be nice to be able to sort by "Results Confidence" in the DNA Sampled dashboard details since this is how the chart is being generated.
![dashboard_dna sampled_add results confidence column](https://user-images.githubusercontent.com/7350474/49889776-fc8b1680-fe07-11e8-8fa1-e39e72832d51.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @fedamann This is working as designed. Some of the Dashboard widgets (including DNA sampled) only updates once a day (actually the night before). So the data will be refreshed the next time the job runs.

**Comment by clegarde** [comment]
The mtDNA report is likely to change, but I'm reiterating here that we really need a way to generate reports/searches by "Results Confidence". I chatted with @SachinPawaskarUNO about this and it is something we will come back to at a later date. 
I'm linking to #321 (closed) since I made some related comments on the issue there.

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy please keep this in mind for our DNA Module redesign. We will need to look at all DNA Reports.

**Comment by SachinPawaskarUNO** [comment]
@clegarde I have added the Results Confidence column to the DNA sampled Dashboard drilldown.

**Comment by clegarde** [comment]
That is great! I can't see it since you disabled the "View Details" button, but I think that will be helpful to have.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Yes, that is why I did not ask you to verify, as you rightly pointed out the reason. Once we address the memory/resources issue it will be available.

**Comment by clegarde** [comment]
Glad to see that we can now do a mtDNA report by provenance! Thank you!! This is working.

When I tried to do a search by "Results Confidence", I did not get any results:
![screen shot 2018-12-19 at 11 52 39 am](https://user-images.githubusercontent.com/7350474/50238340-ca883000-0384-11e9-9f3e-8f26dcf56333.png)

But I know there are samples marked "Inconclusive" - 12A, 145A, 151A, 77A

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
