### ISSUE TITLE
No zone description for cuboid

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#323]
Other tarsals (navicular and cuneiforms) say "1 - All". Cuboid only has "1- ". Not that "All" provides a lot of information, but for continuity.
![cuboid_zone_no text](https://user-images.githubusercontent.com/7350474/49890594-1299d680-fe0a-11e8-8aba-98c0ece9c284.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
