### ISSUE TITLE
No zone images for cranial bones - no zones for palatine, vomer, ethmoid, lacrimal, inferior nasal concha

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#324]
1. There are no zone images for the bones of the cranium. We can add the same image that is used for the cranium for the following:
Maxilla
Occipital
Parietal
Sphenoid
Temporal
Frontal
Zygomatic
Nasal

2. The following do not have any zones marked with the cranium:
Lacrimal
Palatine
Ethmoid
Vomer
Inferior nasal concha
@fedamann @cbrown311 @mei215 @emilystreetman @nyukyi , can/should we add additional zones to the cranium to reflect these? Ex: 16 - left lacrimal, 17 - right lacrimal, 18 - left palatine, 19 - right palatine, 20 - ethmoid, 21 - vomer, 22 - left inferior nasal concha, 23 - right inferior nasal concha. All of these are depicted in the cranial images already, except for the inferior nasal concha, but I don't think those need to be pointed out. 

3. Finally, "unidentified cranium" does not have a zone image, but I would suggest removing zones from this altogether. If we cannot identify it to a particular part of the cranium, we won't be able to mark a zone anyway. @fedamann @cbrown311 @mei215 thoughts?

Linking to #319

**Comment by emilystreetman** [comment]
1. This is an issue related to the business rules of cranium inventorying that we have discussed being different between projects. For the _Oklahoma_, the rule is to only inventory an element as cranium, and mark zones so that all cranial remains are searchable by bone, single zone, or combined zones. For other projects, if they do individual bones, there is no point in doing zones because there are not multiple zones within an individual bone, and therefore that data would not be useable or searchable in any meaningful way. I'm not sure that adding the image, or even allowing zones to be marked, is the best way to proceed with individual cranial bones. (E.g. left parietal = cranial zone 4. Marking the zone provides no additional information or back-end data)

3. Agreed.

**Comment by emilystreetman** [comment]
2. If we add these delicate bones as zones, would we have to also add them as freestanding disarticulated cranial bones? That is how the other cranium zones exist in the system. Left maxilla is zone 12 on a cranium, but can also be inventoried as an individual bone.

**Comment by clegarde** [comment]
They already exist in CoRA as individual bones, so I would assume we would treat them in the same manner as the other cranial elements that currently have zones.

**Comment by mei215** [comment]
1. Agree with Emily.

2. It would be ideal to be able to capture the presence of the small bones of the face if possible. 
  
3. Agreed

**Comment by emilystreetman** [comment]
Issues 1 and 3 have been dealt with in separate tickets (#334, #342). Currently, we still need to deal with issue 2 from the original ticket, and I think we're agreed that @clegarde 's suggestion is good.

I suggest that next steps are @clegarde and @fedamann confirm the below and request action on it from the dev team:
Add zones to cranium: 
- 16 - left lacrimal
- 17 - right lacrimal
- 18 - left palatine
- 19 - right palatine
- 20 - ethmoid
- 21 - vomer
- 22 - left inferior nasal concha
- 23 - right inferior nasal concha

**Comment by clegarde** [comment]
Agreed that the listed zones should be added. 

@emilystreetman @nyukyi - can you add the numbers to the cranial image and update image/text in CoRA help docs? I think this is feasible without getting too cluttered. Use your discretion. If we can't add one, then we can just add a line and list in help docs "Zones not depicted:" or something. At a minimum, I think the palatines should be labeled. @fedamann please pipe in if you have any objections.

**Comment by emilystreetman** [comment]
Done.

Dev team, please create the zones indicated in the comment from @emilystreetman on Jan 24.

**Comment by clegarde** [comment]
GTG
