### ISSUE TITLE
Need zone info/images for help docs for malleus, stapes, incus, and hyoid

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#326]
We are missing the following in the help docs (so no image in CoRA, but the zones are listed):
-Malleus
-Stapes
-Incus
-Hyoid

Being worked on by @emilystreetman @nyukyi 

First mentioned in #319 but opening here for easier visibility and tracking.

**Comment by emilystreetman** [comment]
Pull request created following image upload

**Comment by SachinPawaskarUNO** [comment]
@clegarde @emilystreetman @nyukyi Cora now has the new zones images for malleus, stapes, incus, and hyoid. Please verify.

**Comment by clegarde** [comment]
I don't see these. Still showing placeholder. I also don't see them in the linked help.

**Comment by SachinPawaskarUNO** [comment]
@clegarde @emilystreetman @nyukyi The images are not showing in CoRA because the images are in jpg/jpeg format. They need to be in png format just like the rest of them. Please convert these to png and send me a pull request. I'll then upload them again to CoRA.
Please also note that I'll need the appropriate URL for the linked help, once it is created.

**Comment by emilystreetman** [comment]
New pull request sent with corrected image formats.

**Comment by SachinPawaskarUNO** [comment]
@clegarde @emilystreetman @nyukyi CoRA now has the new zones images for malleus, stapes, incus, and hyoid in the correct PNG format. Please verify.

**Comment by clegarde** [comment]
Images GTG in CoRA. @emilystreetman, can you add these to the zones.md and then provide the necessary URL link for @SachinPawaskarUNO to get these linked in CoRA to the help?

**Comment by nyukyi** [comment]
@SachinPawaskarUNO Verified for zones page, but the CoRA Docs that show up on the right side of the screen for these elements have not been updated.

**Comment by SachinPawaskarUNO** [comment]
@nyukyi @emilystreetman, Please see @clegarde comment above, someone at DPAA needs to add these to the zones.md and then provide the necessary URL link for @SachinPawaskarUNO to get these linked in CoRA to the help.

**Comment by emilystreetman** [comment]
Zones Help Guide updated and pull request made in github. Waiting for that help guide to go live so that I can find the links that should be connected to each element's zones page

**Comment by emilystreetman** [comment]
- Hyoid - https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#vertebrae-and-hyoid
- Malleus - https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#cranium
- Incus - https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#cranium
- Stapes - https://cora-docs.readthedocs.io/en/latest/forensics-anthro-guide/zones/#cranium

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman, @clegarde The above links to cora-docs have been updated. Please verify.

**Comment by emilystreetman** [comment]
@clegarde ossicles look good, but I just found out that there are two zones listed for hyoid 
1) body
2) greater horn
Do you think these should be left (2) and right (3) greater horns? Either way, I have to update the help guide and the image, because there is only a (1) present and the guide lists (1) as present/absent.

![image](https://user-images.githubusercontent.com/34662044/51762522-9267c180-2095-11e9-9400-5ecba99d92e7.png)

**Comment by clegarde** [comment]
@emilystreetman Yes! I think we should do the horns and body. Does K&Outram distinguish left and right? It seems like we should go ahead and do both.

**Comment by emilystreetman** [comment]
I don't see the hyoid in K&O at all - not sure where these two zones originated. I will make a new ticket for this issue - I think we could reasonably close this one and move the remaining narrow-scope conversation to the new ticket instead. ((I have verified the original issue, if @clegarde agrees, please close ticket.))

**Comment by clegarde** [comment]
K&O suggest zoning the hyoid per your particular research (pg 87), and an example being body, and left and right horns. Seems we're GTG with your new ticket to address this.
