### ISSUE TITLE
DNA Searches -> Make "Individual Number" link to report

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#327]
Can we have the Individual Number link to a report under a "DNA Search"? It appears we only have this a link to the report under "Skeletal Element" search options. In the example below I was doing a "Mito Seq Number" search for 282.
![link individual number to report](https://user-images.githubusercontent.com/7350474/50576772-9e39ce00-0dde-11e9-88b9-cad95184fac5.png)

We have this ability under a "Bone" search:
![a1 humerus search](https://user-images.githubusercontent.com/7350474/50576782-e2c56980-0dde-11e9-9012-89441e79b496.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
Awesome! GTG
