### ISSUE TITLE
Sca_03 and Sca_04 labels swapped

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#328]
The measurement numbers are swapped for Sca_03 and Sca_04. This was a problem with the labeling of the original data. CoRA Help Docs are correct.
Sca_03 - Glenoid cavity breadth
Sca_04 - Glenoid cavity height

The data matches the description NOT the measurement name. In the example below, glenoid cavity breadth = 29.03. It should be:
Sca_03 Glenoid cavity breadth = 29.03
Sca_04 Glenoid cavity height = 40.5

![screen shot 2019-01-02 at 6 03 14 pm](https://user-images.githubusercontent.com/7350474/50621611-83de1e00-0ecc-11e9-9865-00a4c8244b34.png)

**Comment by fedamann** [comment]
Put on hold

**Comment by fedamann** [comment]
Sachin will make the change to the label this weekend. However, this one is more complicated than the Fem_05 and Fem_06 because the glenoid measurement data will need to be swapped after he makes the label change.  Go interns!

**Comment by clegarde** [comment]
GTG
