### ISSUE TITLE
Fem_05 and Fem_06 descriptions swapped

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#329]
Another problem with the original data. This is a swap in the measurement description, so the measurement name (Fem_05) matches the data (33.5). CoRA Help Docs are correct. Should be:
Fem_05 Medial-Lateral (Sagittal) Subtrochanteric Diameter = 33.5
Fem_06 Anterior-Posterior (Transverse) Subtrochanteric Diameter = 28.07

![screen shot 2019-01-02 at 4 54 28 pm](https://user-images.githubusercontent.com/7350474/50621825-29de5800-0ece-11e9-8764-29e874729ba7.png)

**Comment by fedamann** [comment]
Put on hold

**Comment by clegarde** [comment]
These are errors that I think should be addressed sooner rather than later. It could cause problems with data entry for anyone that uses CoRA. If they read the description, they may put in the wrong measurement and it doesn't match the data in the help docs (which is correct), so it's confusing.

**Comment by jjlynch2** [comment]
Just some more information: OsteoSort and the Standard list has already been updated to match what @clegarde  is saying. I thought this issue (and the scapula one) had already been resolved.

**Comment by fedamann** [comment]
Thanks @jjlynch2 and @clegarde for the verification. That is want I wanted to get sorted.

**Comment by fedamann** [comment]
Sachin will make the change to the label this weekend, and should complete this task.  The data will be correct once the label swap is made.

**Comment by clegarde** [comment]
GTG
