### ISSUE TITLE
Error when saving zones

### ISSUE THREAD

**Issue by sfuehr** [spawaskar-cora/cora-docs#335]
Got the following error when saving zone information for an element. When I clicked Back on my browser, it had successfully saved the zone, despite this error appearing.

It won't let me attach the snip of the error message, but it's the one with the white background that says "Whoops, looks like something went wrong."

**Comment by rpernst** [comment]
@sfuehr This should be fixed now.

**Comment by sfuehr** [comment]
Verified and will close ticket.
