### ISSUE TITLE
Ability to export advanced search results

### ISSUE THREAD

**Issue by sfuehr** [spawaskar-cora/cora-docs#336]
Can we have an export option on the results page of advanced searches? Related to ticket #286.

**Comment by emilystreetman** [comment]
This is what @cbrown311 suggested as a solve for searching for left femora with OR without an I-# attached, but it is not currently possible to export the results:
![image](https://user-images.githubusercontent.com/34662044/50998983-bef4d880-14ee-11e9-82b0-fcb0cd150c38.png)

**Comment by SachinPawaskarUNO** [comment]
@sfuehr Please verify

**Comment by emilystreetman** [comment]
Verified and closed.
