### ISSUE TITLE
Remove zones pages for some elements

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#342]
The following elements should not have a Zones page active:
- coccygeal vertebra 1
- coccygeal vertebra 2
- coccygeal vertebra 3
- coccygeal vertebra 4
- Ethmoid
- Inferior nasal concha
- Lacrimal
- Maxilla
- Nasal
- Occipital
- Palatine
- Parietal
- Temporal
- Unidentified Cranium
- Unidentified Metacarpal/tarsal
- Unidentified Phalanx
- Unidentified Vertebra
- Vomer
- Xiphoid Process
- Zygomatic

Related to #324 and #334 
This list includes bones of the cranium that, when inventoried individually, consist of a single zone. Since zones cannot be searched across elements (aka you can't search for zone 11 from cranium AND zygomatic), zone information should either be automated or deleted for these elements. Additional elements listed are those for which zonation is not possible or needed, such as unidentified elements or coccygeal vertebrae.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please verify

**Comment by emilystreetman** [comment]
Verified and closed.
