### ISSUE TITLE
Elements that need to be linked to existing zones images

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#343]
The following elements should get the indicated images added to their Zones page

Extra vertebra - thoracic_500.png
Frontal - cranium_zones_composite_500.png
Sphenoid - cranium_zones_composite_500.png
Sternal body - sternum_500.png

Related to ticket #342

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please verify

**Comment by emilystreetman** [comment]
Extra vertebra, frontal, sphenoid, sternal body - good

Verified and closed.
