### ISSUE TITLE
Additional elements for "count" to be added to

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#344]
Per comment by @SachinPawaskarUNO: In the future, we may also want to consider the following as countable. Thoughts?

- unseriated cervical vertebra
- unseriated lumbar vertebra
- unseriated metacarpal
- unseriated metatarsal
- unseriated rib
- unseriated thoracic vertebra

Following discussion in ticket #182

**Comment by fedamann** [comment]
@emilystreetman: These look good to me, and I would add Tissue to this list too provided "count" also includes "weight" per @CTegtmeyer and #350

**Comment by emilystreetman** [comment]
Agreed, please add to list of countable elements:
- Tissue
- Hair (once it's created)

**Comment by SachinPawaskarUNO** [comment]
This is related to #350 and #351.
@emilystreetman Tissue and Hair have been added as countable. Please verify

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman, @CTegtmeyer and @fedamann Currently we have the following specimens as being countable. Please review this list and let me know if we are missing something, I see that we have a bunch of tickets related to making specimens countable (one on Sesamoid, the list I have in this ticket above, do we still need these specimens as countable?).

List of specimens that are currently countable
1. - Unidentified fragments
2. - Unseriated intermediate pedal phalanx
3. - Unidentified long bone
4. - Unidentified cranium
5. - Unidentified rib fragments
6. - Unidentified metacarpal/tarsal
7. - Unidentified phalanx
8. - Unidentified vertebra
9. - Unseriated proximal manual phalanx
10. - Unseriated distal manual phalanx
11. - Unseriated distal pedal phalanx
12. - Unseriated intermediate manual phalanx
13. - Unseriated proximal pedal phalanx
14. - Tissue
15. - Hair

**Comment by emilystreetman** [comment]
Per @fedamann 's previous comment, yes, these additional 7 elements should be countable.

**Comment by SachinPawaskarUNO** [comment]
related to #337
@emilystreetman, @CTegtmeyer and @fedamann The following are now countable. Please verify

1. Sesamoid
2. Unseriated cervical vertebra
3. Unseriated lumbar vertebra
4. Unseriated metacarpal
5. Unseriated metatarsal
6. Unseriated rib
7. Unseriated thoracic vertebra
