### ISSUE TITLE
View details buttons don't work

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#346]
The "View Details" buttons on the dashboard for the charts aren't click-able. I cannot view the details of any of the charts, either the standard ones or the new ones I add to the dashboard.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer This has been done intentionally as these queries pull in a lot more data and currently can degrade performance on the servers. This is related to the 500 limit. This is a known issue and @fedamann is aware of this. We are working towards getting additional memory resources on these servers.

**Comment by CTegtmeyer** [comment]
Understood. Will close this issue.
