### ISSUE TITLE
"DNA sampled" check mark doesn't appear on search results

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#347]
A check mark doesn't appear on the search results page for elements that have been DNA sampled. (See Left femur, element 401 below)

![dna check mark capture1](https://user-images.githubusercontent.com/36896992/51217907-2d121480-18ce-11e9-83ba-4e7656ab0978.JPG)

![dna check mark capture](https://user-images.githubusercontent.com/36896992/51217910-3307f580-18ce-11e9-9879-f4bfa5361abd.JPG)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer The current process is that you should create a DNA Profile record before you mark the Specimen as DNA sampled. Once you do that it will automatically show you the DNA Sample number in that column. This is new functionality based upon feedback from @clegarde, She can provide more details in needed.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer and @clegarde Please verify and close out. We now are displaying DNA sample number links for easy access of DNA data in search screens

**Comment by clegarde** [comment]
GTG
