### ISSUE TITLE
Cannot add DNA sample numbers

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#349]
When trying to add DNA sample numbers and update DNA profile for a specimen, the saved page cannot be found.

I tried to add sample number 01A to this specimen, and when I went to save the page, I got an error (see below).

![mtdna save capture](https://user-images.githubusercontent.com/36896992/51218307-e0c7d400-18cf-11e9-8e2d-fc7b86368dcd.JPG)

![mtdna save capture1](https://user-images.githubusercontent.com/36896992/51218312-e45b5b00-18cf-11e9-9e5a-9d4791f608e4.JPG)

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer That is a bug, @nmcelroy Can you please take a look at this?

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy This is failing in the checkUniqueDnaSampleNumber() function. Happens in CAT, so you can verify it there. Please check this out ASAP.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Please verify

**Comment by CTegtmeyer** [comment]
verified
