### ISSUE TITLE
Weight/Mass option for tissue?

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#350]
Would it be beneficial to have a weight/mass box for tissue? This gets weighed in the course of analysis, but there isn't currently an option to put a mass like there is for fragments.

**Comment by emilystreetman** [comment]
Please verify

**Comment by CTegtmeyer** [comment]
still no weight or count function available for tissue

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Please verify

**Comment by emilystreetman** [comment]
verified
