### ISSUE TITLE
Hair as a new category or as part of tissue?

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#351]
This is something I'd like feedback on from the group. Should hair (and nails for that matter) be a part of tissue or should they be their own category? Hair especially may be important as the isotope project moves forward for analysis, and currently there is no way to individually capture its presence in CoRA.

**Comment by fedamann** [comment]
add hair

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Please verify

**Comment by fedamann** [comment]
Verified
