### ISSUE TITLE
Need to delete elements

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#355]
We need to be able to delete elements.  Logged in as a PM, but still cannot delete a duplicated element.  There are two options for "Discard Changes" once you are editing an element, but no option for delete.
![cora duplicated element](https://user-images.githubusercontent.com/34662044/51340383-67a5b980-1a54-11e9-8062-b6105f2a8b5f.png)
![cora edit](https://user-images.githubusercontent.com/34662044/51340381-670d2300-1a54-11e9-87ae-2eb1d115dd49.png)
![cora need delete option](https://user-images.githubusercontent.com/34662044/51340382-670d2300-1a54-11e9-80ba-d791557031cf.png)

**Comment by SachinPawaskarUNO** [comment]
@cbrown311 Please verify

**Comment by cbrown311** [comment]
Verified.  Deleted duplicated element without any issues.
