### ISSUE TITLE
How are units indicated in "Mass" field?

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#358]
The mass field is only available in "count" elements. I don't believe there's a way to indicate units. If CoRA is making a unit decision, I suggest it be indicated to the right of the fillable numeric field (e.g., "grams (g)")

I can't test whether this field is numeric only, due to an editing issue that I have to make a different ticket for.

![image](https://user-images.githubusercontent.com/34662044/51710585-36e2f880-1fef-11e9-9148-ee27eb99bff7.png)

**Comment by CTegtmeyer** [comment]
The field is numeric only (based on the last time I've used it), the g cannot be added. I agree that standard operating procedures should make mass be in grams, or that it be fillable to the right of the field.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman, @CTegtmeyer, The unit of measure (UoM) for mass is set at the Organization level by the Org Administrator, in your case @fedamann. You should now see the UoM displayed to the right as shown below. Please verify.
![image](https://user-images.githubusercontent.com/19599773/51882903-2c559580-2346-11e9-8e19-ec96052971ed.png)

**Comment by emilystreetman** [comment]
verified
