### ISSUE TITLE
Element sorting in new Individual Number Report

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#360]
I can't tell how the elements within an individual number are sorted. Could these please be sorted/alphabetized by Key or Element name?

![image](https://user-images.githubusercontent.com/34662044/51711480-de612a80-1ff1-11e9-927e-a18b50225ac1.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please Verify

**Comment by emilystreetman** [comment]
verified
