### ISSUE TITLE
Auto-populated drop down menus keep your mistakes

### ISSUE THREAD

**Issue by Megyesimm** [spawaskar-cora/cora-docs#363]
When entering new skeletal elements - the drop down menus for Accession and Provenance keep ANYTHING you have EVER entered in them, even if its a mistake and you fixed that entry.  For instance, now I have GC 215 (instead of CG 215)  forever in the drop down menu, even though it was fixed and it does not exist in an entry.  Same with any mistake in Accession numbers.  Can we delete items in the Auto-populated drop down menus?

**Comment by SachinPawaskarUNO** [comment]
@Megyesimm, @fedamann This is not a CoRA issue, This auto saving of previous values is done by your Browser for form inputs. You can clear your browser cache to clear these saved values.

**Comment by SachinPawaskarUNO** [comment]
@Megyesimm, you probably still have this in your Accessions, so go to the accessions for your project and delete it. It only allow you to delete it as long as you do not have any Specimens that are tied to it.
@fedamann I think we need to have and provide some more structured, formal and regular training for folks.

**Comment by Megyesimm** [comment]
The typos are no longer in the accessions.  That is the whole issue.  When you mistakenly enter something incorrectly, and then go back and fix it, the mistake/typo remains an option to choose from.

**Comment by SachinPawaskarUNO** [comment]
@Megyesimm Can you send me the entire accession, meaning AN and P1 that this is happening for? I'm assuming this is for the Cabanatuan project. Can you also add a screenshot? might give be some clues and clarify things for me.

For others in the future, Please note that if you removed it using the Accession Management screen and then made the typo, you need to clear your form cache.

**Comment by Megyesimm** [comment]
met with Sachin and I figured out how to resolve this issue
