### ISSUE TITLE
Automatic project switching from Org Administrators Dashboard

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#364]
Automatic project switching from Org Administrators Dashboard

**Comment by fedamann** [comment]
@sachin this function appears to be working. From the org admin dashboard I can select a project from the data grid and be taken to the specific project dashboard without having to switch the project from the top drop-down menu.  When switching to a new project dashboard page the project menu automatically swaps over.

**Comment by SachinPawaskarUNO** [comment]
@fedamann Yes I coded this for you and @John Byrd and was going to ask you to verify this and close this ticket out. Plus I wanted this feature to demo to the Rear Admiral. Can you please close this out if verified?

**Comment by fedamann** [comment]
Verified.
