### ISSUE TITLE
Update zone names (and image and guide) for hyoid

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#365]
Following #326 and discussion with @clegarde:
For the dev team to update, the zones for hyoid should be - 

1. Hyoid body
2. Left greater horn
3. Right greater horn

Also, @emilystreetman will update the related image and help guide section.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please verify

**Comment by clegarde** [comment]
The three zones have been added in CoRA. @emilystreetman can you please update the help guide?

**Comment by emilystreetman** [comment]
Help guide text and images updated. Waiting for merge to verify they're live before closing this ticket.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please verify

**Comment by emilystreetman** [comment]
Image in CoRA and CoRADocs not updated

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Images in CoRA will be updated at a later date. For now can you please verify the CoRA Docs images. I'm seeing an issue with rotated images. Is this related to what you did?

![image](https://user-images.githubusercontent.com/19599773/55187977-3e965900-5168-11e9-9a56-e78fc82d8bb4.png)

**Comment by emilystreetman** [comment]
Hyoid images are OK - verified and closing. @SachinPawaskarUNO your last comment is related to ticket #324, not this one
