### ISSUE TITLE
"Dna" needs to be "DNA"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#366]
DNA needs to be capitalized.
![screen shot 2019-01-29 at 8 13 26 am](https://user-images.githubusercontent.com/7350474/51914295-24c1db00-239e-11e9-978c-9efdeaa3b550.png)
![screen shot 2019-01-29 at 8 13 37 am](https://user-images.githubusercontent.com/7350474/51914297-268b9e80-239e-11e9-9c78-be764afaf33f.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
