### ISSUE TITLE
Confusing screenshot in help manual under create new skeletal element

### ISSUE THREAD

**Issue by Katie-East** [spawaskar-cora/cora-docs#369]
In the CoRA online help manual under User Guide>Skeletal Element>Creating a New Skeletal Element, the screenshot uses a "Left, Complete, Third Cervical Vertebra" as an example. This is incorrect at DPAA or for outside users because if a midline element is described as left it cannot also be complete. This is present in a number of places on this page: 
https://cora-docs.readthedocs.io/en/latest/user-guide/skeletalelements/#creating-a-new-skeletal-element

I would suggest changing this example to the following "Middle, Complete, Third cervical vertebra". Screenshots will follow:
<img width="908" alt="middlecervical" src="https://user-images.githubusercontent.com/34662044/52239366-e2176b80-2893-11e9-9d2a-c0d4c339ac64.PNG">

I can update the md doc if this correction is OK.

**Comment by SachinPawaskarUNO** [comment]
@Katie-East and @fedamann This is a good idea. Please feel free to change the docs/screenshots as you see fit. I will leave it up to the anthropologists to discuss and update docs/screenshots.

**Comment by Katie-East** [comment]
I have updated the create "new skeletal element" and "view skeletal element" screenshots in the user docs.
