### ISSUE TITLE
Autopopulate mtDNA Results Confidence

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#371]
Requesting an option to autopopulate the mtDNA Results Confidence Field with "Reportable" as soon as sequence data is entered.

E.g., an analyst enters mtDNA Seq 5 for an element.  Because we have a specific sequence, we know the data is reportable.

![image](https://user-images.githubusercontent.com/34662044/52370381-5844db00-2a18-11e9-9e63-3848209d0310.png)

**Comment by SachinPawaskarUNO** [comment]
Based upon conversation in SCRUM today, this violates our current rule that the mito sequence number and some other fields are only available when the results are reportable

**Comment by cbrown311** [comment]
Agree.  Closed.
