### ISSUE TITLE
Tibia doesn't show up for Articulations with Talus

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#377]
When I tried to add articulations for a talus, tibia doesn't show up and is not an option even when I type it in, but when I went to tibia and added articulation with talus, it works.

Here's a screenshot of my issue:
https://imgur.com/ubChJOq

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Good catch. This is a data issue related to missing data for articulations from original list provided by Anthropologists. 
@fedamann FYI, I'll get this missing articulation added in CoRA.

**Comment by SachinPawaskarUNO** [comment]
@nyukyi This data issue has been fixed. Please verify.

**Comment by nyukyi** [comment]
@SachinPawaskarUNO Looks good now, thank you!
