### ISSUE TITLE
Links to mito sequence on Dashboard are broken

### ISSUE THREAD

**Issue by lfkennedy** [spawaskar-cora/cora-docs#378]
clicking links in dashboard sometimes results in a "page not found" error

![broken link1](https://user-images.githubusercontent.com/34662044/52660023-5f5e6400-2ec4-11e9-8fd6-a4efb3a62738.PNG)
![broken link2](https://user-images.githubusercontent.com/34662044/52660027-608f9100-2ec4-11e9-9c93-5c1469f163ff.PNG)

**Comment by emilystreetman** [comment]
I recreated this issue at my station using the following steps:
1) Go to dashboard
2) Under the "User Activity: DNA" module on the lower right, click on the hyperlink for a mitochondrial DNA sequence (in my case "251")
3) "Sorry, the page you are looking for could not be found." error appears with the following URL: https://www.coracore.org/reports/mtDNA/results/251

**Comment by SachinPawaskarUNO** [comment]
@lfkennedy @emilystreetman This should now be fixed. Please verify.

**Comment by lfkennedy** [comment]
Verified. I'll speak for Emily, too.
