### ISSUE TITLE
Searching by I number

### ISSUE THREAD

**Issue by jjlynch2** [spawaskar-cora/cora-docs#381]
Perhaps this is a resource problem? 

Sometimes when searching by an I number the element that is associated via articulation only (not via mtDNA sequence) does not show up under the I number results (despite it having the same I number). The results will return the 14  mtDNA sequenced elements rather than all 15 associated elements. This happens very randomly and I cannot always replicate it.

**Comment by SachinPawaskarUNO** [comment]
@jjlynch2 Can you provide us with the I-Number is question and project name, I'm assuming you are doing the quicksearch from the nav header. Are you doing Specimens by I-Number or DNAs by I-Number?

**Comment by jjlynch2** [comment]
Ah, disregard this issue. Just a PEBKAC. I was accidentally doing DNA by I number.
