### ISSUE TITLE
Moving forward through tabs during peer review

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#384]
After I saved Measurements Review page, the screen automatically reloaded the General tab. I suggest auto-forwarding to the next tab to streamline the review process.

![image](https://user-images.githubusercontent.com/34662044/52819802-e3088400-306f-11e9-9c1a-68966761e8f7.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Please verify

**Comment by emilystreetman** [comment]
This didn't work for me, but I don't have a case that I'm actively peer reviewing - @nyukyi and @Katie-East can you speak to this?

**Comment by nyukyi** [comment]
@emilystreetman It technically works, but it does weird things in between.  So for example, when I finish reviewing "Measurements," and then hit save, it goes straight back to "General," which is the first tab on the list.  And then it freezes up for a few minutes, and you get a "coracore.org is not responding" message at the bottom, and only then, it goes to the next tab.  It does that every time I hit "save" after putting in peer review notes/measurements.

**Comment by Katie-East** [comment]
While reviewing one page (such as the measurement page) it will occasionally revert back to the general page even if I haven't hit save or accept.

**Comment by clegarde** [comment]
This appears to be functioning properly now.
