### ISSUE TITLE
Dashboard won't display

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#387]
I logged into today and when I go to click on the Dashboard Icon, it comes up with the "Whoops looks like something went wrong" error. Is anyone else getting this error? I am using CoRA on edge, so we already know there are issues there. I am not sure if it is a system bug or an edge bug.

**Comment by clegarde** [comment]
I am also having this problem in Edge and IE. Getting the "Whoops, looks like something went wrong." error. I can check Chrome later today.

**Comment by CTegtmeyer** [comment]
The dashboard appears to be working properly now.

**Comment by fedamann** [comment]
It works in chrome on a non-DPAA network

**Comment by CTegtmeyer** [comment]
Closing this issue as the dashboard appears to be working okay now. Will reopen if fails to display again.
