### ISSUE TITLE
Individual Numbers Report Excel Export

### ISSUE THREAD

**Issue by jwarsom** [spawaskar-cora/cora-docs#389]
Individual Numbers Report Excel Export
Behavior: Export to excel only outputs the first skeletal element assigned to an individual number. 
Expected: Export to excel outputs each of the skeletal elements assigned to an individual number.
Browser Used: Chrome

**Comment by jwarsom** [comment]
<img width="735" alt="screen shot 2019-02-25 at 1 46 28 pm" src="https://user-images.githubusercontent.com/22533192/53364195-e61f3200-3903-11e9-83d8-d2a02ac84e4a.png">

**Comment by SachinPawaskarUNO** [comment]
@jwarsom The data for all specimens is there. Just click the cell to see it. See screenshot below.

![image](https://user-images.githubusercontent.com/19599773/53593181-a3f12d00-3b5d-11e9-8e89-f97f519d972e.png)

**Comment by jwarsom** [comment]
Verified!
