### ISSUE TITLE
Bug When Trying To Add Zone Data

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#39]
I encountered the following bug when trying to input zone information for multiple different elements @SachinPawaskarUNO 

<img width="564" alt="1" src="https://user-images.githubusercontent.com/33871387/36040950-a965586a-0d8c-11e8-8242-4e852d209a81.PNG">
<img width="205" alt="2" src="https://user-images.githubusercontent.com/33871387/36040952-aa407f76-0d8c-11e8-8392-29908e889bb1.PNG">

**Comment by SachinPawaskarUNO** [comment]
This issue has now been addressed via SachinPawaskarUNO/cora#381
