### ISSUE TITLE
Zone page wont display

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#390]
I am getting the "Whoops, looks like something went wrong error" when trying to access the zone page. This is similar to the dashboard issue I had yesterday. I don't know if there is a bug that is making these pages temporarily unable to display? Seemed like it was working fine yesterday.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Please verify, I think this is longer an issue.

**Comment by CTegtmeyer** [comment]
Correct. It is working now. I will close the issue.
