### ISSUE TITLE
Os coxa > Age method > McKern and Stewart 1957 - no composite score when sum is 0

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#391]
We just had help getting the composite score sum for this method. Edit, then save for the composite score to show. For those with a score of 0 for each (Dorsal, Ventral, and Rim), it would not provide a composite score. The composite score field remained blank. 
Ex: CIL 2003-116-G-04-X-56G-901
Will upload screenshot when I can.

**Comment by clegarde** [comment]
Not sure if this will work...
https://drive.google.com/open?id=1-DYlRx1QRdAQDkunhNjj8MsKM9WIg8zG

**Comment by SachinPawaskarUNO** [comment]
@clegarde This was an odd/tricky scenario, I'm guessing this only happens when the composite score adds up to 0. Is that correct?

**Comment by clegarde** [comment]
Yes, this is happening when each score is 0, so the composite score is 0.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, Please verify

**Comment by clegarde** [comment]
GTG
