### ISSUE TITLE
Cannot associate additional pair matches manually after eliminating one

### ISSUE THREAD

**Issue by lfkennedy** [spawaskar-cora/cora-docs#395]
I am unable to click in the box that says "Select Pair Matches" on the pair match screen and/or to associate additional pair matches after one initial attempt.

Here is the path I followed to get to this point:
Left femur CIL 2003-116-G-07-X-241G-401 -> associations -> pair matches -> Actions -> Edit -> "Select"-ed CIL 2003-116-G-07-X-241G-402 as a possible pair match -> realized I had associated the wrong right femur and selected "mtDNA" as elimination reason -> Actions -> only "Discard Changes" is available as an action, not "Edit"

![image](https://user-images.githubusercontent.com/34662044/53585479-a2b70480-3b4b-11e9-81b4-0c859880ea5f.png)

**Comment by SachinPawaskarUNO** [comment]
@rpernst Please take a look at this issue.

**Comment by SachinPawaskarUNO** [comment]
@lfkennedy Please verify

**Comment by lfkennedy** [comment]
Verified.
