### ISSUE TITLE
mtDNA Report Enhancement

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#396]
When an mtDNA Report is created for a specific sequence, can there be other columns visible that indicate any other remains that have been associated with each element in that sequence by articulation, refit, and pair match?

It currently seems clunky/inefficient to determine what other elements have been associated. For example, if I see CIL 2017-310-X-5150--202 is associated with Ploesti DNA Sequence #13, I must then go to that element and then click on each type of Association (pair match, articulation, refit) to know if they exist.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed in CoRA v2.1.0
