### ISSUE TITLE
"Reviewed By" Column Not Updating

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#397]
When I review element inventories and check the boxes for "Inventory Completed" and "Reviewed," the column that should indicate this task has been done is not updating. As a result, I cannot tell unless I click on the element if the review has been completed.

**Comment by SachinPawaskarUNO** [comment]
@mei215 Good catch, Please verify.
@mei215 Are you receiving the notifications when you mark them are reviewed?
@tlvandeest Are you receiving the notifications when the reviewer marks the specimens you inventoried as reviewed?
@fedamann We need to document the behavior of the reviewed status flag change.

**Comment by mei215** [comment]
I am receiving notifications that a specimen has been reviewed as soon as I do that. However, the "Reviewed By" column does not update to show a name/check mark that the review has been completed. Also, the "Updated At" column does not update to show that the specimen has been recently updated.

**Comment by mei215** [comment]
Also, my project Dashboard Inventory section is not updating to show elements have been Inventoried and Reviewed.

**Comment by mei215** [comment]
Verified this is working now
