### ISSUE TITLE
Os coxa > Age (method) > McKern and Stewart 1957 pubic symphysis

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#398]
Os coxa > Age (method) > McKern and Stewart 1957 pubic symphysis
For this method, the age range for a composite score = 0 ("Composite Score - SUMALL") needs to be changed from "<17" to "<19". This is an update to the data we provided. Screenshot of example to follow.

**Comment by clegarde** [comment]
![MS 1957_CompScore0](https://user-images.githubusercontent.com/7350474/54166388-033f1f00-4433-11e9-978f-71794a16f2dd.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
