### ISSUE TITLE
Remains Status Enhancement

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#400]
Can there be an additional check box on the inventory page for Remains Status? A way to indicate if the remains are at the lab or have been released would be useful. A date box for when the remains were released would also be useful.

**Comment by SachinPawaskarUNO** [comment]
@mei215 @clegarde and @fedamann I like the suggestion, Is it just 2 items [In-Lab, Released]? Can you all do an internal discussion and come up with the a list of possible values for that dropdown?

**Comment by mei215** [comment]
Spoke with @clegarde, @skorps, @emilystreetman, and @cbrown311. The general consensus is two options for Remains Status: 1) In Lab and 2) Released. Having this function should make writing a group report at the end of a project easier and help with prioritizing APRs. 

@clegarde and @emilystreetman also suggested a separate area for Identification Status (also binary) with an area to record Date of ID.

**Comment by mei215** [comment]
added to new version and works
