### ISSUE TITLE
Profile Image Disclosure Bug

### ISSUE THREAD

**Issue by jjlynch2** [spawaskar-cora/cora-docs#405]
Another minor bug. Under 'My Profile' if you edit the user number in the browser URL, that users profile image will show up under your profile. Similar to the previous ticket #404 , this could allow none-DPAA staff (once CoRA becomes public) to view information that should be only accessible by admin level accounts.

**Comment by jjlynch2** [comment]
This also shows the "Role" assignment so you are able to determine which user accounts have management access, etc.

**Comment by SachinPawaskarUNO** [comment]
@jjlynch2 Please verify

**Comment by jjlynch2** [comment]
@SachinPawaskarUNO Verified
