### ISSUE TITLE
Update welcome screen image

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#41]
New image for welcome screen to replace POW/MIA flag.  
![commingulated assemblage](https://user-images.githubusercontent.com/12400947/36108817-9f837fc6-1015-11e8-885e-af644cc449c0.jpg)

**Comment by fedamann** [comment]
Or this one? 

![paco cemetery manila](https://user-images.githubusercontent.com/12400947/36109056-2f5ea38c-1016-11e8-9bdb-25589313f6a6.jpg)

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#403. This will be available in the next release.
