### ISSUE TITLE
Provenance 1 and 2 Search Formatting

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#410]
When I search for elements by Provenance 1 and 2, the suggested example that comes up in the search bar is formatted "G21 or G212," or "X1," etc. but I think most (if not all?) of us format it "G-21 or G-212" with a dash in between.  Is it possible to change the example format?

![CoRA_ProvenanceSearch](https://user-images.githubusercontent.com/34749060/54832135-9b39d580-4c89-11e9-95d7-ede80e8af616.PNG)

**Comment by SachinPawaskarUNO** [comment]
@nyukyi Please verify

**Comment by fedamann** [comment]
verified and closed.
