### ISSUE TITLE
Mito sequence specimen number on dashboard incorrect

### ISSUE THREAD

**Issue by skorps** [spawaskar-cora/cora-docs#415]
The number of specimens for mito sequence 2 is incorrect on the dashboard for Buna.  The dashboard says there are 6 specimens, but only 5 are entered (which is correct - there should be 5).  The other mito sequences displayed on the dashboard have the correct number of specimens.

![Mito Sequence 2 Dashboard](https://user-images.githubusercontent.com/37446598/54945352-997b4680-4f03-11e9-950f-bcf5dd84c2ec.PNG)

![Mito Sequence 2](https://user-images.githubusercontent.com/37446598/54945366-9e3ffa80-4f03-11e9-9286-1b58a7f8cf18.PNG)

**Comment by SachinPawaskarUNO** [comment]
@skorps Thanks for all the details provided, this is very useful. I think we have identified the issue. There were soft delete records that are being incorrectly being pulled into the count. This will be addressed in the next release.

**Comment by SachinPawaskarUNO** [comment]
@skorps Please verify

**Comment by skorps** [comment]
@SachinPawaskarUNO Verified
