### ISSUE TITLE
Left justify measurment roll-over help text

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#42]
The text inside the roll-over help menu should be left justified. It is currently center justified.

![measurement help roll-over text](https://user-images.githubusercontent.com/12400947/36109983-08a41562-1019-11e8-8ef0-42f11c6eb6bb.jpg)

**Comment by SachinPawaskarUNO** [comment]
Good idea @fedamann, This will be addressed in the next release.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#404. This will be available in the next release.
