### ISSUE TITLE
No ability to edit DNA sample number

### ISSUE THREAD

**Issue by kristengrow** [spawaskar-cora/cora-docs#429]
Currently, analyst do not have the ability to edit the DNA sample number under the DNA profile tab once it has already been entered. I noticed this when I entered the wrong DNA sample number for an element and tried to change it. Thank you!

**Comment by clegarde** [comment]
Only project leads or higher can make changes to DNA sample numbers. I believe only delete. But then the analyst can add new.

**Comment by kristengrow** [comment]
Sounds good. Thanks!

**Comment by kristengrow** [comment]
Sounds good. Thanks!

**Comment by SachinPawaskarUNO** [comment]
@clegarde Thank you for jumping in and providing the workflow. This is related to #354
