### ISSUE TITLE
Measurement help icon not visible IE11

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#43]
The help icon to the right of the data field does not display in IE11, but the text does show up when you mouse over the region.  
![measurement help roll-over text](https://user-images.githubusercontent.com/12400947/36110045-40fa0b2e-1019-11e8-98f8-0622a786749f.jpg)

**Comment by SachinPawaskarUNO** [comment]
I have tried this on IE and it works for me. The icons display correctly.

@fedamann This might be a DPAA only issue with regards to some script being blocked or an issue with the version of IE (IE update/build number) being used at DPAA.

**Comment by SachinPawaskarUNO** [comment]
@fedamann I was able to see the icons in IE11, see screenshot below.
This might be a DPAA only issue with regards to some style/font url being blocked or an issue with the version of IE (IE update/build number) being used at DPAA.

![image](https://user-images.githubusercontent.com/19599773/38960302-966e4fe6-4329-11e8-899d-66c10e0ebc33.png)

**Comment by clegarde** [comment]
This may be over kill, but I thought I'd show what we see in IE vs. Edge. Edge seems to be working pretty well. If it's working on a non-government computer, maybe there is some sort of block.
![no icons_dashboard](https://user-images.githubusercontent.com/7350474/38994829-14d127e0-43ad-11e8-9f2c-965cfa078f3b.PNG)
![no icons_details](https://user-images.githubusercontent.com/7350474/38994838-18dc34e2-43ad-11e8-9e3d-ce57fbd00ca1.PNG)
![no icons_help](https://user-images.githubusercontent.com/7350474/38994865-27bb674e-43ad-11e8-8ee8-690ccde1f1ec.PNG)
![no icons_delete](https://user-images.githubusercontent.com/7350474/38994870-2a7086c2-43ad-11e8-8060-27d3f10685fb.PNG)

**Comment by SachinPawaskarUNO** [comment]
@fedamann Based on our discussions and given that Microsoft is recommending the use of Microsoft Edge browser over IE for compatibility issues with W3C standards. We will not be addressing any IE related issues. Users should be encouraged to user the Microsoft Edge browser.
