### ISSUE TITLE
MCC Date blacked out when DNA results inconclusive

### ISSUE THREAD

**Issue by mattcgo** [spawaskar-cora/cora-docs#436]
Hello,
Thank you for all your work on improving CoRA! I'd like to point out that the MCC Date field when adding an inconclusive DNA result is blacked out. It may be beneficial to have the date attached to the inconclusive result in the event retesting is done in the future. That way, we know how long ago or outdated the inconclusivity is.
<img width="866" alt="Screen Shot 2019-04-22 at 8 20 19 AM" src="https://user-images.githubusercontent.com/49535698/56517126-e557e600-64d7-11e9-95d7-cec9fc6e9953.png">
Thank you,
Matt

**Comment by clegarde** [comment]
Hi Matt - the results date for the DNA sample is recorded in the field just above "Inconclusive." I believe that field should be sufficient since that ties more closely to the reporting of the data?

**Comment by mattcgo** [comment]
> Hi Matt - the results date for the DNA sample is recorded in the field just above "Inconclusive." I believe that field should be sufficient since that ties more closely to the reporting of the data?

Thank you Dr. LeGarde, you are right that I should just use the Receive Date. Apologies for not noticing it. I was trying to be consistent with how I entered information from all the other samples.

**Comment by fedamann** [comment]
Thank you @mattcgo and @clegarde for the feedback. I'm closing this ticket.
