### ISSUE TITLE
Add "Results Date" to mtDNA report

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#437]
@SachinPawaskarUNO , can we add the "Results Date" as a column for the output of the mtDNA Report? This would be helpful to have. 

![image](https://user-images.githubusercontent.com/7350474/56518404-fb2fd000-6504-11e9-8ca1-947e48b79f94.png)

**Comment by nmcelroy** [comment]
@clegarde would this be the mito receive date, austr receive date etc?

**Comment by clegarde** [comment]
Yes! Sorry about that. @nmcelroy

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed in CoRA v2.1.0
