### ISSUE TITLE
Add "Teeth" specimen with "count" field

### ISSUE THREAD

**Issue by veronicak7** [spawaskar-cora/cora-docs#439]
In situations where we have numerous unassociated teeth in an accession, we would like to have the ability to note the number of teeth present without having a separate record for each tooth. For example, in a JRO accession with numerous loose/unassociated teeth, not individually numbered and no DNA potential (as determined by an odontologist), it would be helpful to be able to enter "Teeth" and a count for the number of teeth present.

**Comment by mattcgo** [comment]
@SachinPawaskarUNO Thank you for adding the unnumbered "Tooth" option. May I also ask that we be able to articulate the unnumbered tooth option to a cranium or mandible? I have a case where the tooth was only identified as a maxillary tooth and not numbered, but it was articulated to the maxilla. I am unable to articulate the "Tooth" to the "Cranium" in CoRA.

**Comment by clegarde** [comment]
@SachinPawaskarUNO For skeletal element "Tooth" - need to add Count field.
"Tooth" 
->articulates with Cranium, Maxilla, and Mandible

Need to add the following:
"Maxillary Tooth"
-> articulates with Cranium and Maxilla
-> include Count field

"Mandibular Tooth"
-> articulates with Mandible
-> include Count field

I believe this hits what everyone was looking for. @fedamann @veronicak7 @mattcgo

**Comment by clegarde** [comment]
I believe this has been addressed. I checked "Tooth" and "Maxillary Tooth". There are no "Mandibular Tooth" in USS Oklahoma or Ploesti projects for me to check. Closing.
