### ISSUE TITLE
Measurement names are not in order and they should be

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#45]
The measurement names are not in sequential order. 
![measurement names order](https://user-images.githubusercontent.com/12400947/36113044-6c6c65cc-1023-11e8-89a9-f351bdd59b3a.JPG)

**Comment by SachinPawaskarUNO** [comment]
Good idea. Quite a few bone measurements were not is order in the original file received from DPAA, such as Humerus, Radius, Ulna, Os coxa, Femur, Talus, Cervical vertebra 1, Cervical vertebra 2. This will be addressed in the next release.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#405. This will be available in the next release.
