### ISSUE TITLE
Create new bone groups for Thorax, Pelvic Girdle and Vertebral Column

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#454]
Create new bone groups for the following, some with both left and right sided bones

- [ ] Thorax
- [ ] Pelvic Girdle
- [ ] Vertebral Column

**Comment by SachinPawaskarUNO** [comment]
Attached spreadsheet for new bone groups provided @clegarde based on work done by @clegarde and @CTegtmeyer

[CoRA_Bone groupings_New.xlsx](https://github.com/spawaskar-cora/cora-docs/files/3214903/CoRA_Bone.groupings_New.xlsx)

**Comment by clegarde** [comment]
This was completed for newest CoRA rollout. GTG
