### ISSUE TITLE
Add "Pending" to "Results Confidence" Field

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#455]
Right now, there is no way to search for all pending DNA samples. Please add "Pending" to the "Results Confidence" field. Also, make this the default when adding a new DNA sample. @SachinPawaskarUNO

**Comment by clegarde** [comment]
In CoRA Cat: having "Pending" as the default is not working since auSTR and Y-STR appear for each DNA sample, even if they haven't been requested. For the following sample, only mtDNA has been requested. The way this is set up in Prod, having this field default to Pending works because it's only for the type of DNA you requested, but it is not accurate for all three to default to Pending.
![image](https://user-images.githubusercontent.com/7350474/58912258-47168d00-86df-11e9-9483-fdff8057aa56.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde please verify in CAT.

**Comment by clegarde** [comment]
GTG
