### ISSUE TITLE
New vs View Skeletal Element check boxes

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#46]
Remove check boxes from "New Skeletal Element" page per discussion with @fedamann
On the new skeletal element page there are three check boxes, once saved, three more become available. This is a particular issue for mistakenly clicking the "Inventoried" box and locking the element for editing. Because the data has to be entered after the save, it is not necessary to have any of these boxes on the new skeletal element page ("pre-save"). They all could just become available after the element is saved since they should really only be checked after that data has been entered anyway.

![newskeletalelement](https://user-images.githubusercontent.com/7350474/36156122-d11385fa-109b-11e8-80ec-26eba12aa4ff.PNG)

![viewskeletalelement](https://user-images.githubusercontent.com/7350474/36155878-2b639e10-109b-11e8-9c22-1645ecb5de98.PNG)

**Comment by SachinPawaskarUNO** [comment]
This makes complete sense. Issue will be addressed in the next release.

**Comment by SachinPawaskarUNO** [comment]
This issue has now been addressed via SachinPawaskarUNO/cora#407
