### ISSUE TITLE
CoRA Cat: "Results Confidence" column not filling in after search

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#463]
I did DNA search -> Sample Number -> 1366A and received the following:
![image](https://user-images.githubusercontent.com/7350474/58911528-9f4c8f80-86dd-11e9-8350-a18e91098e58.png)

The "Results Confidence" is blank, but if you go to the element, that is filled in:
![image](https://user-images.githubusercontent.com/7350474/58911515-95c32780-86dd-11e9-8962-1bface505fd8.png)

**Comment by clegarde** [comment]
Looks like this is now affecting the dashboard for DNA samples:
![image](https://user-images.githubusercontent.com/7350474/58911848-682aae00-86de-11e9-929c-85a07cf16bd6.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify in CAT.

**Comment by clegarde** [comment]
GTG
