### ISSUE TITLE
Bone Groups Broken

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#464]
The Bone Group function appears to be broken in prod. Is anyone else having issues creating bone groups?

When I go to create bone groups (or at least hands), I get a "whoops looks like something went wrong" page.

**Comment by CTegtmeyer** [comment]
It appears as though this issue resolved itself, however, I do not want to close the issue, as I do not know what cause the Bone Group Function to stop working temporarily, and then start working again. Is it something we can look into?

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer This issue was caused because Heroku/AWS upgraded their redis queue which is used to queue up our bone group jobs. I think we can close this issue.

![image](https://user-images.githubusercontent.com/19599773/59234458-6ff0c380-8bb2-11e9-8675-2ecf71dfddc2.png)

**Comment by CTegtmeyer** [comment]
Sounds good. Will close.
