### ISSUE TITLE
Not able to accept peer review comments 

### ISSUE THREAD

**Issue by Katie-East** [spawaskar-cora/cora-docs#466]
This is a follow up to ticket #379 

I am still unable to accept peer review comments for analyses I have done to an element that I did not initially inventory. Instead I am shown the peer reviewer screen where I can edit the peer reviewer's measurements. 
![Peer review measurments](https://user-images.githubusercontent.com/46726506/59305634-3ffff980-8c60-11e9-9e1c-0006c7db9a79.PNG)

**Comment by clegarde** [comment]
Issue from past CoRA version. Closing.
