### ISSUE TITLE
Welcome Page Format

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#47]
Love the new photo! Please remove some of the extra space on the sides by narrowing overall box and/or enlarging photo. Also, enlarge "Welcome to CoRA" text to stand out as a title/header, please.

![welcomepage](https://user-images.githubusercontent.com/7350474/36159898-7d429254-10a5-11e8-9aac-e53b51a19083.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @fedamann, We need to discuss this further. It is not as straight forward as stretching the image. We need to get the image in the appropriate resolution and width and height. It also has to make sense on other devices such as Tablets/iPads and maybe Phones.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#429 & SachinPawaskarUNO/cora#409.
@clegarde and @fedamann Please verify and close out issue.
