### ISSUE TITLE
CoRA Cat: Isotope page broken

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#470]
The isotope page is broken in CoRA Cat. It brings up an error message when trying to access it (see below):

![Capture](https://user-images.githubusercontent.com/36896992/59636128-73bea180-90ee-11e9-8469-d8d6cce2f04b.PNG)

I'm not sure if this is intentional because I am not an isotope analyst or not, but I am not sure how to build isotope samples for analysis otherwise.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Can you share be screenshot of screen prior to this, what link/menu/nav did you click on. A screenshot of that would be helpful? Seems like you are missing some privileges.

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO All I did was search for a random humerus and then click on isotope analysis. But I've gotten this page when creating a new bone and also clicking on the link from there too. There isn't really anything else to screenshot. This is the isotope analysis link from the drop down menu on the skeletal element page.

**Comment by CTegtmeyer** [comment]
This issue has been resolved
