### ISSUE TITLE
Composite Key Search Confusion

### ISSUE THREAD

**Issue by btrnew** [spawaskar-cora/cora-docs#488]
Hi! Maybe this is a me problem, but I foresee it being confusing for others in the future as well (if it hasn't already happened). I was experiencing an issue that @CTegtmeyer has brought up before where we have accessions and provenances with greater than 500 entries. Once created, I was struggling to pull up elements using just the accession or provenance, so I tried using the composite key search function. Initially, I couldn't get the composite key search function to work because was following the format as it presents once you create an element (i.e. CIL2017-053-HF2016-020--3013). Upon closer inspection, I realized that the composite key search prompt indicates you should insert commas between your accession and provenance. 

Is it possible to clarify search criteria formatting in the help docs? I checked the site navigation section of the help docs and it indicates what kinds of searches are possible, but not how to conduct them/format appropriately. 

For example, when you select "Search by Bone" it prompts 
"SE eg. Humerus, Tibia, Cranium" where commas indicate separate single elements you can search. 
![CoRAsearch1](https://user-images.githubusercontent.com/43450732/61978395-e4c66400-af8c-11e9-83db-a73d3cfe0b7e.PNG)

However, when you select "Search by Composite Key" it prompts "SE e.g. CIL 2003,116,G-21,X-1,201 or CIL 2003-116,,," (and then it cuts off for me, so I'm not quite sure what the three commas indicate. I am assuming they might be missing provenance 1, provenance 2?, I-0 number?). In this search function, the commas in the prompt indicates a string of search parameters. I think, not unreasonably, the average user would assume a composite key has to be formatted exactly as it is presented everywhere else  (i.e. CIL2017-053-HF2016-020--3013 or CIL2017-053-HF2016-020) to pull the appropriate information.
![CoRAsearch2](https://user-images.githubusercontent.com/43450732/61978566-44bd0a80-af8d-11e9-8413-4b934f415e94.PNG)

Further clarification on the search function in the help docs would help users intuit how to find their data quicker and navigate the CoRA system better.

**Comment by SachinPawaskarUNO** [comment]
@stutiraut We need to document how the entire search capability works

**Comment by SachinPawaskarUNO** [comment]
Help documentation has been updated with more clarification.
