### ISSUE TITLE
Typo on Dashboard

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#49]
Missing a space between "skeletal elements" on dashboard under the highlights of the project. 

![dashboardtypo](https://user-images.githubusercontent.com/7350474/36167758-9098d572-10bc-11e8-8380-caecf7d181f0.PNG)

**Comment by SachinPawaskarUNO** [comment]
This issue has been fixed via SachinPawaskarUNO/cora#411
