### ISSUE TITLE
Enhancement to New ID, Release, Status Fields

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#499]
![1](https://user-images.githubusercontent.com/33871387/63028005-957ca080-be73-11e9-8d84-d54d62ec321c.JPG)

Would it be possible to batch this information? For example, can all elements grouped as Individual # I-01 be given the same ID date, release date, and status once, as opposed to adding this information for each element?

**Comment by mei215** [comment]
Also, can Remains Status be something added to the Dashboard? It would be useful to be able to visualize remains in the lab versus remains released.

**Comment by mei215** [comment]
@SachinPawaskarUNO I think this would be great to have these days as large quantities of remains are released from the lab...@clegarde what do you think?

**Comment by SachinPawaskarUNO** [comment]
@mei215, @clegarde I agree with you all, let's have a quick meeting over Zoom or MS Team to go over the changes, so that we are in sync and you get exactly what you are looking for. Can one of you setup a quick team meeting to go over the changes?
