### ISSUE TITLE
Deleting an Association

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#50]
The following error pops up when I try to delete an articulation, pair match, or refit. After I delete the element and press save, the error screen comes up. 

![removingarticulationerror](https://user-images.githubusercontent.com/7350474/36171433-4909285e-10c8-11e8-98f7-e5c2324ff860.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde, I need a little more information from you, try and give me a step by step approach on how to recreate the issue. I don't even know which project and skeletal element you were working with when you encountered this issue. 
It seems like you did not have sufficient privileges to do some action. But hard to tell.
Did you create the skeletal element that you were working with?

I think it might be easier to get on Skype and show me what exactly you did, meaning what steps you took to encounter the issue.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, I'm now convinced that this issue is a privileges and process issue. The SE that you were trying to edit/delete associations were created by @mei215 and were still in the process of being inventoried. 

I do think there is a bug in that you should not have been able to access that page associations page in edit mode. You should only be able to access that page in view only mode.

@fedamann, we may have to revisit the process and who can make changes until inventory of a SE in deemed complete and ready for review.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, one easy way to test my theory out is to create a new SE and then try to add/edit/delete of associations (pairs, articulations/refits) and see if that works. That would help confirm/reject if we are on the right track.

**Comment by clegarde** [comment]
Yesterday I was in the CoRA Demo Project, and I added an association to an element that was checked as "Inventoried" (not by me), but not checked as "Reviewed" yet. That was then the one I tried to delete and got the error.
I just added a new element in the CoRA Demo to test. I added two elements, then pair matched them (ABC 2018-001--B1-201). I then deleted the pair match, clicked save, and got the error message. So while in the inventorying process, I was not allowed to remove an association.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, that helps. I now have the steps to recreate the issue. Will give an update once we get it recreated and post an update.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, that really helped identify the issue. I have now fixed the issue, Please try it out and confirm. 
This issue has now been addressed via SachinPawaskarUNO/cora#415

**Comment by clegarde** [comment]
Tested and success! Thank you.
