### ISSUE TITLE
DNA module -> locking fields based on "Results Confidence"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#500]
When “Cancelled” is chosen, all fields are locked except for “Mito Haplogroup” and “MCC Date”. These could be locked as well.
![CoRA_DNA module issue](https://user-images.githubusercontent.com/7350474/63067379-53d01200-bed4-11e9-9e72-eccd5ecc4aac.png)

**Comment by fedamann** [comment]
@SachinPawaskarUNO move to TO2.1 development

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
Fixed. However, "Unable to Assign" now locks all fields. I think we should leave this one open, like "Reportable" because we would be able to fill in all fields but the "Sequence Number". We would have results for "Similar Sequence", "Mito Match Count", "Base Pairs", "Confirmed Regions", and "Mito Polymorphisms." This is reserved for those that we do get results, its just a limited range of loci.
![Screen Shot 2019-08-18 at 12 22 55 PM](https://user-images.githubusercontent.com/7350474/63228048-4f954480-c1b3-11e9-9eda-1eba5d06927a.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify
 "Unable to Assign" is now open, like "Reportable".

**Comment by clegarde** [comment]
GTG
