### ISSUE TITLE
DNA module -> "Disposition"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#501]
Based on the reports we get from AFDIL, these should be:
-Stored
-Consumed
-Returned
![CoRA_DNA module_Disposition](https://user-images.githubusercontent.com/7350474/63067443-a0b3e880-bed4-11e9-8096-4e597ac62372.png)

**Comment by fedamann** [comment]
@SachinPawaskarUNO move to TO2.1 development

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
