### ISSUE TITLE
Create DNA -> keep only top three fields

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#502]
Do not show the fields below "External Case #" on this screen. The fields below this would be completed later in the process.
![CoRA_Create DNA](https://user-images.githubusercontent.com/7350474/63067581-45cec100-bed5-11e9-8320-7c9b8c57759c.png)

**Comment by fedamann** [comment]
@SachinPawaskarUNO move to TO2.1 development

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
Looks good!
