### ISSUE TITLE
Update Uln_08 thresholds

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#504]
The thresholds for Uln_08 should be 
min: 10 
max: 40

![CoRA_Uln_08 thresholds](https://user-images.githubusercontent.com/7350474/63067815-62b7c400-bed6-11e9-95ea-dec38c54c4a3.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
