### ISSUE TITLE
Review -> Zones

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#505]
Can we have the zone image show in the Review Zones module? It would be helpful during review to have it.

![CoRA_Review Zones](https://user-images.githubusercontent.com/7350474/63067871-985cad00-bed6-11e9-975d-050f24b247fd.png)

**Comment by fedamann** [comment]
@SachinPawaskarUNO move to TO2.2+ development

**Comment by SachinPawaskarUNO** [comment]
@clegarde We discussed this briefly. Are we Ok with just adding the ability to pull out the right-side panel with help for Zones for the Bone being currently reviewed? If so, I would close this issue. I would like to go away from having zones/measurements images being displayed in two places that need to be kept in sync.

**Comment by clegarde** [comment]
I think the help in the side panel is sufficient for this. Closing.
