### ISSUE TITLE
Change "Inventoried By" to "Created By"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#51]
On Skeletal Element Advanced Reporting, change Inventoried By to Created By to better reflect the action it is reporting.
![advancedreport_createdby](https://user-images.githubusercontent.com/7350474/36222091-d1eff734-1185-11e8-9c2e-cf0937d57076.PNG)

**Comment by SachinPawaskarUNO** [comment]
This issue has now been addressed via SachinPawaskarUNO/cora#416
