### ISSUE TITLE
Typo/grammar issue in Age page

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#514]
Prior to age methods being added, the message reads as:
"No :relationship have been created/associated with this Specimen."
1. there should not be a colon before relationship
2. relationship > relationships (to match the verb "have")
3. Specimen should not be capitalized in the middle of a sentence
![image](https://user-images.githubusercontent.com/34662044/63289323-73748b00-c284-11e9-86f5-0cacd46f81e1.png)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman @clegarde Please verify.
