### ISSUE TITLE
McKern and Stewart (1957) Age Intervals for Scapula (Acromion) Incorrect

### ISSUE THREAD

**Issue by skorps** [spawaskar-cora/cora-docs#515]
The age intervals for the acromion of the scapula using McKern and Stewart (1957) are incorrect, and appear to correspond to the medial clavicle ages.

They should be:

0: 17-22
1: 18-19
2; 18-20
3: 17-21
4; 17+

![Scapula McKern and Stewart](https://user-images.githubusercontent.com/37446598/63293309-6f00a000-c28d-11e9-90cf-638a54145998.PNG)

**Comment by SachinPawaskarUNO** [comment]
@skorps @emilystreetman Please verify

**Comment by skorps** [comment]
Verified
