### ISSUE TITLE
McKern and Stewart (1957) should not be an option for Cervical Vertebra 1

### ISSUE THREAD

**Issue by skorps** [spawaskar-cora/cora-docs#516]
McKern and Stewart (1957) epiphyseal ring fusion (age method) should not be an option for Cervical Vertebra 1.  This bone does not have epiphyseal rings.

![C1 McKern and Stewart](https://user-images.githubusercontent.com/37446598/63296106-e6d1c900-c293-11e9-8a5b-e7eabdc989bb.PNG)

**Comment by SachinPawaskarUNO** [comment]
@skorps @emilystreetman Please verify

**Comment by skorps** [comment]
Verified
