### ISSUE TITLE
"Details" menu be available on all screens

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#518]
It would save time and be a bit more user friendly if the "Details" menu was available on all specimen screens.
![CoRA_Details](https://user-images.githubusercontent.com/7350474/63359266-0d464180-c332-11e9-82d7-820db21680cb.png)
For example, if you are editing/inventorying the element and add age methods, you have to navigate back to the "View Specimen" screen to then go to measurements. 
![CoRA_Details2](https://user-images.githubusercontent.com/7350474/63359343-3666d200-c332-11e9-8155-29d83c4224d8.png)
This is not a huge time issue, but when adding numerous elements each with multiple methods, it would save a considerable amount of time to be able to navigate from one module to the next.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
