### ISSUE TITLE
Change "Inventoried" check box to "Inventory Completed"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#52]
On Skeletal Element page, change the check box from "Inventoried" to "Inventory Completed" to clarify terminology. This will also be reflected on the Advanced Report page too, right?

![skeletalelement_inventoried](https://user-images.githubusercontent.com/7350474/36222195-2b603cc0-1186-11e8-8130-afcc8647232a.PNG)

**Comment by SachinPawaskarUNO** [comment]
This issue has now been addressed via SachinPawaskarUNO/cora#416 and SachinPawaskarUNO/cora#418. 
@clegarde can you please verify this.

**Comment by clegarde** [comment]
@SachinPawaskarUNO, Yep, GTG. This clears up the report searches for created vs. inventoried. And makes it clear under the skeletal element page to only check when done.

**Comment by SachinPawaskarUNO** [comment]
closing this issue, has been now been verified by @clegarde
