### ISSUE TITLE
Add Mincer as age method for third molars

### ISSUE THREAD

**Issue by Katie-East** [spawaskar-cora/cora-docs#520]
This is my first time inventorying teeth and I realized that there are no age methods for third molars. I am not sure if this has been discussed previously but I searched current tickets and could not find anything. I think it would be useful to have age estimation methods for third molars.

**Comment by clegarde** [comment]
"Mincer et al 1993" is an Age method currently under the Cranium, Maxilla, and Mandible. Please add as an option for the following "Skeletal Elements":
-> Tooth 1
-> Tooth 16
-> Tooth 17
-> Tooth 32

Method has the following options:
D - Crown complete
E - Root length < crown
F - Funnel-shaped root ends
G - Root apices open
H - Root apices closed

**Comment by SachinPawaskarUNO** [comment]
@clegarde @Katie-East Please verify

**Comment by Katie-East** [comment]
I verified that the method is present for all appropriate teeth and the appropriate options are available.
