### ISSUE TITLE
Automatically check "Measured" and "DNA Sampled" box - Skeletal Element Page

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#53]
After measurements have been added and click "save", automatically check the "Measured" box on the View Skeletal Element Page.
This could also be done for "DNA Sampled" once a DNA sample has been added and saved.

**Comment by SachinPawaskarUNO** [comment]
This has now been addressed via SachinPawaskarUNO/cora#419 & SachinPawaskarUNO/cora#420
@clegarde, can you please verify these.

**Comment by clegarde** [comment]
@SachinPawaskarUNO , Checked both, GTG.
