### ISSUE TITLE
Visibility of whether there are Assocations (Articulations, Pair-match, Refits) for an element

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#531]
It would be nice to be able to easily see if associations had been entered for an element.  Currently, this information is buried under multiple layers within each individual element.  This would be particularly helpful during data entry, as it is easy to lose track of where you are in entering associations within an accession.  Maybe have a check box on the first page that autopopulates once any association is made or a column visible in the search results that indicates whether or not associations are present for an element.  @fedamann @clegarde @SachinPawaskarUNO  
![Associations Add](https://user-images.githubusercontent.com/35308331/63462371-62f91780-c420-11e9-9b5f-71fa892f3bcc.JPG)
![Associations Add 2](https://user-images.githubusercontent.com/35308331/63462376-655b7180-c420-11e9-98e3-5b6625a516ca.JPG)

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed in CoRA v2.1.0
