### ISSUE TITLE
Maximum threshold for Cla_09 not high enough

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#533]
I have a clavicle with a 28mm Cla_09, but the threshold is 26 mm. I confirmed that I am doing this supplemental measurement correctly with @clegarde

**Comment by clegarde** [comment]
Looking at the reference data, this should be:
Min: 10mm
Max: 40mm

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman @clegarde Please verify

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman @clegarde Please verify

**Comment by clegarde** [comment]
GTG
