### ISSUE TITLE
Add indicator on DNA page if resampling could be helpful

### ISSUE THREAD

**Issue by skorps** [spawaskar-cora/cora-docs#534]
When a sample is inconclusive for DNA, the DNA summary report says (sometimes) whether or not resampling could be helpful.  Is there a way we could indicate this that would also be searchable - i.e., we could search for all inconclusive samples where resampling could be helpful?

**Comment by clegarde** [comment]
Maybe we could just add a dropdown (Yes or No) or a checkbox that is "Resampling recommended?"

**Comment by SachinPawaskarUNO** [comment]
@skorps Please verify

**Comment by clegarde** [comment]
GTG
