### ISSUE TITLE
"Individual Number Report" returning error

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#538]
Trying to do a full Individual Number Report to get the list of all and it's returning the following error:
![Individual Number Report Error](https://user-images.githubusercontent.com/7350474/63870203-1e6cff00-c97f-11e9-9b8d-191597d29f15.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @fedamann. This report has to pull a lot/most of the specimens in the case of the USS Oklahoma project, hence the error. I'm recommending that such long running reports be designed run as exports in the future.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please review

**Comment by clegarde** [comment]
GTG
