### ISSUE TITLE
Add "Lumbar vertebra 5/sacral vertebra 1" as another skeletal element

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#539]
Per discussion with @skorps @fedamann, please add the following skeletal element:

Lumbar vertebra 5/sacral vertebra 1

This can be used when there are vertebral shifts or issues determining L5 vs S1. Please allow articulations with:

Lumbar vertebra 4
Lumbar vertebra 4/5
Lumbar vertebra 5
Sacrum
Sacral vertebra 1
Sacral vertebra 2

**Comment by SachinPawaskarUNO** [comment]
@clegarde @fedamann Please verify

**Comment by clegarde** [comment]
GTG
