### ISSUE TITLE
Allow users who are part of the project team to view and edit SE

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#54]
Based on conversations during CoRA SCRUM today (02/14/2018) with DPAA team @fedamann et. al, it was decided to allow users who are part of the project team to view and edit Skeletal Elements that belong to that project.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#422
@clegarde, can you verify this for me. You should now be able to view/edit SE's created by @mei215 in the Polesti project

**Comment by clegarde** [comment]
@SachinPawaskarUNO, Yep, I can view/edit in Ploesti project.

**Comment by SachinPawaskarUNO** [comment]
Closing this issue. It has now been verified by @clegarde
