### ISSUE TITLE
Tooth Type in Inventory

### ISSUE THREAD

**Issue by JKJuarez** [spawaskar-cora/cora-docs#540]
Hi Everyone,
I'm not sure if this has already been addressed at a meeting I didn't attend but it's an issue we have noticed in CAB that we think would be helpful for us.

Often the dentists nominate a tooth but don't assign a number but DO assign a type (example: canine Sample 01A).  In CoRA right now we are only able to enter "tooth" and then add in the DNA sample number.  Could the tooth types be added, please?  At minimum: Canine/Molar/Premolar/Incisor.  

Would be nice to have Maxillary *tooth type* and Mandibular *tooth type* , though, also.

Thank you from the Cab Team

**Comment by clegarde** [comment]
I think this could be good to add.

OR, we create "zones" for teeth that would be these categories. Then you could do a zone search that would give you all incisors (numbered or not) and/or canines, etc. So we would keep just "Tooth" but then you could mark the zone as "Incisor", "Canine", etc.

**Comment by JKJuarez** [comment]
I think zones *could* work, but as it is set up now, putting in zones is an extra few steps outside of the initial inventory input.  If we could add the zones to the initial inventory page that would be great!  

However, in terms of this request, even if we could just get the options I listed above, that would help us out because our project is so commingled that, often, several teeth get nominated from each of our accessions.  Zones may be the way to go if we are able to capture all of that information though...because you've got a good point about searching for "canine" and seeing all of them whether they are numbered or not.  I'm just trying to streamline our input process a little and still be able to capture as much as possible.

Thanks,
Cab Team

**Comment by SachinPawaskarUNO** [comment]
@JKJuarez @clegarde Currently we have Tooth, Mandibular Tooth and Maxillary Tooth. Along with these we also have Tooth 1 - Tooth 32. Does this address some or part of the issue?

@JKJuarez and @clegarde This should be discussed by the anthropologists participating in an internal dental module review. @clegarde is going to set this up for folks in Omaha and Hawaii to come up with a comprehensive list of items to work on from a dental perspective.

**Comment by JKJuarez** [comment]
@SachinPawaskarUNO Unfortunately, due to the nature of our project,  we lose a lot of information with the options that available currently.  We will often receive teeth/tags from the dentists labeled only by type (ex. canine).  Since it hasn't been designated maxillary or mandibular, right now it just gets entered as "tooth".  When we do get, for example, "maxillary canine", we lose the type because all we can say is "maxillary tooth".  I've RSVPd to the dental module review discussion sent out by @clegarde 

Thank you, Cabanatuan Team

**Comment by JKJuarez** [comment]
@SachinPawaskarUNO Unfortunately, due to the nature of our project, we lose a lot of information with the options that are available currently. We will often receive teeth/tags from the dentists labeled only by type (ex. canine). Since it hasn't been designated maxillary or mandibular, right now it just gets entered as "tooth". When we do get, for example, "maxillary canine", we lose the type because all we can say is "maxillary tooth". I've RSVPd to the dental module review discussion sent out by @clegarde

Thank you, Cabanatuan Team

**Comment by SachinPawaskarUNO** [comment]
@JKJuarez @clegarde Please verify

**Comment by JKJuarez** [comment]
@SachinPawaskarUNO  I didn't have a new inventory to add but I checked an existing inventory entry under edit mode.  As far as I can tell, I was able to see options for: incisor, premolar, molar, canine, anterior tooth, posterior tooth as well as options for crown and root in the zones.  While I go through and clean-up some of our tooth entries, I can let you know if I found any bugs.   Is there anything specific that you needed for us to do or check?

Thanks, 
JKJ

**Comment by SachinPawaskarUNO** [comment]
@JKJuarez Thanks for verifying that the new options for: incisor, premolar, molar, canine, anterior tooth, posterior tooth show up. At this point you should close the ticket. 
If some issue/bug comes up later related to these you can create a new issue and relate it back to this issue.
