### ISSUE TITLE
Add mandible/maxilla/cranium to Dentition Groups for articulation purposes

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#541]
Add mandible/maxilla/cranium to dentition bone groups so that it can automatically be articulated with the dentition. *Allows for you to choose the bone if you want to include it here - delete it if not.*

Add the following skeletal element to "Mandibular dentition":
-> Mandible (articulates with Tooth 17-32)

Add the following skeletal elements to "Maxillary dentition":
-> Left maxilla (articulates with Tooth 9-16)
-> Right maxilla (articulates with Tooth 1-8)
-> Cranium (articulates with Tooth 1-16)

**Comment by SachinPawaskarUNO** [comment]
@clegarde please verify

**Comment by clegarde** [comment]
Confirmed that mandible/maxilla/cranium are in appropriate groups. Will try to check articulations in CoRA-cat later.
