### ISSUE TITLE
3D Scanned - Inventory Checkbox

### ISSUE THREAD

**Issue by jjlynch2** [spawaskar-cora/cora-docs#542]
Similar to 'CT Scanned' and 'X-ray Scanned', perhaps having a '3D Scanned' checkbox on the inventory screen would be a good feature for future data collection?

**Comment by SachinPawaskarUNO** [comment]
@jjlynch2 Please verify

**Comment by SachinPawaskarUNO** [comment]
@jjlynch2 Please verify

**Comment by clegarde** [comment]
GTG
