### ISSUE TITLE
Create zones 1 & 2 for teeth? Crown vs root?

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#544]
Currently we do not have zones for teeth, but it could be useful to know if you have an "incomplete" tooth whether you have the crown or root present.

**Comment by fedamann** [comment]
Good idea.  Mark it as Dental module build out

**Comment by SachinPawaskarUNO** [comment]
@clegarde @fedamann Please verify

**Comment by clegarde** [comment]
Zones present in CoRA. If the tooth is marked "Complete", will all zones be checked?

**Comment by SachinPawaskarUNO** [comment]
@clegarde You should try it by creating a new tooth and select complete and then verify if the zones are being created.  Try it out in CAT, if you do not want to create one in PROD.

**Comment by clegarde** [comment]
Tested in CAT. GTG
