### ISSUE TITLE
Ability to peer review mass (of hair, tissue, etc.)

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#545]
Currently, there is no option on the review page to peer review the mass of non-osseous remains associated with a case.  Also, in a case where the analyst has not taken/recorded the mass, the peer reviewer cannot suggest the analyst to do so.  Can we add "mass" under the "measurements" tab for hair, tissue, etc.?

**Comment by clegarde** [comment]
Suggested to go under "General" tab with Count under #537. @nyukyi, add your comment there if you'd prefer it under a different section. I'm going to close this ticket.
