### ISSUE TITLE
"Reviewed" checkbox error

### ISSUE THREAD

**Issue by nyukyi** [spawaskar-cora/cora-docs#546]
When I clicked on the checkbox for "Reviewed" for each element after I was done reviewing, it gave me an error message (see below).  This is my second time clicking the "Reviewed" checkbox.  I had no problems the first time round.  I unfortunately clicked on the "Reviewed" checkbox before the analyst clicked on the "Inventory Completed" checkbox, so now I am going through each element again to click on the "Reviewed" checkbox (I'm on my second round of reviews).

![Untitled](https://user-images.githubusercontent.com/34749060/64559929-0b5a1780-d30d-11e9-9e08-23116b7c9aa6.png)

**Comment by nyukyi** [comment]
Sorry, I forgot to add that, despite the error message, the clicked checkbox saves properly.  It's just that it gives me this error message.

**Comment by cbrown311** [comment]
I also have been getting the same error for the past 2 hours while doing an inventory review.  Like Nandar, checking the "Reviewed" check box does get saved, even with the error message.

**Comment by nyukyi** [comment]
I tried it again yesterday and today, and it seems to be working ok now.  But I will leave this ticket up just in case someone else experiences this again.

**Comment by SachinPawaskarUNO** [comment]
This was related to AWS Redis Server (Queues/Jobs) not being available due to an upgrade. We can close this issue.

**Comment by SachinPawaskarUNO** [comment]
This was related to AWS Redis Server (Queues/Jobs) not being available due to an upgrade. We can close this issue.
