### ISSUE TITLE
Zones absent from Cranium list

### ISSUE THREAD

**Issue by tlvandeest** [spawaskar-cora/cora-docs#559]
Zones 16 - 23 are not present on the list for the cranium and thus, cannot be used. Help window also does not depict all zones (e.g., Zone 21) labeled and visible in the Cranium Zones images.  See image below. @fedamann @clegarde @SachinPawaskarUNO 

![CORA CRANIUM ZONES MISSING](https://user-images.githubusercontent.com/35308331/65996993-21677d80-e45e-11e9-9bbd-caad0afb29d5.JPG)

**Comment by clegarde** [comment]
21 should be Vomer - will add to md.

**Comment by clegarde** [comment]
Need to add the following:
16 - Left lacrimal bone
17 - Right lacrimal bone
18 - Left palatine bone
19 - Right palatine bone
20 - Ethmoid
21 - Vomer 
22 - Left inferior nasal concha (not depicted)
23 - Right inferior nasal concha (not depicted)

**Comment by SachinPawaskarUNO** [comment]
@tlvandeest @clegarde Please verify

**Comment by clegarde** [comment]
GTG
