### ISSUE TITLE
Change "DNAs" to "DNA"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#56]
Plural for DNA is just DNA, no "s."

![dna](https://user-images.githubusercontent.com/7350474/36266836-15f075aa-1238-11e8-9184-e59ee553ffec.PNG)

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed via SachinPawaskarUNO/cora#428.
@clegarde Please verify and close out if good to go.

**Comment by clegarde** [comment]
@SachinPawaskarUNO, "DNAs" is still showing.

**Comment by SachinPawaskarUNO** [comment]
@clegarde, Please try again. 
It was late last night and I did not refresh the database because I did not want you to loose your data.
Go ahead and give it a try now and close the issue if its working.

**Comment by clegarde** [comment]
@SachinPawaskarUNO, Looks good!
