### ISSUE TITLE
Add auto Pair Match for bone groups with left and right

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#560]
Like we have articulations applied to skeletal elements within bone groups, can we now add pair matching since we have bone groups with left and right? This would be a time saver.
Spoke about this briefly with @SachinPawaskarUNO.

**Comment by clegarde** [comment]
For example: Pelvis bone group includes left and right os coxa.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
Tested Pelvic girdle in PROD - GTG
