### ISSUE TITLE
Problem with Zones for T3

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#563]
![1](https://user-images.githubusercontent.com/33871387/67015082-945a3080-f0bb-11e9-9bda-b4f4c087cb14.JPG)
 Zone 1 for T3 should be "Body" not "Spinous Process."

**Comment by clegarde** [comment]
Description for Zone 1 = Body

**Comment by SachinPawaskarUNO** [comment]
@clegarde @mei215 Please verify

**Comment by mei215** [comment]
verified it is fixed. thanks
