### ISSUE TITLE
Cannot update specimen as "Reviewed"

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#565]
Returning an error when trying to mark a specimen as "Reviewed" and click Save. This was working fine last week @SachinPawaskarUNO. 

![1](https://user-images.githubusercontent.com/7350474/67221174-a1935a00-f3f0-11e9-8b3c-39a2df1c103a.JPG)

Notified by @emilystreetman and @mei215.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
