### ISSUE TITLE
Review - Don't show modules if there is no possible data

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#568]
Don't show modules if there is no possible data. For example, the coccyx does not have any possible measurements in CoRA. It would save time during review if those weren't visible (see below image). This issue is related to #564 

![image](https://user-images.githubusercontent.com/19599773/67528991-82aaf700-f680-11e9-84e8-1ada4b9cac99.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
