### ISSUE TITLE
Specimen Review - don't collapse Age, Sex, Ancestry if there is data in there

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#569]
Specimen Review - don't collapse Age, Sex, Ancestry if there is data in there. The default is that each one is collapsed (see image below). During the review, it adds more steps if you have to uncollapse each one just to check if there is data there. 
related to #564

![Bio Profile_Review](https://user-images.githubusercontent.com/7350474/67131641-14bb8700-f1cb-11e9-923d-f35748ed95f2.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by clegarde** [comment]
GTG
