### ISSUE TITLE
Mitochondrial DNA Report: Two Issues with the Results

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#571]
The "Mito Request Date" column is blank, even when dates have been entered for specific elements. 

Also, "Sequence Subgroup" in the Mitochondrial DNA Report seems to be pulling sequences from all projects, not just the project the user is working in.

![1](https://user-images.githubusercontent.com/33871387/67878042-ae0e6580-fb08-11e9-83f3-a7c47fc70afd.JPG)

**Comment by clegarde** [comment]
The list for "Sequence Number" and "Sequence Subgroup" have numbers/data that are not in the USS Oklahoma Project (or Ploesti). If I'm in the USS Oklahoma Project and try to search one of these (ex: 675), it does not yield any data. These look like they might be KWP sequences and subgroups.
![DNA Report_Sequence](https://user-images.githubusercontent.com/7350474/67888429-12d2bb80-fb1b-11e9-876b-d26de14adeae.png)
![DNA Report_Subgroup](https://user-images.githubusercontent.com/7350474/67888516-3f86d300-fb1b-11e9-9ffa-4bb48d25f475.png)

**Comment by SachinPawaskarUNO** [comment]
@mei215 @clegarde Please verify

**Comment by mei215** [comment]
verified and closed
