### ISSUE TITLE
Y and Auto Reports Please

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#573]
Similar to the "mtDNA Report, I would like to be able to search by what has been sent for Y and auto. Thanks

**Comment by clegarde** [comment]
Based on "Results Status" field.

**Comment by clegarde** [comment]
I just wanted to highlight this request for a report by Y or auto. For Project Leads, we have to provide a list of "Pending" requests on a fairly regular basis. This currently cannot be compiled from CoRA, but would save us a lot of time and prevent us from needing to use additional spreadsheets, which we have to do now. It is very quick and easy to do by mito in CoRA, so a similar report for Y and auto would be great!
@SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
@clegarde This report is on the release roadmap planned out and will be available in one of the upcoming releases.

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed in CoRA v2.1.0
