### ISSUE TITLE
DNA Sample Number - allow "."

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#578]
Moving forward with new projects, our DNA sample numbers will reflect the LIMS subexhibit number (ex: 1.1.1) which will need to allow for the "."

![CoRA_DNA Sample Number](https://user-images.githubusercontent.com/7350474/70183740-ee36aa00-16ab-11ea-8b51-f1a8413c4463.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please verify

**Comment by SachinPawaskarUNO** [comment]
This has been completed
