### ISSUE TITLE
New DNA report parameters

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#586]
With new fields in DNA, we now would like to have the ability to run reports based on date.

For example, we often need to determine:
1. How many DNA tests were **requested** between a given date range? And which of these have results (i.e, "Results Status")?
2. How many DNA tests results were **received** between a given date range? And which of these have results?

It would be nice to be able to obtain this data for all DNA test types (mt, Y, and auto) OR being able to search for only Y-str tests received in 2019, for example.

Important reports for project leads @mei215 @skorps @cbrown311 @TarawaProject @veronicak7 @lfreas

**Comment by TarawaProject** [comment]
what you demonstrated during the scrum provides most of what the Project Leads are required to report on.  We need to be able to do the same for Y and auto testing as well as distinguish between NGS and Sanger sequencing.

**Comment by mei215** [comment]
#573

**Comment by SachinPawaskarUNO** [comment]
This issue has been addressed in CoRA v2.1.0
