### ISSUE TITLE
Create new element error

### ISSUE THREAD

**Issue by aschaefer1** [spawaskar-cora/cora-docs#588]
I get an error saying "The remains status field is required." when I try to create a new element.  
![CreateNewElement Error](https://user-images.githubusercontent.com/38509714/71912555-55c49700-313b-11ea-8986-65be93eb76d8.PNG)

**Comment by SachinPawaskarUNO** [comment]
@aschaefer1 Please verify

**Comment by aschaefer1** [comment]
Problem solved!
