### ISSUE TITLE
Set thresholds for measurements to reduce error

### ISSUE THREAD

**Issue by fedamann** [spawaskar-cora/cora-docs#60]
Create upper and lower limits for individual measurements that provide the user with a warning when a measurement is outside normal distribution

**Comment by SachinPawaskarUNO** [comment]
@fedamann and @clegarde At some point in time we need to get threshold values for each measurement.

**Comment by SachinPawaskarUNO** [comment]
@fedamann, We need to have someone tasked with getting threshold values for each measurement.

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy @rpernst Here is the limits file 
[limits.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1975189/limits.xlsx)

**Comment by SachinPawaskarUNO** [comment]
@fedamann Here are Bone Measurements that we are missing limits for.

Cal_03 Minimum Height Distal to Articular Facets
Cal_04 Posterior Length
Cal_05 Maximum Length of the Calcaneus
Cra_28 Zygoorbitale Breadth (zo-zo, ZOB)
Fem_12 Maximum Anterio-posterior Length of the Lateral Condyle
Fem_13 Maximum Anterio-posterior Length of the Medial Condyle
Fem_18 Upper Breadth of Femur
Fem_19 Lateral Condyle Height
Osc_03 Pubis Length
Osc_04 Ischium Length
Osc_06 Maximum Pubis Length (XPL)
Osc_07 Minimum Pubis Length (WPL)
Osc_08 Ischial Length (ISL)
Osc_09 Minimum Ischial Length (WISL)
Osc_10 Maximum Ischiopubic Ramus Length (XIRL)
Osc_11 Anterior Superior Iliac Spine to Symphysion (ASISS)
Osc_12 Maximum Posterior Iliac Spine to Symphysion (PSISS)
Osc_13 Minimum Apical Border to Symphysion (WAS)
Sac_04 Anterior-Posterior Diameter of Sacral Segment 1
Sac_05 Maximum Breadth with the Osteometric Board
Tal_03 Maximum Length
Tib_13 Biarticular Breadth
Tib_14 Medial Condyle Articular Width
Tib_15 Medial Condyle Articular Length
Tib_16 Lateral Condyle Articular Length

**Comment by SachinPawaskarUNO** [comment]
See missing measurement threshold data in spreadsheet below provided by @fedamann and @aschaefer1 

[MissingCoRAMeasurments_ADS.XLSX](https://github.com/spawaskar-cora/cora-docs/files/1992240/MissingCoRAMeasurments_ADS.XLSX)

**Comment by SachinPawaskarUNO** [comment]
@nmcelroy to update both repos and new version will be deployed this weekend by @SachinPawaskarUNO

**Comment by SachinPawaskarUNO** [comment]
This work is complete and will be available with the next release of CoRA

**Comment by SachinPawaskarUNO** [comment]
@fedamann and @emilystreetman Can we please verify this issue?

**Comment by emilystreetman** [comment]
@skindsc1 has offered to take a look at this ticket in conjunction with #239 which she opened as a threshold error ticket

**Comment by SachinPawaskarUNO** [comment]
@fedamann Please verify

**Comment by fedamann** [comment]
Threshold limits set. Verified and closed this issue. Correct values for thresholds are assessed under #167
