### ISSUE TITLE
Not allowing letters and dashes for Sequence Number (Y-STR and auto)

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#616]
With the new version, the "Y-STR Sequence Number" field won't allow letters or dashes. The OK Project has been entering this data like the following:
170-2 or 206-C2
But are now getting the following error message:
"The ystr sequence number must be a number."

If there is a reason for this change, please let us know. It affects our current (and past) data entry.

I just tried this with DNA Sample Number 1987A (CIL 2003-116:G-20:X-258G:901 :: Os coxa-Right).

In PROD, using Edge.

**Comment by SachinPawaskarUNO** [comment]
@clegarde A hot fix for this has been applied. Please verify

**Comment by clegarde** [comment]
GTG
