### ISSUE TITLE
DNA Module: "Special Characters Not Allowed"

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#621]
PROD environment

When updating in the DNA Module, in the "Confirmed Regions" and "Mito polymorphisms" fields, I receive errors when trying to save that these fields can only contain letters, numbers, dashes, and spaces.

However, all of that data was previously entered with commas separating loci and some loci include periods (.).  Please make commas and periods acceptable characters again in these fields.  

  Right now I cannot update.

**Comment by SachinPawaskarUNO** [comment]
@mei215 Please verify and close if fixed.

**Comment by mei215** [comment]
The "Mito polymorphisms" field" appears fixed.  The "Confirmed Regions" field still says "The mito confirmed regions format is invalid" and "Special characters not allowed."

**Comment by SachinPawaskarUNO** [comment]
Updated Regex validation
@mei215 Please try it now. Please verify and close if fixed.

**Comment by mei215** [comment]
Both the "Confirmed Regions" and "Mito polymorphisms" fields appear to be fixed now because they no longer show up with red errors when the data is entered. However, the data still will not SAVE because at the top of the page in red it says, "Special characters not allowed" only.

**Comment by SachinPawaskarUNO** [comment]
@mei215 Can you tell me what special characters are used in these fields, I'm aware of - , . and space
Are there others?

**Comment by mei215** [comment]
I think those are all of the special characters I use.

Right now, the data in those two blocks are :

16069T,16126C,73G,185A,263G,295T,315.1C

and

16024-16391,35-369

So I'm not sure what special characters are triggering the error?

**Comment by SachinPawaskarUNO** [comment]
@mei215 That is interesting, not sure right now what is going on. I did try this on cat and it seems to work with the examples you have given above, see screenshot below. Can you give me what specimen it is (Composite Key) and DNA Sample Number, it would be since to have a screenshot, but I'm assuming you are still unable to attach one.

![image](https://user-images.githubusercontent.com/19599773/78155521-3029ef80-7403-11ea-8e80-1b88b0db383d.png)

**Comment by mei215** [comment]
Unfortunately, I cannot add screenshots. 

I just tried to add data to CIL 2017-310:X-5184::802 (Sample 70A), CIL 2017-310:X-5082::201 (sample 79A), and CIL 2017-310:X-5264::401 (Sample 66A), and the DNA Updates were Successful!

I continue to have problems specifically with CIL 2017-310:X-5082::401 (Sample 82A). 

I now think the problem may be the "/" symbol that is used to enter Y loci because I removed that and it saved. 

So maybe please just add the "/" as an acceptable character and hopefully that will be all the changes that are needed? Thanks

**Comment by SachinPawaskarUNO** [comment]
@mei215 I have updated Regex validation to include /. Please try it now and close if verified as fixed.

**Comment by mei215** [comment]
verified and closed
