### ISSUE TITLE
Follow through screen not producing

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#627]
The follow through screen is not always producing in CoRA PROD when trying to advance to the next page after entering information or selecting a button. The website appears as though it is loading but when it stops loading, the page does not change; this is particularly troublesome when entering elements, as when you then refresh the page to get the page to reload, your element has already been created and you must search for your element in the search bar in order to finish the analysis or inventory of it. Is anyone else having this problem. I am working in edge (not the new updated edge that came with the new windows update).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 42.17134.1098.0

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Are you able to attach any images? BTW, Is this happening when working from home or from DPAA office?
I'm assuming this is on the New Specimen screen and not the New Specimen Bone Group screen (right?). If this is happening only sometimes then I think it might be a network issue. Can you confirm that this works as expected sometimes? and occasionally fails to take you to the follow on screen.

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO There aren't really any images to attach, all it would show is the same page twice. It happens on every page, not just the new specimen page. I've had it happen on the login screen, the dashboard and the specimen entry page. It does work as expected sometimes, it's just every few page loads or so it glitches. I remember it happening sometimes when I was in the lab as well, but I didn't really think anything of it, but now that I have a lot of specimens to enter I am noticing it happening a lot more.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer So right now it is happening from home? Is that correct?

**Comment by CTegtmeyer** [comment]
Correct

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer I see that several people are working from home, but none of them has reported a problem like this. I'm wondering of this has to do with your network connectivity? Have you tried reseting your wireless router? I'm also wondering what bandwidth you have with your ISP (Internet Service Provider) provider. I'm including @clegarde on this email to see if she has seen issues like this in Omaha as well.

**Comment by CTegtmeyer** [comment]
Not to sound glib, but I run MMORPGs off my bandwidth just fine with little to no issues on a regular basis. I do not believe it is a bandwidth issue. I have a 200mbps internet speed with my ISP. Also, as I mentioned, I have had this issue at the lab as well.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer I'm just going through and ruling out possibilities. I think based on what you have said that you have a 200 mbps ISP service. I think we can rule that out as as issue. However we still need to figure out if others are having this issue or is it isolated to your machine. Is this the same machine/laptop you use at work? Have you tried it from a different machine? I'm more than happy to do a Skype session with you to triage other possibilities. Let me know if you would like to do a quick Skype.

**Comment by CTegtmeyer** [comment]
Haha, they Mass Multiplayer Online Role Playing Games.
Yes, this is the same machine I use at work. I will try my personal laptop, but I have the updated version of edge on that one, so I might not be able to recreate the issue if it is restricted to a version issue like so many other things.
I am free to skype later today. I have a meeting at 9:00, but I am free after that.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Tell you how much I know about gaming :-)
Yes, Lets Skype, just call me on my Skype ID: spawaskar@unomaha.edu

**Comment by CTegtmeyer** [comment]
@SachinPawaskarUNO I just tried it on my personal laptop and it worked just fine. This laptop has the newest version of edge that came out with the new Windows 10 update: 83.0.478.58 (which shows you just how far behind DPAA is in their edge version). So I wonder if it is a machine issue or another edge issue.

I will skype you after my meeting at 9.

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer Thanks for trying it from a different laptop. This confirms my suspicion that it is isolated to your DPAA issued laptop. It also shows that more needs to be done by DPAA IT to get you to the current versions of both OS and Edge versions. Since we have not heard about this from others my suspicion is that it is isolated to your machine for now.
I'll wait for you to call on Skyoe after your 9:00 am meeting.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by SachinPawaskarUNO** [comment]
fixed with the CDN release CoRA 2.0
