### ISSUE TITLE
Rougé-Maillart (2009) acetabulum+auricular surface method for age estimation

### ISSUE THREAD

**Issue by LucieBiehlerGomez** [spawaskar-cora/cora-docs#629]
Would it be possible to add the Rougé-Maillart et al (2009) method for age estimation based on the scoring of degenerative features of the acetabulum and auricular surface? The method is particularly useful for the elderly, when Lovejoy (1985) and Suchey-Brooks (1990) are less reliable or give too wide ranges (such as ">60"). 

Here is the reference: Rougé-Maillart, C., Vielle, B., Jousset, N., Chappard, D., Telmon, N. and Cunha, E., 2009. Development of a method to estimate skeletal age at death in adults using the acetabulum and the auricular surface on a Portuguese population. Forensic science international, 188(1-3), pp.91-95.

The method consists in the scoring of degenerative changes of the auricular surface: 5 criteria, score up to 7; and acetabulum: 3 criteria, score up to 5. 
<img width="963" alt="Capture d’écran 2020-07-23 à 12 26 49" src="https://user-images.githubusercontent.com/59883510/88276786-eaf63a00-ccdf-11ea-84c6-c317f8add6fb.png">
<img width="959" alt="Capture d’écran 2020-07-23 à 12 26 58" src="https://user-images.githubusercontent.com/59883510/88276799-f0538480-ccdf-11ea-801f-5ae974b5f11d.png">

The total sum of the scores per criteria for both auricular surface and acetabulum corresponds to a certain category (defined in the table below) that may be correlated to 10-year age groups with various probabilities. The correlated group with the highest probability (grey-colored cells) is generally the result provided. 
<img width="600" alt="Capture d’écran 2020-07-23 à 12 27 27" src="https://user-images.githubusercontent.com/59883510/88277119-7a9be880-cce0-11ea-9905-3489988ad343.png">

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez This is very useful. We will definitely add this method to CoRA. I do need some clarifications, which we can discuss tomorrow in our Friday calls.

**Comment by fedamann** [comment]
@LucieBiehlerGomez can you attach the article, please?  Thank you in advance

**Comment by LucieBiehlerGomez** [comment]
@fedamann Absolutely! Here it is.
[Rougé-Maillart et al. - 2009 - Development of a method to estimate skeletal age at death in adults using the acetabulum and the auricul.pdf](https://github.com/spawaskar-cora/cora-docs/files/4968468/Rouge-Maillart.et.al.-.2009.-.Development.of.a.method.to.estimate.skeletal.age.at.death.in.adults.using.the.acetabulum.and.the.auricul.pdf)

**Comment by fedamann** [comment]
@LucieBiehlerGomez thank you!  I'll pull data into a structure and send it back so you can see what we need for adding in new methods.

**Comment by fedamann** [comment]
@LucieBiehlerGomez I am curious how you report results based on this method.  If you had a composite score of 17 would you report (1) the min and max age observed per Overall Score Category (e.g., III -> 30-68 years of age); or (2) the 35-44 age interval associated with highest probability for Category III (0.527)?  Or some other combination of results?

**Comment by LucieBiehlerGomez** [comment]
@fedamann Actually, I would put both. While precision in age estimation is the ultimate goal, accuracy is more important. I would write first that this method gives a high probability (0.527) of an age range 35-44 but to increase accuracy, a larger age range (30-68) should be considered.

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez Please find attached the spreadsheet created by @fedamann for new methods request. After filling out the required information, simply attach the updated excel file to this ticket/issue.

[CoRA_New Methods Request.xlsx](https://github.com/spawaskar-cora/cora-docs/files/5007828/CoRA_New.Methods.Request.xlsx)

**Comment by LucieBiehlerGomez** [comment]
@SachinPawaskarUNO The excel sheet is correct, except there are no Score Intervals, a sum of the scores for each feature is necessary to compute the age interval.

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez Can you please verify this for me in CAT environment? Once you verify it in working as expected in CAT I will push it to PROD.

**Comment by LucieBiehlerGomez** [comment]
@SachinPawaskarUNO I can't see the method appear in the CAT environment when I want to do the age estimation of an Os Coxa nor do I see it in the lists of age methods on the CORA Docs.

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez Can you please try this again and verify this for me in CAT environment? It should be there now. 
For the documentation, this is where you @LucieBiehlerGomez will add the documentation to cora-docs repo. I will show you how.

**Comment by LucieBiehlerGomez** [comment]
@SachinPawaskarUNO Now it's working, unfortunately it's not complete. Two sections should be evaluated: the auricular surface and the acetabulum as such:

**Auricular surface**
_Transverse organization_: with a score from 1 to 7
_Surface texture_: score from 1 to 5
_Porosity_: score from 1 to 5
_Apical activity_: score from 1 to 3

**Acetabulum**
_Rim_: score from 1 to 5
_Fossa_: score from 1 to 4
_Apical activity_: score from 1 to 3

So far, I can only see transverse organization and rim and the location (auricular surface or acetabulum) is not specified.
Then to reach an age estimation, we must calculate the total score of these 7 values. This score will correspond to a certain category (I, II, III, IV etc). By looking in the final table (Table 7 in the original article and inserted above) at the highest probability of each age range for that specific category, we obtain the final age estimation.

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez Maybe we can get on a quick zoom call to sort this out. Are you available now?

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez I have made the necessary changes in CAT based on our discussion today. So, Please take a look at it in CAT. I have also accepted your pull request as well, so you will see the new method documentation updated as well.
Let me know, once you take a look and verify that every thing looks good, I will push the changes in to PROD.

**Comment by LucieBiehlerGomez** [comment]
@SachinPawaskarUNO Everything works perfectly!

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez I have pushed these changes to PROD. Please verify it in PROD and close issue if verified.
