### ISSUE TITLE
Zone search finding zones that are not present

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#63]
When running a zone search for the head of the right humerus (i.e., zone 2/caput) the list is including humeri that have no head/caput/zone 2.  I found that this happens with other zones too but there are also bones on the list that do have the zone that has been requested.  (Also, note that the search field says "Skeletal Bone" instead of "Skeletal Element" or "Bone")  

![image](https://user-images.githubusercontent.com/21186879/37097352-d47f642e-21e0-11e8-9ae0-292aef2cbab8.png)

For example, I chose the first humerus on the list and it shows that the head/caput/zone 2 is not present but it was included in the list.  

![image](https://user-images.githubusercontent.com/21186879/37097209-7450ea46-21e0-11e8-93ff-e6e85623c3b0.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
When doing a zone search, you should be able to ask for it to return an inclusive list. For example, if I search for zones 2 and 11 on the humerus, I want it to return a list of elements that ONLY have those two zones, not a list of elements that have that zone. It is set up as an "or" option, but it should give an "and" output. Zones 2 AND 11. Or it should be an option to search one way or the other.

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 Can you please review this issue and close if fixed
