### ISSUE TITLE
Add new taphonomy  features to CoRA - used by University of Milano

### ISSUE THREAD

**Issue by Mirkomattia** [spawaskar-cora/cora-docs#632]
Could you add this new taphonomy categories:

Biological – aquatic scavengers large (e.g: sharks...)
Biological – aquatic scavengers small (e.g.: arthropods)

**Comment by SachinPawaskarUNO** [comment]
@Mirkomattia Please verify this in PROD and close this issue if complete.

**Comment by Mirkomattia** [comment]
Great! Thanks Sachin!
