### ISSUE TITLE
CoRA Prod is Unresponsive

### ISSUE THREAD

**Issue by skorps** [spawaskar-cora/cora-docs#638]
**Describe the bug**
The main home page loads, but all buttons are unresponsive.  I can't search, add new bones, go to my profile, etc.  There is no error - just nothing happens.

**What is the environment**
PROD

**To Reproduce**
1. Go to CoRA
2. Try to do anything else in CoRA
3. Nothing happens (no error)

**Expected behavior**
Clicking on buttons will take you to the pages you intend to go to.

**Screenshots**
- Not able to add any.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Don't know

**Additional context**
This is happening while plugged into the network at work, as well as at home through VPN.  Internet/network is working fine otherwise.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer

Another update and potential fix:  I tried CoRA again from my work laptop at home, connected to WiFi but not VPN.  It worked.  I then re-connected to the VPN and it still worked.  I will try from the lab when I'm back in on Wednesday.  I emailed Caryn and it is working for her too.

**Comment by skorps** [comment]
@SachinPawaskarUNO @fedamann @CTegtmeyer 

Update and potential temporary fix:  I loaded CoRA on my work laptop at home connected to WiFi but not VPN.  It worked fine (and I could see buttons!).  I reconnected to VPN, and CoRA still worked (but I lost the buttons again).  I'll try again when I'm back at the lab on Wednesday and update with any new info.

**Comment by SachinPawaskarUNO** [comment]
@skorps Thanks for sharing this.
@fedamann May want to share this workaround with others in Omaha who are experiencing this issue.

**Comment by skorps** [comment]
@SachinPawaskarUNO  @fedamann @CTegtmeyer  This is definitely only a temporary fix.  I've lost functionality again a couple times while at work, where there is no way to restore it.  It seems to last for most of a work day.

**Comment by SachinPawaskarUNO** [comment]
fixed with the CDN release CoRA 2.0
