### ISSUE TITLE
Ability to search for a single zone

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#64]
Within the "Zone Search" function, is it possible to search for a single zone?  For example, if I want to find all of the femora that are _only_ represented by the head (caput/zone 4) I can search for that zone but the search returns femora that _have_ the zone, not just the ones that are _only_ that zone.

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue has been addressed with a new release. Please verify and close issue if verified.
