### ISSUE TITLE
New Pathology Feature

### ISSUE THREAD

**Issue by LucieBiehlerGomez** [spawaskar-cora/cora-docs#643]
Would it be possible to add a new pathology feature? "Deformative - Bending" 
What do you think?

**Comment by LucieBiehlerGomez** [comment]
@fedamann @SachinPawaskarUNO Sorry, I'm tagging you just to make sure you get the ticket :)

**Comment by fedamann** [comment]
Hi Lucie, I'll have a look at the entire list of pathologies and get back
to you.  I assume you have an entire bone that is not normal and has some
curvature, and it is not the results of ricketts or some other condition.

**Comment by LucieBiehlerGomez** [comment]
@fedamann thank your for your answer Franklin. Yes absolutely, we have a few bones with abnormal bending (not taphonomy- or trauma-related), rickets is the most probable diagnosis and consistent with our data on the population. So far, I wrote the lesion as Deformative and described it in the notes, but I thought it could be interesting for CoRa purposes to have a feature indicating bending, so I took the liberty of suggesting it.

**Comment by fedamann** [comment]
@LucieBiehlerGomez we have pathology broken into Categories and Characteristics. In this instance what do you think about Deformative as the Category and Rickets/Osteomalacia as the Characteristic?  This would only be applicable to long bones, and differination between Rickets and Osteomalacia would obviously depend on age profile.

**Comment by LucieBiehlerGomez** [comment]
@fedamann I completely agree on the distinction based on the age profile. Rickets and Osteomalacia would already be diagnoses, unlike most of your other characteristics (e.g., cribra orbitalia, porotic hyperostosis, cloaca, etc.) but it's true that bending occurs in only a few conditions (i.e., Rickets, Osteomalacia, Paget's disease). If you would like to divide in categories and characteristics, I would advice "bending", and then the differential diagnosis would be up to the anthropologist. Paget's is rare, so if you prefer Rickets/Osteomalacia, I would still be grateful for the addition of the new feature.

**Comment by fedamann** [comment]
@LucieBiehlerGomez Thank you for your comment. you are correct. Your comment reminds me --in a good way -- of the conversations our group had a few years ago when first setting up the pathology section. That being focus more on description and leave interpretation to write up and synthesis.  

That said what do you (or anyone else in the community) think about "Deformative - Bending" or "Deformative - Bowing" ?  Do you have a preference?  @tlvandeest did point out that Ortner calls it "bending deformity" 

@SachinPawaskarUNO can we shoot to get one of these in by this weekend, if possible?

**Comment by LucieBiehlerGomez** [comment]
@fedamann That's exactly how I - and Professor Cattaneo - view things as well. I personally prefer "bending", I think that's what I am most used to read and use, but I'm completely open to a different term. Thank you so much for your help.

**Comment by SachinPawaskarUNO** [comment]
@LucieBiehlerGomez Please verify this in PROD and close this issue if complete.
