### ISSUE TITLE
Associations between two elements only appear for one of the two elements in "Associations" column

### ISSUE THREAD

**Issue by mei215** [spawaskar-cora/cora-docs#646]
When a pair match exists between two elements, it is only indicated for one of those two elements in the Associations column (see humeri PM example in screenshot 1).

Similarly, articulations (and assuming also refits and morphologies) between two elements are only indicated for one of those two elements in the Associations column. For example, if a mandible articulates with 9 teeth (see screenshot 2), each tooth says it articulates with 1 element (the mandible), but instead of having 9 articulations, the mandible says it has 0 articulations 

![2](https://user-images.githubusercontent.com/33871387/106500127-13c56c00-6487-11eb-9942-1f43d5676d07.JPG)
![1](https://user-images.githubusercontent.com/33871387/106500137-158f2f80-6487-11eb-867c-111bdc721018.JPG)

 PROD environment, Edge

**Comment by SachinPawaskarUNO** [comment]
@mei215 Agree, this is  bug. I think I know what the reason is but need to look at code to verify and fix it.

**Comment by SachinPawaskarUNO** [comment]
@mei215 Can you please verify the fix for this in CAT environment?

**Comment by mei215** [comment]
@SachinPawaskarUNO can you please reset my CAT account? My CAT account has been inactive over 60 days so I cannot get in to verify the fix. Thanks!

**Comment by SachinPawaskarUNO** [comment]
@mei215 Inactivity lock has been reset. You may have to change your password because it has been over 90 days. Let me know if you do not remember your password and I can reset it for you.

**Comment by SachinPawaskarUNO** [comment]
@mei215 Great, I will get this into PROD later tonight. Please check tomorrow morning and close the ticket if verified.

**Comment by fedamann** [comment]
Thank you Sachin and Megan.

**Comment by mei215** [comment]
@SachinPawaskarUNO @fedamann verified in production and closed! thanks!
