### ISSUE TITLE
For zone search, add the number to description

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#65]
When doing the zones search/report it would be helpful to include the zone # along with the written description.  Currently, you can only see the number once you have conducted the search and then click on the description itself.

![zones desc](https://user-images.githubusercontent.com/35307698/37102232-0394ee62-21ed-11e8-8dd8-95b7c8e8e600.PNG)

![zones w number](https://user-images.githubusercontent.com/35307698/37102282-24795636-21ed-11e8-89ce-ccda4af124ee.PNG)

**Comment by SachinPawaskarUNO** [comment]
@cbrown311 @clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
