### ISSUE TITLE
Cranial anomalies

### ISSUE THREAD

**Issue by mcummaudo** [spawaskar-cora/cora-docs#651]
Dear @fedamann and @SachinPawaskarUNO,
would it be possible to add to Cora the following cranial anomalies?

Bipartite parietal bone
Bipartite temporal squama
Bipartite zygomatic bone
Craniopharyngeal canal
Foramen of Vesalius
Frontal bone porosity
Frontal grooves
Inca bone
Inferior squamous foramen
Infraorbital suture
Mandibular torus
Marginal tubercle
Mendosal suture
Mental tubercle
Mental spine
Nasal foramen
Nasofrontal ossicle
Occipito-mastoid ossicle
Paracondylar process
Pharyngeal foveola
Pharyngeal tubercle
Pterigospinous bridge
Pterion shape
Sagittal suture ossicle
Secondary anterior condylar canal
Secondary infraorbital foramen
Secondary mental foramen
Squamous ossicle
Superior squamous foramen
Supra-nasal suture
Supra-orbital notch
Zygomatic tubercle

Thank you
Marco

**Comment by fedamann** [comment]
Marco, This should be rather straightforward to add in.  I will ask you to
help though. Will you attach a list to this ticket that includes the
nonmetric traits you want listed in one column and the CoRA bone name(s)
that trait is found on in a separate column? Thank you in advance.
SIncerely,
Franklin

**Comment by mcummaudo** [comment]
Dear @fedamann and @SachinPawaskarUNO,
as requested, here is the list of nonmetric traits with the relative CoRA bone names:

Bipartite parietal bone				Parietal
Bipartite temporal squama			Temporal
Bipartite zygomatic bone		        Zygomatic
Craniopharyngeal canal				Sphenoid
Foramen of Vesalius				Sphenoid
Frontal bone porosity			        Frontal
Frontal grooves					Frontal
Inca bone						Parietal
Inferior squamous foramen			Temporal
Infraorbital suture					Maxilla
Mandibular torus					Mandible
Marginal tubercle					Zygomatic
Mendosal suture					Occipital
Mental tubercle					Mandible
Mental spine						Mandible
Nasal foramen						Nasal
Nasofrontal ossicle					Frontal
Occipito-mastoid ossicle				Temporal
Paracondylar process				Occipital
Pharyngeal foveolar				Occipital
Pharyngeal tubercle				Occipital
Pterigospinous bridge				Sphenoid
Pterion shape						*
Sagittal suture ossicle				Parietal
Secondary anterior condylar canal		Occipital
Secondary infraorbital foramen		Maxilla
Secondary mental foramen			Mandible
Squamous ossicle					Parietal
Superior squamous foramen			Temporal
Supra-nasal suture					Frontal
Supra-orbital notch					Frontal
Zygomatic tubercle					Zygomatic

*this is at the junction of temporal, sphenoid, parietal and frontal. Maybe it could be added to all these bones. 

Thank you!
Marco

**Comment by mcummaudo** [comment]
Dear @fedamann and @SachinPawaskarUNO ,
as requested, here is the list of nonmetric traits with the relative CoRA bone names:

Nonmetric trait | Bone
-- | --
Bipartite parietal bone | Parietal
Bipartite temporal squama | Temporal
Bipartite zygomatic bone | Zygomatic
Craniopharyngeal canal | Sphenoid
Foramen of Vesalius | Sphenoid
Frontal bone porosity | Frontal
Frontal grooves | Frontal
Inca bone | Parietal
Inferior squamous foramen | Temporal
Infraorbital suture | Maxilla
Mandibular torus | Mandible
Marginal tubercle | Zygomatic
Mendosal suture | Occipital
Mental tubercle | Mandible
Mental spine | Mandible
Nasal foramen | Nasal
Nasofrontal ossicle | Frontal
Occipito-mastoid ossicle | Temporal
Paracondylar process | Occipital
Pharyngeal foveola | Occipital
Pharyngeal tubercle | Occipital
Pterigospinous bridge | Sphenoid
Pterion shape | *
Sagittal suture ossicle | Parietal
Secondary anterior condylar canal | Occipital
Secondary infraorbital foramen | Maxilla
Secondary mental foramen | Mandible
Squamous ossicle | Parietal
Superior squamous foramen | Temporal
Supra-nasal suture | Frontal
Supra-orbital notch | Frontal
Zygomatic tubercle | Zygomatic

*this is at the junction of temporal, sphenoid, parietal and frontal. Maybe it could be added to all these bones.

Thank you!
Marco

**Comment by fedamann** [comment]
Thank you @mcummaudo !   

@SachinPawaskarUNO attached is the record from Marco with the added parent bone Cranium for the relevant specimen types.  The traits should be available for users if they select the specific cranial bone or the more general Cranium.    

[NonmetricTraitAdd.xlsx](https://github.com/spawaskar-cora/cora-docs/files/6264856/NonmetricTraitAdd.xlsx)
 would

**Comment by SachinPawaskarUNO** [comment]
@mcummaudo Please verify this in PROD and close this issue if complete.

**Comment by mcummaudo** [comment]
> @mcummaudo Please verify this in PROD and close this issue if complete.

Thank you!
