### ISSUE TITLE
Need to create function for methods with composite scores

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#67]
As discussed this morning, we need functionality to produce and display component scores for methods that have multiple components and rely on a composite score of those components in order to derive an age estimate.  The composite score is a sum of all component scores.  This is important because when we search for elements that are similar and define a range (+/- a certain value), we need the total score and not each score separately.

A help ticket will be created for each method that requires a composite score.

**Comment by SachinPawaskarUNO** [comment]
Related to issues #68, #69, #70

**Comment by clegarde** [comment]
Specific issue have been created for each method with composite score, so I'm closing this ticket.
