### ISSUE TITLE
DNA resample entry option

### ISSUE THREAD

**Issue by CTegtmeyer** [spawaskar-cora/cora-docs#689]
Okay, so it's been a good while since I've entered a ticket, so forgive me if this has been discussed before -

But is there a way we can get an option on the DNA entry page for resample information (e.g. if a DNA sample has been through an A, B, and C sample):

For example, maybe A and B failed but C reported a sequence. I don't just want to report C because I think it's important to also reflect the information from A and B?

(I and going back through and entering Tarawa's DNA results, so if this feature exists and I am just missing it, please let me know).

Thanks!

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer, adding on to what @clegarde mentioned in her email.
CoRA has a concept called as consensus DNA which is essentially the DNA profile view for a given specimen which is information consolidated from multiple DNA samples for that specimen.

@clegarde email comment.
Hi Caryn,
I’m away from my desk and don’t remember my GitHub password to comment…
In this case, you can create a sample for every resample, then add the results for each sample. Right now, we can’t add several results of the same testing to one sample. We might need to come up with a way to do this though. 
Thanks,
Carrie

**Comment by SachinPawaskarUNO** [comment]
@CTegtmeyer @clegarde Here is a sample screenshot from the USS Oklahoma project.
![image](https://user-images.githubusercontent.com/19599773/145884948-eca37e94-f5a3-4e12-a665-a946fac6adcb.png)

**Comment by CTegtmeyer** [comment]
Acknowledged! Thanks for showing me!

Closing the issue! Appreciate the help!
