### ISSUE TITLE
Composite score - Meindl and Lovejoy 1985 (cranium, vault)

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#70]
Create composite score that is sum of 7 scores for the vault sutures in Meindl and Lovejoy 1985 (cranium):  midlambdoid, lambda, obelion, anterior sagittal, bregma, midcoronal, and pterion.  Each suture can be scored from 0 to 3.

**Comment by tedunn** [comment]
As per today's discussion, the composite score for this method is the sum of a subset of the scores mentioned in the article. @clegarde @SachinPawaskarUNO

**Comment by skindsc1** [comment]
Until the CoRA Analytics app is up and running, can we add a box labeled "Composite Score" that can then be searchable using a Methods search?

**Comment by clegarde** [comment]
Looks good. Combined with #71
