### ISSUE TITLE
Composite score - Nawrocki 1998 (cranium, SUMALL)

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#72]
Create composite score that is sum of 27 scores for all cranial sutures in Nawrocki 1998 (cranium): 
![image](https://user-images.githubusercontent.com/35307698/37427740-4414a116-2798-11e8-8532-8b0d0aa98ba5.png)

Each suture can be scored from 0 to 3.

**Comment by skindsc1** [comment]
Until the CoRA Analytics app is up and running, can we add a box labeled "Composite Score" that can then be searchable using a Methods search?

**Comment by clegarde** [comment]
Looks good, combined with #73 by #111
