### ISSUE TITLE
Composite score - Nawrocki 1998 (cranium, SUMCAL)

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#73]
Create composite score that is sum of 15 scores for uppermost cranial sutures in Nawrocki 1998 (cranium): 
![image](https://user-images.githubusercontent.com/35307698/37427811-6d5584be-2798-11e8-8993-e899229f659c.png)
![image](https://user-images.githubusercontent.com/35307698/37427824-77771232-2798-11e8-8d94-15f9b69c0659.png)

Each suture can be scored from 0 to 3.

**Comment by tedunn** [comment]
As per today's discussion, the composite score for this method is the sum of a subset of the scores mentioned in the article. @clegarde @SachinPawaskarUNO

**Comment by skindsc1** [comment]
Until the CoRA Analytics app is up and running, can we add a box labeled "Composite Score" that can then be searchable using a Methods search?

**Comment by clegarde** [comment]
Looks good, combined with #72
