### ISSUE TITLE
Add null value when element not scored for age

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#75]
When an element that has a feature that could be scored for age, but it has not been scored, there should be a way to indicate a null value and not have a default entry of 0.  For scoring purposes, several methods have values of 0, so it is not possible to tell if the element was scored a 0 or not scored.  

The default should probably also not be blank, as this would be indistinguishable from something that was simply forgotten, but what are everyone's thoughts on this?  @clegarde @fedamann @skindsc1

**Comment by clegarde** [comment]
Agreed! I think that's an important distinction that needs to be reflected somehow. Can it say "Unscorable"? Is that a word? Or something like that...maybe just "NS" for not scored? I don't think NA accurately reflects it being something that cannot be scored, but could be the easiest option.

**Comment by cbrown311** [comment]
@mei215 @Lariabeth @emilystreetman @sfuehr @brittanywalter

**Comment by skindsc1** [comment]
I like the idea of using something like "NS" that specifically means the trait is present but hasn't been scored.  N/A could mean the trait is missing altogether or that it couldn't be scored.  Could the default be something like "Choose score from dropdown" that just serves as a placeholder?

@cbrown311 @clegarde

**Comment by SachinPawaskarUNO** [comment]
@cbrown311 @clegarde @skindsc1 This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by skindsc1** [comment]
@clegarde Are you happy with this?

**Comment by emilystreetman** [comment]
@skindsc1 @clegarde For the tibia, looks like "Select Option" has been retained as the no-entry default. This makes sense to me. I'll leave it to others who have weighed in previously to close this ticket, though.

![age method null](https://user-images.githubusercontent.com/34662044/38566205-ab479ca4-3cd2-11e8-9df4-b672d8e9026c.jpg)

**Comment by clegarde** [comment]
This seems appropriate. Closing.
