### ISSUE TITLE
Order of measurement numbers - fix to ascending order

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#77]
![measurement numbering issue](https://user-images.githubusercontent.com/35307698/37428550-925edcc2-279a-11e8-86f6-3fc599e393e5.PNG)

Measurements appear out of order for at least os coxa, possibly other bones.  Measurements should be in ascending order.

**Comment by SachinPawaskarUNO** [comment]
@cbrown311 This issue has been addressed with a new release. Please verify and close issue.

**Comment by clegarde** [comment]
Checked - GTG.
