### ISSUE TITLE
Add rollover for zone description

### ISSUE THREAD

**Issue by cbrown311** [spawaskar-cora/cora-docs#78]
Add a rollover description for each zone of each bone that gives definition of what zone is, next to number.  Do not add description as part of number in order to avoid clutter on this page per @fedamann

**Comment by SachinPawaskarUNO** [comment]
@cbrown311 @clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
