### ISSUE TITLE
Generate Association Report by Individual Number and/or Mito Seq Number

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#80]
We should be able to generate an association report by Individual number and/or DNA Seq - so we could query all the methods and/or measurements done for an individual. I think it would be best to have both options so you could look up by either (in case MNI >1 for a sequence). Thoughts? @cbrown311 @mei215
Add option to generate association report "By Individual Number" and "By Mito Sequence Number"
![screen shot 2018-03-15 at 9 23 49 pm](https://user-images.githubusercontent.com/7350474/37500381-37e344ce-2897-11e8-9a70-938a5694b977.png)

**Comment by mei215** [comment]
#48

**Comment by cbrown311** [comment]
Let me make sure I am understanding this correctly, we want the ability to see what has been associated with elements from an individual or a sequence?  As in, I-01 has these elements based on DNA, these based on pair matching, these based on articulation, etc.  I ask because I am not seeing any of those options currently and can't get the search to even work in Association Report, so perhaps some things are still being worked on?

**Comment by clegarde** [comment]
I just put this issue in to add a "search by" option based on the current outputs. For example, you can search by an X# (ex: X-232C) to generate a measurement list, and it will give you a list of all the elements in that X# with their measurements. What I'm asking for here is to be able to search by an I# to generate a measurement list for all elements associated with that I#. Or Mito Seq. 
Not even going into the associations because I think that hasn't been developed yet. This is just to add another "search by" option.

**Comment by cbrown311** [comment]
Ok, I like it.  Sorry for making more complicated!

**Comment by emilystreetman** [comment]
Looks like the Sequence Report exists in the new reports dashboard, but there is still no search by I-# possible. This was discussed in the meeting on 11Apr18, and I think @SachinPawaskarUNO said it could be added easily.

![mito report](https://user-images.githubusercontent.com/34662044/38879120-317c0c1a-4228-11e8-95ca-c80c10999e35.jpg)

**Comment by SachinPawaskarUNO** [comment]
@clegarde Please take a look at this issue to see if we are missing something that has not already been addressed in the new v1.0.0 in CAT.

**Comment by clegarde** [comment]
GTG
