### ISSUE TITLE
Zone check box not marked

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#83]
I performed a zone search but none of the check boxes were marked to show which zones are present.  For example, I searched for Zone 6 but when I open the element highlight it does not indicate Zone 6 is present.

![image](https://user-images.githubusercontent.com/21186879/38263622-26c2b884-3736-11e8-91fe-2168568e2896.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue should have been fixed, please test and close out if verified
