### ISSUE TITLE
Complete elements only show up as Zone 1

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#84]
When searching for a zone, searching for Zone 1 will pull up all complete elements and only the Zone 1 box will be checked as being present.  In the below example I searched for Zone 1 only.  Zone 1 is the only zone marked as present even though the bone is complete.  

![image](https://user-images.githubusercontent.com/21186879/38263885-f0bb0934-3736-11e8-9023-7d39bf2c8b91.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 this is an issue with old data that is not in  sync. Currently when any new SE is created and you mark it as complete then all zones for the Bone are marked as complete. This is not true for the old USS Oklahoma dataset that was uploaded. Hence the issue you are seeing.
@fedamann we need to at some point have someone go through all complete bones and re-save to make sure the data for zones is correctly populated. Maybe something the intern can do. 
Or write a script/program and using a programming resource. 
Please note again this is a onetime issue with USS Oklahoma dataset only.

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue should have been fixed, please test and close out if verified
