### ISSUE TITLE
create CoRA account for Karen Foreman

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#88]
create CoRA account for Karen Foreman

**Comment by karenforeman** [comment]
@SachinPawaskarUNO  Confirmed GitHub and Cora. Currently have access to Cora demo, can you please add USS Oklahoma project? Thank you, Karen Foreman

**Comment by SachinPawaskarUNO** [comment]
@karenforeman This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by karenforeman** [comment]
@SachinPawaskarUNO  Good morning! I now have access to CoRA- USS Oklahoma and CoRA Demo.
Thank you, I am closing this ticket.

**Comment by karenforeman** [comment]
I do not have an option to close this ticket, I asked @clegarde  to please close this ticket for me.
Thank you, Karen Foreman

**Comment by karenforeman** [comment]
Thank you Carrie!
K

-----Original Message-----
