### ISSUE TITLE
Remove fields UM2C6-UM2C10 from Edgar 2013 - Cranium

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#90]
Please remove the last five fields - UM2C6 through UM2C10 - for the Edgar 2013 ancestry method for the cranium. These do not exist. 

![edgar 2013_field names](https://user-images.githubusercontent.com/7350474/38329824-78ed50b6-383e-11e8-9dc3-1f5bc49eafdb.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde, these were from the original methods and method features spreadsheet. I just want to confirm, was this an error in the original files we received? It is easy to take these off, I just want to make sure these are not features that we incorrectly assigned to cranium from some other Bone. Can you please confirm that the method features we are planning on removing are not used anywhere at all and the ones we have for cranium are complete?

**Comment by clegarde** [comment]
Yes, this was an error in the original data. This method applies to both the cranium and mandible, since it applies to teeth, so I double-checked the method for the mandible and those labels are correct.

**Comment by clegarde** [comment]
GTG
