### ISSUE TITLE
In DNA Profile "Analysis Tests" should read "Additional Tests"

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#92]
![analysis tests](https://user-images.githubusercontent.com/34662044/38378527-8cec2ace-38ed-11e8-8f4b-0b8df8b94a79.jpg)

**Comment by emilystreetman** [comment]
Header verified as corrected, additional location of the phrase "analysis tests" noted in the below image, please update to "additional tests" as well. 

![Uploading analysis tests2.jpg…]()

**Comment by emilystreetman** [comment]
and "for this DNA" in the same line should read "for this DNA sample"

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by emilystreetman** [comment]
Verified as fixed - closing ticket
