### ISSUE TITLE
In DNA Profile>Analysis Tests Dropdown, "NGS" should also be an option

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#93]
Per Greg Berg's comments in scrum 4 April 18

![ngs](https://user-images.githubusercontent.com/34662044/38378664-ef385888-38ed-11e8-9434-fea29586138d.jpg)

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman Can you please provide me with a short description or what the Acronym stands for? I need to include this in the table.

**Comment by emilystreetman** [comment]
Yes! Sorry!
Next Generation Sequencing

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by emilystreetman** [comment]
Verified that this issue has been addressed

Closing ticket
