### ISSUE TITLE
In Cranium > Age > Methods dropdown, Nawrocki 1998 is repeated

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#94]
I suspect this should be differentiated like the two "Meindl and Lovejoy 1985" entries are in the same list - with a clarification. 

![cranium age methods](https://user-images.githubusercontent.com/34662044/38378981-d63cf180-38ee-11e8-8a18-73651953755a.jpg)

Clicking "create" for either listing of the method leads to a blank page with only a broken image icon, so I'm not sure about what the labels should be.

![nawrocki blank page](https://user-images.githubusercontent.com/34662044/38379086-28d4eef2-38ef-11e8-8227-e3557db5faf4.jpg)

**Comment by emilystreetman** [comment]
this is related to tickets #72 and #73

**Comment by clegarde** [comment]
This has been taken care of with combining the methods into one. #111
