### ISSUE TITLE
In DNA > mtDNA Report, mito sequence number search drop-down menu should be in numerical order

### ISSUE THREAD

**Issue by emilystreetman** [spawaskar-cora/cora-docs#95]
![dna order](https://user-images.githubusercontent.com/34662044/38382215-e685bcf4-38ce-11e8-9aae-9d93ee1626c8.jpg)

**Comment by SachinPawaskarUNO** [comment]
Currently the field is a alphanumeric field, hence it is now been display in alphanumeric order. We need to discuss if this can be made into a number only field.

**Comment by SachinPawaskarUNO** [comment]
@emilystreetman This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by emilystreetman** [comment]
Verified and confirmed as addressed. Closing ticket.
