### ISSUE TITLE
Measurements page is unavailable for the mandible

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#96]
Under the Skeletal Element, when you go to details, "Measurements" is not an option in the dropdown menu. I think this must be a bug since there are measurements for the mandible.
![measurements_mandible](https://user-images.githubusercontent.com/7350474/38443453-526b37ae-39b1-11e8-87a2-b194cd604be4.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde, Good catch. This is actually a data issue with the original baseline data provided by DPAA Anthropologists. It seems like there is quite a bit of missing data.
@fedamann I'm seeing a lot of data issues like this with regards to baseline data provided. The only way to identify these types of issues is to make sure that DPAA Anthropologists test the system and create SE's for all Bones and go through every screen/association data for that Bone. 

I'm also seeing missing data for articulations based on #86 identified by @CTegtmeyer

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
