### ISSUE TITLE
Features out of order for Edgar 2013 - Mandible

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#97]
The features listed are out of order. LCDR (canine) usually comes after LI2SS (incisor). Just to be sure there aren't data entry mistakes, it would be best to put it after LI2SS.
![mandible_edgar 2013](https://user-images.githubusercontent.com/7350474/38443921-fde2cf7e-39b2-11e8-834c-e65a1c0e0ec2.PNG)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
GTG
