### ISSUE TITLE
Identify Bones that are flagged as having articulations but do not have base data setup for articulations

### ISSUE THREAD

**Issue by SachinPawaskarUNO** [spawaskar-cora/cora-docs#98]
Identify Bones that are flagged as having articulations but do not have base data setup for articulations. Related to #86

**Comment by emilystreetman** [comment]
Updated articulations list sent to @clegarde via DPAA email

**Comment by clegarde** [comment]
@SachinPawaskarUNO @fedamann @emilystreetman 
[Bone articulations 16Apr18 ENS_updated.xlsx](https://github.com/spawaskar-cora/cora-docs/files/1916188/Bone.articulations.16Apr18.ENS_updated.xlsx)

**Comment by emilystreetman** [comment]
This ticket is related to #91 - create an articulations report by @CTegtmeyer

**Comment by SachinPawaskarUNO** [comment]
@clegarde and @emilystreetman This issue has been addressed with a new release. Please verify and close issue if verified.

Please verify that you can add some of the new created articulations.

@CTegtmeyer You may also want to try and test that you can create articulations for hand and foot bones.

**Comment by CTegtmeyer** [comment]
@emilystreetman I closed issue #136 however, I am unable to close this issue because I am not assigned to this one. But I am okay with it being closed if you want to close it.

**Comment by emilystreetman** [comment]
Closing along with #136 and following discussion with @CTegtmeyer
