### ISSUE TITLE
Create ability to search for a single element

### ISSUE THREAD

**Issue by skindsc1** [spawaskar-cora/cora-docs#99]
Create an option that will allow a search by the element's entire identification number, i.e., CIL 2003-116-G-27-X-184B-201 so that a single bone can be directly located.  

![image](https://user-images.githubusercontent.com/21186879/38498702-e7bffe28-3bca-11e8-9c77-b6966dfefe4a.png)

**Comment by SachinPawaskarUNO** [comment]
@skindsc1 This issue has been addressed with a new release. Please verify and close issue if verified. You will have to use **accession_number,provenance1,provenance2,designator**. Note the each is separated by a **, [comma with no spaces]**

**Comment by skindsc1** [comment]
@SachinPawaskarUNO, Could you give an example of the formatting of the composite key using the following number?  I have been unable to search for an element.  Example: CIL 2003-116-G14-X253A-201

**Comment by skindsc1** [comment]
@SachinPawaskarUNO Perfect!  I am going to close this ticket but I think we may need to open a new one to figure out a place to put an example of the way the composite key goes together.  I was originally thinking that no hyphens can be present anywhere which is why I was having an issue searching.
